camunda/camunda-modeler

- app/lib/deploy.js
- app/lib/index.js
- package-lock.json
- package.json
When trying out the new deploy feature in the Camunda modeler distribution (build via `npm run all`) I realized that using `request` does not work / is not available.
An alternative is to install the `request` module. It is however bloated and uses an old API.
This PR changes the deploy function to use got:
* got has way smaller bundle size and a, modern, promise based API
* works in packaged distribution
Additional changes:
* don't pass raw strings as errors to done (in `app/lib/deploy`). Instead, pass an error that got meta-data such as stack trace attached
* in `app/index.js` log error and extract error message to be sent to client
> chore(app): use <got> instead of <request> to deploy

- client/lib/app/tabs/bpmn/initial.bpmn
- client/lib/app/tabs/bpmn/provider.js
- client/lib/app/tabs/cmmn/initial.cmmn
- client/lib/app/tabs/cmmn/provider.js
- client/test/spec/app/app-spec.js
Make sure that new diagrams get random IDs assigned.
This way we prevent clashing in deployments and so on.
Closes #736
> feat(editor): generate random definition IDs for new diagrams

- app/lib/dialog.js
- app/lib/file-system.js
- app/lib/index.js
- app/test/helper/mock/electron-dialog.js
- app/test/spec/dialog-spec.js
This uses the browserWindow option to make dialogs actual modal windows.
As a result the menu on the parent window is no longer clickable and
does not receive key strokes. In my opinion this should be the desired behavior.
> chore(app): make dialogs actual modal windows

- client/lib/app/editor/bpmn-editor.js
- client/lib/app/editor/cmmn-editor.js
- client/lib/app/editor/dmn-editor.js
- client/lib/app/editor/dmn/CamundaDmnEditor.js
Makes sure `EDIT` menu is updated on both direct editing cancel and complete.
> Update state on direct editing cancel/complete

- .eslintignore
- client/src/app/App.js
- client/src/app/Log.js
- client/src/app/Log.less
- client/src/app/__tests__/AppSpec.js
- client/src/app/__tests__/LogSpec.js
- client/src/app/primitives/Tabbed.less
- client/src/app/tabs/PropertiesContainer.js
- client/src/app/tabs/bpmn/__tests__/BpmnEditorSpec.js
- client/src/app/tabs/xml/XMLEditor.less
- client/src/util/dom/dragger.js
> Restore log component

- client/src/app/App.js
- client/src/app/TabsProvider.js
- client/src/app/__tests__/AppSpec.js
- client/src/app/__tests__/TabsProviderSpec.js
- client/src/app/__tests__/mocks/index.js
Misc changes, as discussed.
Tabs may use the `onAction` props now to trigger app actions (cf. https://github.com/camunda/camunda-modeler/commit/c314b77df21039919a186b3a64e6da54809e178a#diff-ac4ca2a9a20657e33b44fd3d789a606dR875).
> App improvements

- app/package.json
- client/package-lock.json
- client/package.json
- package-lock.json
Did a min-dash release to fix broken `{ isUndefined, isDefined }` utilities.
Would be great to merge it soon.
> chore(client): bump min-dash dependency

- app/lib/file-system.js
- app/test/spec/file-system-spec.js
This PR fixes a broken behaviour of `saveAs` button which would not actually save any files.
Closes #962
> 962 create a file when new diagram is saved

- app/lib/dialog.js
- app/lib/index.js
- app/test/spec/dialog-spec.js
- client/src/app/App.js
- client/src/app/TabsProvider.js
- client/src/app/__tests__/AppSpec.js
- client/src/app/__tests__/mocks/index.js
- client/src/app/tabs/MultiSheetTab.js
- client/src/remote/Dialog.js
- client/src/remote/__tests__/DialogSpec.js
Closes #976 
Closes #975 
Since the unrecognized file dialog is related to the empty file handling, I've just combine the refactoring of both dialogs in this pull request. 
- Restore empty file dialog
- Restore unrecognized file dialog
- Remove harcoded dialogs [1]
[1] the hardcoded `unrecognized-file` dialog is used in [another event](https://github.com/camunda/camunda-modeler/blob/next/app/lib/index.js#L311) as well. This should be refactored in another place, e.g. in #971
> 976 refactor empty file and unrecognized file dialog

- client/src/app/tabs/bpmn/BpmnEditor.js
- client/src/app/tabs/cmmn/CmmnEditor.js
- client/src/app/tabs/dmn/DmnEditor.js
Context:
* XML import might finish after editor was unmounted (e.g. scrolling through tabs quickly)
* making sure that import is only handled if editor is mounted fixes this warning
Closes #934
> Only handle import if editor mounted

- client/src/app/App.js
- client/src/app/__tests__/AppSpec.js
- fixes the throwed exception on open empty files
- adds test for correct function call
Closes #1036
> fix(client): use correct type param to empty file dialog

- client/src/app/AppParent.js
- client/src/app/__tests__/AppParentSpec.js
- client/src/app/__tests__/mocks/index.js
- client/webpack.config.js
* ensures we ship with source maps so that actual errors are logged with full stack traces
* unifies error logging in `AppParent`
> Source maps

- client/src/app/tabs/bpmn/getBpmnEditMenu.js
- client/src/app/tabs/dmn/DmnEditor.js
- client/src/app/tabs/getEditMenu.js
- client/test/mocks/dmn-js/Modeler.js
This PR fixes menu entries that weren't working. It doesn't fix issues with undo and redo behavior, these are to be tackled when fixing the dirty checking of all editors.
I've created a seperate issue for undo/redo behavior when editing DMN decision table cells: https://github.com/camunda/camunda-modeler/issues/1061
Closes #1024
> 1024 fix menu entries

- client/src/app/App.js
- client/src/app/__tests__/AppSpec.js
Gets rid of a `TODO` in the app.
> feat(app): mark tab created from empty file as dirty

- app/lib/menu/menu-builder.js
- client/src/app/App.js
- client/src/app/__tests__/AppSpec.js
* ensures we only show the edit menu, if the
client provides it
* the empty tab does not provide it, thus
it is disabled without a tab open
Closes #1070
> fix(app): activate edit menu if provided only

- client/src/app/Log.less
- client/src/app/__tests__/LogSpec.js
Closes #1079
Testing: Unfortunately it seems to be not possible to test the behavior of `window.getSelection`, `selection.addRange` to test the current selection and `navigator.clipboard` or else to test the current clipboard content.
> fix(client/Log): (re)-enable log copy

- client/src/app/tabs/bpmn/BpmnEditor.js
- client/src/app/tabs/bpmn/__tests__/BpmnEditorSpec.js
- client/src/app/tabs/cmmn/CmmnEditor.js
- client/src/app/tabs/cmmn/__tests__/CmmnEditorSpec.js
- client/src/app/tabs/dmn/DmnEditor.js
- client/src/app/tabs/dmn/__tests__/DmnEditorSpec.js
- client/test/mocks/bpmn-js/Modeler.js
- client/test/mocks/cmmn-js/Modeler.js
- client/test/mocks/dmn-js/Modeler.js
The properties panel will now be resized whenever its layout changes.
Closes #1080
> feat(editors): resize properties panel along with editor

- app/lib/file-system.js
- app/test/spec/file-system-spec.js
- client/src/app/TabsProvider.js
- client/src/app/__tests__/TabsProviderSpec.js
- client/src/app/__tests__/mocks/index.js
- client/src/app/tabs/bpmn/BpmnEditor.js
- client/src/app/tabs/cmmn/CmmnEditor.js
- client/src/app/tabs/dmn/DmnEditor.js
* change jpg to jpeg
> Note: Without integration tests #1103 cannot be tested. Extension is passed from `App` to editor.
* remove point from extensions
> Note: Must be tested manually since we mock dialogs during testing.
Closes #1102
Closes #1103
> fix(client): fix image export

- client/src/app/tabs/dmn/DmnEditor.js
- client/src/app/tabs/dmn/__tests__/DmnEditorSpec.js
Closes #1100
This fixes the input blurring inside the `dmn-js-properties-panel` by preventing reattaching the properties panel on every element change. Therefore it checks whether the new `dmn-js view` is different from the previous one and only reattaching the properties panel when there is an actual view switch.
What is not part of this PR is the fact we should consider refactoring the way the `views.changed` is fired inside `dmn-js` (https://github.com/bpmn-io/dmn-js/issues/388)
> fix(client/dmn-editor): prevent reattaching properties panel

- client/karma.config.js
- client/src/app/util/__tests__/diagram.svg
- client/src/app/util/__tests__/generateImageSpec.js
- client/src/app/util/generateImage.js
Ends up with better to read diagrams while ensuring
diagram sizes are still O.K. (4.5MB for a huge diagram).
Closes #486
> chore(export): scale pixel images by factor 3

- client/src/app/App.js
- client/src/app/__tests__/AppSpec.js
- client/src/app/primitives/TabLinks.js
- client/src/app/primitives/__tests__/TabLinksSpec.js
- client/src/app/primitives/__tests__/mocks/index.js
* seperate concepts of unsaved and dirty tabs
* pass maps of unsaved and dirty tabs instead of callback
* maps will be re-created whenever there's a relevant change
Closes #1117
> fix(client): pass dirty tabs as prop to tab links

- client/src/app/App.js
- client/src/app/modals/ModalConductor.js
- client/src/app/modals/keyboard-shortcuts/KeyboardShortcutsModal.js
- client/src/app/modals/keyboard-shortcuts/View.js
- client/src/app/modals/keyboard-shortcuts/View.less
- client/src/app/modals/keyboard-shortcuts/__tests__/KeyboardShortcutsModalSpec.js
- client/src/app/modals/keyboard-shortcuts/getShortcuts.js
- client/src/app/modals/keyboard-shortcuts/index.js
- client/src/index.js
Restoring the keyboard shortcuts overlay
Closes #1039 
Closes #1040
> feat(client): restore keyboard shortcuts overlay

- client/src/app/KeyboardBindings.js
- client/src/app/__tests__/KeyboardBindingsSpec.js
Removes also check for darwin as the hook is required also for MacOS.
Closes #1119
> fix(KeyboardBindings): bind redo to cmd+shift+z

- .travis.yml
- package-lock.json
- tasks/distro.js
Applies the nightly build fixes in https://github.com/zeebe-io/zeebe-modeler/pull/46 to the Camunda Modeler, too.
Actual fixes: https://github.com/camunda/camunda-modeler/pull/1129/commits/f9832f35c72fdee64c45ac084edb9e2a011e0378, the rest is cleanup.
> Fix broken nightly builds

- client/src/app/App.js
- client/src/app/__tests__/AppSpec.js
- client/src/app/tabs/MultiSheetTab.js
- client/src/app/tabs/__tests__/MultiSheetTabSpec.js
We will no longer handle contents change in App component. It's moved to MultiSheetTab now.
Closes #1122
Closes #403
> fix(client/BpmnEditor): mark tab as dirty after namespace conversion

- CHANGELOG.md
- package-lock.json
- package.json
It could make sense to update to the latest `electron@3.x`, as we are introducing breaking changes anyway. Needs testing on MacOS and Windows.
> Update to electron@3.1.1

- client/src/app/App.js
- client/src/app/__tests__/AppSpec.js
- client/src/app/__tests__/mocks/index.js
- client/src/app/drop-zone/DropZone.js
- client/src/app/drop-zone/DropZone.less
- client/src/app/drop-zone/__tests__/DropZoneSpec.js
- client/src/app/drop-zone/index.js
- client/src/app/tabs/xml/CodeMirror.js
Closes #1085 
Closes #571
Regarding #571, dropping a text to XML editor is still possible, whereas dropping a file will trigger file opening action.
> feat(client/App): add file drop feature

- .eslintignore
- app/lib/index.js
- client/webpack.config.js
Serve files in DEV mode via the `file://` protocol, too.
Cf. https://github.com/camunda/camunda-modeler/commit/f9edd19c31c28bdc7f6b6dc8f1e9474fb95a8ec1 for rationale.
> Serve via file protocol in dev mode, too

- client/src/app/tabs/dmn/getDmnEditMenu.js
- client/src/app/tabs/dmn/modeler/DmnModeler.js
- client/src/app/tabs/dmn/modeler/features/decision-table-keyboard-bindings/DecisionTableKeyboardBindings.js
- client/src/app/tabs/dmn/modeler/features/decision-table-keyboard-bindings/__tests__/DecisionTableKeyboardBindingsSpec.js
- client/src/app/tabs/dmn/modeler/features/decision-table-keyboard-bindings/index.js
Closes #1061 
Following keyboard bindings were already being implemented, they were not integrated inside the dmn-js [Keyboard feature](https://github.com/bpmn-io/dmn-js/blob/master/packages/dmn-js-decision-table/src/features/keyboard/Keyboard.js):
- TAB / SHIFT + TAB navigate cells (horizontally)
- CTRL+ENTER adds a new line in the cell
Following keyboard bindings are integrated by a39223f:
- Undo / Redo works as expected, via command stack operation
- ENTER / SHIFT + ENTER navigate cells (vertically)
62f4c1a also restores the edit menu entries for `selectCellBelow` and `selectCellAbove` as it was before in `camunda-modeler` version `v2.2.4`.
During the integration, I encountered a problem regarding missing keyboard bindings inside the dmn diagram editor. I opened an according issue …
> Properly wire all decision table keyboards shortcuts

- client/src/app/tabs/bpmn/__tests__/BpmnEditorSpec.js
- client/src/app/tabs/cmmn/__tests__/CmmnEditorSpec.js
- client/src/app/tabs/dmn/__tests__/DmnEditorSpec.js
- client/src/app/tabs/dmn/getDmnEditMenu.js
- client/test/mocks/dmn-js/Modeler.js
Closes #1146 
- Add missing editMenu entries for `moveCanvas` and `moveSelection` for DMN drd tab
- Add test coverage for edit menu entries for `DmnEditor`, `CmmnEditor`, `BpmnEditor`
Note #1148 also adds editMenu entries for the `DmnEditor`. Therefore it might be a good idea adding some test coverage there after this pr is merged.
> Add moveCanvas and moveSelection editMenu actions for drd

- app/lib/platform/mac-os/index.js
This should fix a regression introduced in https://github.com/camunda/camunda-modeler/commit/64431481b6f6935e09d5052ff176f7bc5c9f4d12.
The event `app:open-file` is no longer emitted.
> fix(app): re-activate app on <open-file>

- client/src/app/App.js
- client/src/app/__tests__/AppSpec.js
- client/src/app/util/__tests__/executeOnceSpec.js
- client/src/app/util/executeOnce.js
Closes #1118
This pull request provides a proper solution to overcome the problem described #1118 on a windows machine.
The bug is internally caused by the fact that the [`mainWindow#focus`](https://github.com/camunda/camunda-modeler/blob/master/app/lib/index.js#L356) event is triggered twice. Therefore the [contentChanged-dialog](https://github.com/camunda/camunda-modeler/blob/master/client/src/app/App.js#L224) is opened twice.
Except for other platforms, e.g. [macOS](https://electronjs.org/docs/api/dialog#sheets), the dialogs on _Windows_ have its own focus, and are not attached to the `mainWindow`. That means on the time the user clicks on some action of the contentChanged-dialog, the dialog's got closed and it will focus the `mainWindow` a second time. Surely we have a check that the …
> Create locking mechanism for check file changed

- app/lib/flags.js
Logs active flags so we can easier debug what's going on with the users installation.
> chore(app): log active flags

- client/src/app/App.js
- client/src/app/primitives/TabLinks.js
- client/src/app/primitives/__tests__/TabLinksSpec.js
- client/src/app/primitives/__tests__/mocks/index.js
- client/src/remote/Backend.js
- client/src/remote/__tests__/BackendSpec.js
- client/src/remote/__tests__/mocks/index.js
- client/src/remote/index.js
Closes #1187
---
__Note to Reviewer:__ This deliberately excludes the convenience feature of representing the user home as `~` on Mac OS and Linux. We must internally represent files as absolut paths but display them to the user in a localized manner, something that we cannot simply / quickly implement right now.
> 1187 diagram discovery

- client/package-lock.json
- package-lock.json
This builds upon https://github.com/camunda/camunda-modeler/pull/1264 and bumps the selection-ranges dependency. `v3.0.0` accidently pulled in large parts of the babel toolchain :woman_cartwheeling:
> Up selection ranges

- client/package-lock.json
- client/package.json
`<= v6.2.1` did not properly destroy child viewers.
Cf. bpmn-io/dmn-js#392
> chore(client): bump dmn-js version

- resources/platform/base/resources/plugins/README.md
- tasks/after-pack.js
- tasks/after-pack/add-platform-files.js
This builds upon https://github.com/camunda/camunda-modeler/pull/1271 and ensures we only ship tagged links to documentation (not references to `master`).
Closes #1178
> Reference tagged documentation in distribution only

- NOTICE
- THIRD_PARTY_NOTICES
- client/package-lock.json
- client/package.json
- client/webpack.config.js
- docs/.project/THIRD_PARTY_NOTICES.md
- package-lock.json
- package.json
- tasks/after-pack/add-platform-files.js
- tasks/license-book.js
- tasks/test-distro.js
This builds upon https://github.com/camunda/camunda-modeler/pull/1272 and hooks license book bundling into our release procedures.
__TLDR__
License book...
* is checked into project as `THIRD_PARTY_NOTICES` file
* is updated as `prerelease` script
* is packed into distribution as `THIRD_PARTY_NOTICES.camunda-modeler.txt`
__Visual Flow__
Closes #1233
> Generate + bundle license book

- client/src/app/tabs/dmn/DmnEditor.js
- client/src/app/tabs/dmn/__tests__/DmnEditorSpec.js
This is fixing one problem inside #1228: When making changes inside the drd and switching to another view (e.g. Literal Expression), the dirty state got lost. Therefore with this pull request, we properly set the dirty state when the switch is happening.
Note: the second bug described in #1228 is still happening.
> fix(dmn): set dirty state on views changed

- client/src/app/tabs/bpmn/BpmnEditor.js
- client/src/app/tabs/bpmn/__tests__/BpmnEditorSpec.js
- client/src/app/tabs/cmmn/CmmnEditor.js
- client/src/app/tabs/cmmn/__tests__/CmmnEditorSpec.js
- client/src/app/tabs/dmn/DmnEditor.js
- client/src/app/tabs/dmn/__tests__/DmnEditorSpec.js
In the current modeler version (`v3.0.0-beta.2`) the [token simulation plugin](https://github.com/bpmn-io/bpmn-js-token-simulation-plugin) is turned on every time the user presses  'T', regardless an input is active. This pull request adds the missing `inactiveInput` property to the `BpmnEditor`, to ensure [the menu item got disabled](https://github.com/bpmn-io/bpmn-js-token-simulation-plugin/blob/master/menu.js#L10). 
It also adds this property to the other editors to ensure backward compatibility.
Closes https://github.com/bpmn-io/bpmn-js-token-simulation-plugin/issues/14.
Relates to https://github.com/camunda/camunda-modeler/issues/1193.
> Add missing input active properties

- client/src/app/slot-fill/FillContext.js
- client/src/app/slot-fill/__tests__/FillSpec.js
- client/src/app/tabs/bpmn/__tests__/BpmnEditorSpec.js
- client/src/app/tabs/cmmn/__tests__/CmmnEditorSpec.js
- client/src/app/tabs/dmn/__tests__/DmnEditorSpec.js
- client/src/app/tabs/xml/__tests__/XMLEditorSpec.js
Done via providing default context value for FillContext.
Main benefit of the change is that it's now possible to set props on editor wrappers via enzyme setProps method.
Example:
```javascript
it('should import new XML', async function() {
// given
const onImport = sinon.spy();
// when
const { wrapper } = await renderEditor(diagramXML, { onImport });
await wrapper.update();
wrapper.setProps({ xml: diagramXML + ' ' });
await wrapper.update();
// then
expect(onImport).to.be.calledTwice;
});
```
> Remove SlotFillRoot from editors' tests

- client/src/app/App.js
- client/src/app/__tests__/AppSpec.js
This pull request disables the `save-as` toolbar button when the `EmptyTab` is active.
Closes #1282
> fix(client/App): disable save-as on empty tab

- docs/README.md
- docs/element-templates/README.md
- docs/flags/README.md
- docs/plugins/README.md
- docs/search-paths/README.md
Previously we used to state out the `search-paths` (e.g. `%AppData/camunda-modeler` for Windows) in every single part of the documentation. This led to confusion since we did always in a different form.
This pull request adds clear documentation for the `search-paths`. Furthermore, it links to it in every other place where the search paths are needed by the `{APP_HOME}` and `{USER_DATA}` identifier.
I also run the documentation through Grammarly to add some improvements in grammar and fix some typos.
Closes #1220 
Note: I was about to link the `search-paths` directly in the paths, so like
[`{APP_HOME}`](../search-paths#application-home-directory)`/resources/plugins`
But as you can see the GitHub markdown flavor always adds space after the link, which looks dirty. Therefore I just put the …
> Clarify search paths in documentation

- client/src/app/tabs/bpmn/BpmnEditor.js
- client/src/app/tabs/bpmn/__tests__/BpmnEditorSpec.js
- client/src/app/tabs/cmmn/CmmnEditor.js
- client/src/app/tabs/cmmn/__tests__/CmmnEditorSpec.js
- client/src/app/tabs/dmn/DmnEditor.js
- client/src/app/tabs/dmn/__tests__/DmnEditorSpec.js
Removes regression introduced in import refactoring.
> Import XML only when it is changed

- client/src/app/modals/deploy-diagram/View.js
Improve the user flow by automatically focusing the
deployment name. This way the user may start typing right away (and is
not forced to manually click the field).
Closes #750
> fix(deploy): auto-focus deployment name

- client/src/app/drop-zone/DropZone.js
- client/src/app/drop-zone/__tests__/DropZoneSpec.js
On my OS (Linux) files with known extensions (TXT or XML) get type set
to the actual mime-type.
This prevents dropping these files, as we previously matched for an
empty file type only (assuming that the OS does not know about BPMN,
CMMN and DMN files).
This PR improves the situation. If the OS reports a well-known type
(or a text typethat may contain a diagram), allow dragging over.
> fix(app): allow well-known files to be dropped

- client/src/app/App.js
- client/src/app/__tests__/AppSpec.js
As a follow-up from the [last week's hour of code](https://github.com/bpmn-io/hour-of-code/blob/master/snippets/App_exportAs.md) I refactored the `App.js#exportAs` method, in order to make the export retry more understandable and the whole function(s) more readable (cf. [Single responsibility principle](https://en.wikipedia.org/wiki/Single_responsibility_principle).
> chore(client/App): refactor exportAs

- client/src/app/tabs/bpmn/BpmnEditor.js
- client/src/app/tabs/bpmn/__tests__/BpmnEditorSpec.js
- client/src/app/tabs/cmmn/CmmnEditor.js
- client/src/app/tabs/cmmn/__tests__/CmmnEditorSpec.js
- client/src/app/tabs/dmn/DmnEditor.js
- client/src/app/tabs/dmn/__tests__/DmnEditorSpec.js
Closes #1298
While the past refactoring of import handling inside all editors, we removed the `xml-change-check` when the editors trigger an update. This pull request re-adds it, to ensure no old xml is imported.
> fix(client/editors): prevent import when props did not update

- client/src/app/primitives/__tests__/ToastContainerSpec.js
- client/src/app/primitives/index.js
- client/src/app/primitives/toast/ToastContainer.js
- client/src/app/primitives/toast/ToastContainer.less
- client/src/app/primitives/toast/index.js
- client/src/app/tabs/MultiSheetTab.js
- client/src/app/tabs/__tests__/MultiSheetTabSpec.js
- client/src/app/toasts/ToastConductor.js
- client/src/app/toasts/index.js
- client/src/app/toasts/warnings/WarningsToast.js
- client/src/app/toasts/warnings/WarningsToast.less
- client/src/app/toasts/warnings/__tests__/WarningsToastSpec.js
- client/src/app/toasts/warnings/index.js
Closes #1177 
This restores the alert when a diagram is opened with warnings. In comparison with the hint inside the `v.2.2.4` version, it is implemented in a per-tab manner instead inside every editor. I also decided to not restore the 'Open Log' function as it would lead to conflicts with the warning log handling inside the `AppParent`. 
It uses a similar approach as the `ModalConductor`, so it's possible to create different types of toasts in future (e.g. for short notifications, hints etc).
> Restore warnings hint

- client/src/app/KeyboardBindings.js
- client/src/app/__tests__/KeyboardBindingsSpec.js
- client/src/app/tabs/bpmn/BpmnEditor.js
- client/src/app/tabs/bpmn/__tests__/BpmnEditorSpec.js
- client/src/app/tabs/bpmn/getBpmnEditMenu.js
- client/src/app/tabs/cmmn/CmmnEditor.js
- client/src/app/tabs/cmmn/__tests__/CmmnEditorSpec.js
- client/src/app/tabs/cmmn/getCmmnEditMenu.js
- client/src/app/tabs/dmn/DmnEditor.js
- client/src/app/tabs/dmn/__tests__/DmnEditorSpec.js
- client/src/app/tabs/dmn/getDmnEditMenu.js
- client/src/app/tabs/getEditMenu.js
* handle undo/redo manually (similar to copy/cut/paste)
* update edit menu on `directEditing.activate` and `directEditing.deactivate`
* edit menu entries to trigger native undo/redo OR command stack undo/redo depending on state of editor
* added some comments
Closes #1218
> fix(client): handle undo/redo manually

- client/src/app/App.js
- client/src/app/__tests__/AppSpec.js
Follow-up of the latest hour-of-code session (cf. https://github.com/bpmn-io/hour-of-code/commit/51b4f8c50aede163527eca85dea74af763edc8f7). It refactors the `App.js#saveTab` functionality to different methods, to make it more understandable. Follows the same approach as #1297.
> chore(client/App): refactor saveTab

- app/lib/menu/menu-builder.js
- app/test/spec/menu/menu-builder-spec.js
This will allow for convenient usage of `&&` within menuItem#enabled
method, e.g. `return menuState.bpmn && menuState.inactiveInput`.
Previously, `menuState.bpmn === undefined` would make menu item enabled.
> fix(backend/menu): pass plugin menu item enabled fn to Boolean filter

- .travis.yml
Travis CI clones repository with --depth=50 which may cause it impossible to get previous tag.
I changed the config, but still want to test it locally and that's why it's WIP.
> fix(project): deep clone git repo for post distro ci stage

- client/src/app/tabs/MultiSheetTab.js
- client/src/app/tabs/__tests__/MultiSheetTabSpec.js
- client/src/app/tabs/dmn/DmnEditor.js
* fix sorting of sheets
Closes #1317
> fix(client): fix DMN navigation

- client/src/app/tabs/MultiSheetTab.js
- client/src/app/tabs/__tests__/MultiSheetTabSpec.js
Due to [this line](https://github.com/camunda/camunda-modeler/blob/master/client/src/app/tabs/MultiSheetTab.js#L370) in `MultiSheetTab` the cached `lastXML` property must be updated whenever the `xml` prop changes.
Closes #1318
> fix(client): update lastXML on xml prop change

- client/src/app/modals/deploy-diagram/View.js
- client/src/app/modals/deploy-diagram/__tests__/DeployDiagramModalSpec.js
The green/red outline and the error message will be displayed only after the user tries to deploy the diagram for the first time. Then, the validation results will be displayed immediately on change or blur.
Thus, we avoid the error message when the user just opened the modal and immediately wants to exit. Also, we don't display red error messages before the validation is actually required.
Closes #1405
> Display validation result only after first form submission

- client/src/app/tabs/bpmn/BpmnEditor.js
- client/src/app/tabs/bpmn/__tests__/BpmnEditorSpec.js
- client/src/app/tabs/bpmn/util/__tests__/configureSpec.js
- client/src/app/tabs/bpmn/util/__tests__/namespaceSpec.js
- client/src/app/tabs/bpmn/util/configure.js
Implements a generic configuration middleware as discussed in https://github.com/camunda/camunda-modeler/issues/1374.
> Configure middleware

- client/src/app/tabs/xml/getXMLEditMenu.js
This also restores the actual actions on Mac.
Closes #868
Closes #814 
Related to [SUPPORT-6136](https://app.camunda.com/jira/browse/SUPPORT-6136)
Needs manual testing. Please test on Windows if the actions still work as supposed.
> fix(client/xml-editor): restore copy, cut and paste menu entries

- client/package-lock.json
- client/package.json
Updates to current `diagram-js-minimap` version.
> chore(client): bump diagram-js-minimap version

- app/lib/index.js
- app/lib/preload.js
- client/src/remote/index.js
This ensures we follow best practices with our electron app and disable the node integration.
As a result, client plug-ins may not freely run code in the scope of the OS. This is a __potential breaking change__.
My few cents are that we should adopt this PR and see if anyone uses this hidden capability. No plug-in should have done that.
Depends on https://github.com/camunda/camunda-modeler/pull/1451 and https://github.com/camunda/camunda-modeler/pull/1452
> Disable node integration

- client/src/app/AppParent.js
- client/src/app/__tests__/AppParentSpec.js
- client/src/app/__tests__/mocks/index.js
This fixes a problem when error in the app caused an unhandled exception because of renamed `remote/Plugins` method.
Closes https://github.com/camunda/camunda-modeler/issues/1479.
> Correctly display suggestion to disable plugins

- client/src/app/App.js
- client/src/app/AppParent.js
- client/src/app/__tests__/AppParentSpec.js
Simply pass the category as a second argument to `App#handleError`
and `App#handleWarning` callbacks.
This will be useful for logging plugin errors. Might be also used for deployment errors instead of a custom logEntry.
> Allow to display custom warning/error category.

- client/src/app/App.js
- client/src/app/Toolbar.js
- client/src/app/slot-fill/Slot.js
- client/src/app/slot-fill/__tests__/SlotFillSpec.js
- client/src/app/tabs/bpmn/BpmnEditor.js
- client/src/app/tabs/dmn/DmnEditor.js
- client/src/plugins/deployment-tool/DeploymentTool.js
Fills are now ordered alphabetically by group name and take
a new property `priority` with 0 as default which is used
to determine the order within a group. The higher the priority,
the earlier the Fill is displayed.
Closes #1492
> Display fills in a stable order

- client/src/plugins/deployment-tool/CamundaAPI.js
- client/src/plugins/deployment-tool/__tests__/CamundaAPISpec.js
This PR builds on top of https://github.com/camunda/camunda-modeler/pull/1491
It adds a timeout so that the deployment tool doesn't hang in case the server does not handle the request for some reason.
> Add timeout to deployment & connection check

- client/src/plugins/deployment-tool/DeploymentTool.js
- client/src/plugins/deployment-tool/__tests__/DeploymentToolSpec.js
This PR allows to derive the deployment name from the filename. E.g. for a file called `diagram_1.bpmn` it will set the deployment name to `diagram_1`.
Requires https://github.com/camunda/camunda-modeler/pull/1491
> Derive default deployment name from the filename

- client/package-lock.json
- client/package.json
Bump to `camunda-bpm-moddle@4.2.0`
Adds support for `camunda:diagramRelationId` property.
> chore(client): bump camunda-bpm-moddle dependency

- CHANGELOG.md
This slightly changes the wording for some CHANGELOG items.
The goal is to make things clearer. Example: 
* add notifications -> we already had notifications, so what's actually new -> add reusable notification mechanism
Feel free to merge or reject, depending on whether you think the proposal is an improvement.
> chore(CHANGELOG): clarify some items

- client/src/app/modals/keyboard-shortcuts/View.js
- client/src/app/primitives/__tests__/ModalSpec.js
- client/src/app/primitives/modal/Modal.js
- client/src/plugins/deployment-tool/DeploymentDetailsModal.js
There is not much value in exposing the header, if the only thing a user
should ever customize is the title.
Related to #1558
> feat(client/modal): expose title only

- client/src/app/Log.less
- client/src/app/TabsProvider.js
- client/src/remote/Backend.js
- client/src/util/generate-id.js
This ships two improvements:
* the log controls are no more hidden once the user scrolls:
* a generic generate ID utility is provided to create IDs consistently in all places where we need them
I've addressed these things while working on https://github.com/camunda/camunda-modeler/issues/1558 but I hope to get them merged before :wink:
> Fix log error + add generate ID utility

- .travis.yml
- build/entitlements.mac.inherit.plist
- electron-builder.json
- package-lock.json
- package.json
- tasks/after-all-artifact-build.js
- tasks/after-all-artifact-build/build-mac-zip.js
- tasks/after-sign.js
- tasks/after-sign/notarize.js
Closes #1529
Closes #1572
Closes https://github.com/camunda/camunda-modeler/issues/1584
> Migrate to MacOS Catalina

- client/src/app/App.js
- client/src/app/__tests__/AppSpec.js
- client/src/plugins/deployment-tool/DeploymentTool.js
- client/src/plugins/deployment-tool/__tests__/DeploymentToolSpec.js
Instead of ignoring the <tab> param and using the <activeTab> in the <deployTab> functionality, this ensures to actually using the given tab.
Follow up of Hour of Code, cf. https://github.com/bpmn-io/hour-of-code/blob/master/snippets/DeploymentTool_deployTab.md
> chore(deploy): use given tab on <deployTab>

- client/package-lock.json
- client/package.json
- client/src/app/tabs/bpmn/modeler/BpmnModeler.js
This commit adds a bpmn-js plugin that disables modeling
actions that allowed to collapse sub process. It is done
due to lacking support for collapsed sub process with
children in other Camunda tools: Cockpit and Cawemo.
BREAKING CHANGES
* Sub Process cannot be collapsed anymore.
Closes #1486
Closes #
> Disable collapsing sub process

- client/package-lock.json
- client/package.json
This update fixes a typo in a label.
> chore(bpmn-modeler): bump disabled collapsed subprocess

- client/resources/icons/Play.svg
- client/src/plugins/camunda-plugin/CamundaPlugin.js
- client/src/plugins/camunda-plugin/deployment-tool/DeploymentTool.js
- client/src/plugins/camunda-plugin/deployment-tool/__tests__/DeploymentToolSpec.js
- client/src/plugins/camunda-plugin/shared/CamundaAPI.js
- client/src/plugins/camunda-plugin/shared/__tests__/CamundaAPISpec.js
- client/src/plugins/camunda-plugin/start-instance-tool/StartInstanceConfigModal.js
- client/src/plugins/camunda-plugin/start-instance-tool/StartInstanceConfigModal.less
- client/src/plugins/camunda-plugin/start-instance-tool/StartInstanceTool.js
- client/src/plugins/camunda-plugin/start-instance-tool/StartInstanceTool.less
- client/src/plugins/camunda-plugin/start-instance-tool/__tests__/StartInstanceConfigModalSpec.js
- client/src/plugins/camunda-plugin/start-instance-tool/__tests__/StartInstanceToolSpec.js
- client/src/plugins/camunda-plugin/start-instance-tool/__tests__/mocks/index.js
- client/src/plugins/camunda-plugin/start-instance-tool/index.js
Closes #1552 
Depends on #1616 
-----
This enables starting process instanced from the Modeler. To do that, it used a `deployService` to re-use certain methods from the `DeploymentTool`. 
* deployWithConfiguration
* getSavedDeployConfiguration
* getDeployConfigurationFromUserInput
* saveDeployConfiguration
The primary action will always be to directly start a process instance with the given configuration. It will ensure to always start the *latest available process definition*. The engine returns no `deployedProcessDefinition` if the diagram had no changes. In this case, the tool will use the latest known process definition (saved in config).
When nothing has configured so far (first-time use), it acts like a Two-Step-Modal to do following actions:
1. Get deployment config from user
2. …
> Start Instance Feature

- app/lib/config/__tests__/config-spec.js
- app/lib/config/index.js
- app/lib/config/providers/OSInfoProvider.js
- client/src/app/plugins/PluginsRoot.js
- client/src/plugins/update-checks/NewVersionInfoView.js
- client/src/plugins/update-checks/NewVersionInfoView.less
- client/src/plugins/update-checks/UpdateChecks.js
- client/src/plugins/update-checks/UpdateChecksAPI.js
- client/src/plugins/update-checks/__tests__/NewVersionInfoViewSpec.js
- client/src/plugins/update-checks/__tests__/UpdateChecksSpec.js
- client/src/plugins/update-checks/constants.js
- client/src/plugins/update-checks/index.js
- client/src/util/Flags.js
Closes #1545
To test this, pull the [Camunda Modeler Updates Server](https://github.com/camunda/camunda-modeler-update-server), start the server with **test mode**: `npm run testMode`, this would let server respond with a test response rather than an empty response.
Run camunda modeler with:
`--server-interaction --updates-server-url=http://localhost:8050`
**Tip**
While testing it makes sense to comment out [this line](https://github.com/camunda/camunda-modeler/blob/3b9eecfa3d269b1beeab9bc0b6071f9f1150ac66/client/src/plugins/update-checks/UpdateChecks.js#L63) as we don't want to wait for another day to make the popup visible again :)
In the testMode, the Modeler should show something like this:
**Go to download page** button should go to camunda.com
> Update checks plugin

- app/lib/index.js
- docs/flags/README.md
- docs/search-paths/README.md
Adds options to set user path via '--user-path' flag
Example: ./'Camunda Modeler' --user-path="/Users/foo/camunda-modeler"
Closes #1625
> feat(app): set user path via flag

- app/util/get-version.js
- tasks/distro.js
Closes #1628
Once this PR gets merged, the updates server will be able to compare the recency of nightly builds.
> Assign timestamp to nightly build versions

- app/lib/menu/menu-builder.js
- client/src/plugins/privacy-preferences/PrivacyPreferences.js
- client/src/plugins/privacy-preferences/__tests__/PrivacyPreferencesSpec.js
- client/src/plugins/update-checks/UpdateChecks.js
- client/src/plugins/update-checks/UpdateChecksAPI.js
- client/src/plugins/update-checks/__tests__/UpdateChecksSpec.js
- client/src/util/Flags.js
Closes #1641
This PR enables privacy preferences and update checks by default. Also introduces --disable-server-interaction flag to disable privacy preference settings and update checks features (which is of course false by default).
> Enable privacy preferences and update checks by default

- client/src/plugins/privacy-preferences/PrivacyPreferencesView.js
- client/src/plugins/privacy-preferences/__tests__/PrivacyPreferencesSpec.js
- client/src/plugins/privacy-preferences/__tests__/PrivacyPreferencesViewSpec.js
- client/src/plugins/update-checks/NewVersionInfoView.js
- client/src/plugins/update-checks/__tests__/NewVersionInfoViewSpec.js
This PR integrates primary and secondary button classes into privacy-settings and updates-check modals so that once we implement these css classes, these modals would be aligned with deployment related modals.
> Integrate primary/secondary buttons to privacy-settings and updates-check modals

- app/lib/dialog.js
- app/package-lock.json
- app/test/helper/mock/electron-dialog.js
- app/test/spec/dialog-spec.js
- client/src/app/tabs/xml/XMLEditor.less
- package-lock.json
- package.json
> Update to Electron 7

- app/lib/__tests__/flags-spec.js
- app/lib/flags.js
- client/src/plugins/update-checks/UpdateChecks.js
- client/src/plugins/update-checks/UpdateChecksAPI.js
- client/src/util/Flags.js
- client/src/util/__tests__/FlagsSpec.js
- client/webpack.config.js
- package.json
This PR addresses these issues to make things easier for us developers to play with Updates Check features:
1)  Introduce `updates-server-url` flag
3) Introduce `force-update-checks` flag to disable wait-for-another-day rule for update checks. Using this flag, update checks requests are sent anytime the editor is refreshed. This flag is enabled by default for dev builds and is not documented as it is not intended for production usage.
> Update checks dev improvements

- client/public/style.css
- client/src/app/EmptyTab.js
- client/src/app/EmptyTab.less
- client/src/app/modals/keyboard-shortcuts/View.js
- client/src/app/modals/keyboard-shortcuts/View.less
- client/src/plugins/camunda-plugin/deployment-tool/DeploymentConfigModal.js
- client/src/plugins/camunda-plugin/deployment-tool/DeploymentConfigModal.less
- client/src/plugins/camunda-plugin/start-instance-tool/StartInstanceConfigModal.js
- client/src/plugins/camunda-plugin/start-instance-tool/StartInstanceConfigModal.less
- client/src/plugins/privacy-preferences/PrivacyPreferencesView.js
- client/src/plugins/privacy-preferences/PrivacyPreferencesView.less
- client/src/plugins/privacy-preferences/__tests__/PrivacyPreferencesSpec.js
- client/src/plugins/privacy-preferences/__tests__/PrivacyPreferencesViewSpec.js
- client/src/plugins/update-checks/NewVersionInfoView.js
- client/src/plugins/update-checks/__tests__/NewVersionInfoViewSpec.js
I renamed the modal-buttons branch to unified-buttons, as it is more correct.
**Empty page:**
**Privacy prefs:**
**Deploy diagram:**
**Start process instance [Step 1]:**
**Start process instance [Step2]:**
**Update checks modal:**
> Unified buttons

- client/src/app/tabs/bpmn/__tests__/BpmnEditorSpec.js
We have `helpers` comment a few lines above ...
> chore(client/bpmn): remove unnecessary comment

- client/src/app/tabs/dmn/DmnEditor.js
- client/src/app/tabs/dmn/__tests__/DmnEditorSpec.js
- client/src/app/tabs/dmn/util/__tests__/configureSpec.js
- client/src/app/tabs/dmn/util/configure.js
Closes #1550 
Introduces endpoints to integrate plugins into the DMN Editor
* `dmn.modeler.moddleExtensions`
* `dmn.modeler.drd.additionalModules`
* `dmn.modeler.decisionTable.additionalModules`
* `dmn.modeler.literalExpression.additionalModules` 
* `dmn.modeler.configure` (React Client Extension)
* `dmn.modeler.created` (React Client Extension)
Depends on https://github.com/camunda/camunda-modeler-plugin-helpers/pull/7 (has to be integrated first)
**Aditional Context** 
[Simple Examples](https://github.com/camunda/camunda-modeler/tree/dmn-plugins-examples) (just showcases, not intended to be merged)
> DMN Editor plugins

- electron-builder.json
While working on Zeebe Modeler we realized that building some native modules in Electron such as gRPC does not work on Linux 32bit platforms. It turns out that Electron has dropped support for such devices some time ago:
https://www.electronjs.org/blog/linux-32bit-support
It makes sense for us to remove this platform from our build pipeline as well.
> Do not build for linux 32bit platforms

- package-lock.json
- package.json
- tasks/test-distro.js
While working on deployment feature in Zeebe modeler, after adding gRPC modules we realized that Appveyor is not capable of successfully running distro tests as the library we use for decompressing zip/tar.gz files allocate a single buffer once for whole file instead of using streams which causes `Array buffer allocation failed` exceptions.
This PR optimizes the distro tests by using streams for reading compressed data and also not writing the decompressed data to file system.
> Optimize distro tests

- app/lib/dialog.js
- client/src/app/App.js
- client/src/app/__tests__/AppSpec.js
A few issues fixed:
* We append the default file extension
* We do not fail if the dialog accidentally returns a file without recognizable extension
* We do not shadow export errors but print them to the console at least
Closes #1699 
---
Please double check if that does not break anything on MacOS (as I believe we removed the extension deliberately during `Save As...` at some point).
> Mitigate file Save As issue

- client/src/plugins/update-checks/UpdateChecks.js
- client/src/plugins/update-checks/__tests__/UpdateChecksSpec.js
This ensures we trigger the update check daily, even if the app remains open for longer than 24 hours.
Closes https://github.com/camunda/camunda-modeler/issues/1718
> Periodic update checks

- client/src/app/App.js
- client/src/app/Log.js
- client/src/app/__tests__/LogSpec.js
Closes #1380 
Enables <CMD+C> copy keyboard shortcut also on mac devices inside the Log panel.
> feat(client/Log): apply native keyboard shortcuts

- client/src/plugins/camunda-plugin/shared/components/Radio.js
Before this change, id could take value of "HTTP Basic", which is invalid in HTML5 because of the whitespace.
Cf. https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/id
> chore(client/radio): make sure to use valid id for inputs

- client/src/styles/_base.less
- resources/plugins/test/style.css
Closes #1731
With this commit we remove the logo in BPMN, DMN, CMMN editors (bottom-right corner):
Also we're getting rid of this logo in DRD view (top-right):
We're keeping the DEV indicator as it helps us distinguishing the prod from dev:
> Remove watermark in prod

- docs/.project/ALPHA_RELEASE.md
To make sure we don't include unnecessary steps in the alpha release process.
> chore(project): add alpha release documentation

- client/src/plugins/error-tracking/ErrorTracking.js
- client/src/plugins/error-tracking/__tests__/ErrorTrackingSpec.js
- client/src/plugins/privacy-preferences/PrivacyPreferences.js
- client/src/plugins/privacy-preferences/__tests__/PrivacyPreferencesSpec.js
An example of how we could subscribe to privacy preferences changes. Thus, we are able to enable/disable crash reports as soon as user enables/disables them.
This might also be helpful for future analytics module.
> Pub sub for privacy preferences in error tracking

- .travis.yml
Related to the duplicated release for Camunda Modeler v4.0.0-alpha.3
This prevents racing condition.
> chore(ci): make sure to create a GitHub release beforehand

- docs/.project/RELEASE.md
An attempt at making the timeline of a release more clear to the release manager.
> chore(docs): improve release issue template

- .travis.yml
Proof that job fails when tests fail (no codecov): https://travis-ci.org/github/camunda/camunda-modeler/jobs/694307743
Proof that it uploads codecov on build success: https://travis-ci.org/github/camunda/camunda-modeler/jobs/694309470#L2069
Closes #1820
> fix(ci): run codecov after success

- client/package-lock.json
- client/package.json
- client/src/app/tabs/bpmn/BpmnEditor.js
- client/src/plugins/camunda-plugin/start-instance-tool/util/isExecutable.js
- client/test/mocks/bpmn-js/Modeler.js
- resources/plugins/test/style.css
With this PR we correctly use the awaitable bpmn-js APIs to get rid of callback deprecation warning logs.
---
Closes https://github.com/camunda/camunda-modeler/issues/1775
> Bump to bpmn-js@7.0.1

- resources/plugins/test/style.css
Fixes this thing in dev builds (`npm run dev`):
We don't have this problem in normal builds.
> Hide old watermark in DMN (dev builds)

- client/src/plugins/error-tracking/__tests__/ErrorTrackingSpec.js
- client/src/plugins/usage-statistics/__tests__/UsageStatisticsSpec.js
In this PR, we get rid of Enzyme in ErrorTracking tests since this plugin does not render anything.
We did the same in [UsageStatistics](https://github.com/camunda/camunda-modeler/commit/87f6e8bf8783ec7ef18782b206f505180013ef52) plugin.
> Don't use Enzyme in ErrorTracking tests

- app/lib/util/__tests__/error-tracking-spec.js
- app/lib/util/error-tracking.js
- client/src/plugins/error-tracking/ErrorTracking.js
- client/src/plugins/error-tracking/__tests__/ErrorTrackingSpec.js
Closes #1831
**Best way to test this works**
Since we don't have this problem for dev builds, we need to create a buggy artifact to test this. Follow these steps:
1. Inject `SENTRY_DSN`, `SENTRY_AUTH_TOKEN`, `SENTRY_ORG` and `SENTRY_PROJECT` environment variables. They should be accessible from `client/webpack.config.js` These values can be found on our Sentry page. Ping @oguzeroglu if you don't know how to get those.
2. We don't want to pollute existing sourcemaps, so we need to change [this line](https://github.com/camunda/camunda-modeler/blob/c002e72af5c0147444af28edd1787e14def83fb8/client/webpack.config.js#L141) to `release: 'testRelease'`. For the same reason, change [this line](https://github.com/camunda/camunda-modeler/blob/c002e72af5c0147444af2 …
> Normalize Sentry events

- client/webpack.config.js
Closes #1849
This is an easy fix. You can see it works [here](https://sentry.io/organizations/camunda-modeling/releases/spec-fix-test-release/artifacts/?project=5223041) as this test artifact does not contain any spec file, as opposed to [here](https://sentry.io/organizations/camunda-modeling/releases/4.0.0/artifacts/?project=5223041).
> Do not upload Spec files to Sentry

- .codecov.yml
It's unnecessary after we dropped Appveyor: 8f24e98aba2e88148fd40e5bc459eb81627408fd
> chore(codecov): remove appveyor configuration

- client/src/app/tabs/cmmn/CmmnEditor.js
- client/src/app/tabs/cmmn/__tests__/CmmnEditorSpec.js
- client/src/plugins/usage-statistics/event-handlers/DiagramOpenEventHandler.js
- client/src/plugins/usage-statistics/event-handlers/__tests__/DiagramOpenEventHandlerSpec.js
- docs/telemetry/README.md
> Track cmmn diagrams

- .travis.yml
Test stage should run for all build which are not triggered via API and for API-triggered builds where SKIP_TESTS is not set to `true`.
This was broken via https://github.com/camunda/camunda-modeler/commit/c0d933c2b228771e2dd1a9865b4f0781bb3f85c9 🙈 
> fix(ci): rewrite test stage condition

- client/src/app/tabs/dmn/DmnEditor.less
This fixes class name clashes as both .top and .bottom classes
are used in dmn-js.
Related to #1898
> Fix dmn modeler dragging layout

- app/lib/config/index.js
- app/lib/config/providers/ElementTemplatesProvider.js
- client/src/app/tabs/bpmn/BpmnEditor.js
- client/src/app/tabs/bpmn/__tests__/BpmnEditorSpec.js
- client/test/mocks/bpmn-js/Modeler.js
Adds two things that are necessary for the new cloud connect plugin to work:
* load element templates from default config file
* action that triggers BPMN editor to reload element templates and update properties panel
Related to https://github.com/bpmn-io/internal-docs/issues/121
> Cloud connect plugin compatibility

- CHANGELOG.md
- client/src/app/tabs/dmn/getDmnEditMenu.js
closes #1843
__Additional context__
Discovered during analysis of this PR and probably caused in same module: #1912
> fix(dmn-edit-menu): handle undo and redo entries without default

- app/lib/file-system.js
- app/test/spec/file-system-spec.js
This adds an ability to get the file contents as buffer, and then operate with it freely.
During the Camunda Summer Hackdays (cf. https://github.com/pinussilvestrus/excel-to-dmn-plugin), I found it helpful if plugins could get file contents as a buffer, and no encoding has to be given. 
Currently, every time when reading a file, you get the encoded file contents, even you did not specify it. Sometimes file contents might be encoded in a format, which [Node.js does not support](https://stackoverflow.com/a/14551669), e.g. when working with Excel files.
_None_. Just a suggestion for better file reading support for plugins.
> feat(app): allow reading file as buffer

- client/src/app/primitives/__tests__/ModalSpec.js
- client/src/app/primitives/modal/Modal.js
- client/src/plugins/element-templates-modal/components/ElementTemplatesModalView.js
- client/src/plugins/element-templates-modal/components/ElementTemplatesModalView.less
- client/src/plugins/element-templates-modal/components/Input.less
- client/src/plugins/element-templates-modal/components/__tests__/ElementTemplatesViewSpec.js
Follow-up to https://github.com/camunda/camunda-modeler/pull/1910. Fixes remaining issues.
* fix input styles
* sort element templates alphabetically
* display date correctly
* make header sticky
* disable apply button if selected element template does not match filter
* filter once per filter change
* do not select on description expand
> Element Template Modal UX Fixes

- client/src/app/tabs/dmn/diagram.dmn
Closes #1912
**Solution explained:**
When we create the Input Expression in the correct position inside the default diagram considering the grid snapping, [align-to-origin module won't adjust its position for the first time](https://github.com/bpmn-io/align-to-origin/blob/34931362346878ea9eec9b248b646c6ba714adf2/lib/align-to-origin.js#L68) therefore polluting the command stack and causing this undo&redo bug. So this is the easiest fix.
> chore(dmn): adjust the initial position of default dmn diagram

- client/src/app/tabs/dmn/DmnEditor.js
- client/src/app/tabs/dmn/__tests__/DmnEditorSpec.js
Closes #1923
Default undo/redo breaks the decision table undo/redo functionalities. This PR fixes it. See the GIF:
> Do not use default undo/redo for decision tables

- client/src/plugins/element-templates-modal/components/ElementTemplatesModalView.js
- client/src/plugins/element-templates-modal/components/__tests__/ElementTemplatesViewSpec.js
- client/src/plugins/element-templates-modal/modeler/EditorActions.js
- client/src/plugins/element-templates-modal/modeler/__tests__/bpmn-io-modelers/EditorActionsSpec.js
Match element types using `isAny` utility.
Closes #1947
> fix(element-template-modal): properly match element types

- client/src/plugins/camunda-plugin/start-instance-tool/StartInstanceTool.js
#1777: changed condition for displaying message config should be true
Closes #1777
The modal message on the dialog should be "Start Process Instance Step 2 of 2"
Modal should show this heading on the second step "Start Process Instance Step 2 of 2".
> Start Process Instance Modal does not have correct label

- client/src/app/AppParent.js
- client/src/app/KeyboardBindings.js
- client/src/app/__tests__/KeyboardBindingsSpec.js
> * Make the most standard shortcut (i.e. Backspace on MacOS and DELETE on other systems) the menu shortcut
> * Make the other shortcut available via the browser view (listen to it and react accordingly)
Closes #1989 
> Backspace element removal

- docs/element-templates/README.md
We should not permit the `Text` type for `property` bindings since
* it's reasonable for properties like `name` or `documentation`
* we have exactly this case [inside our samples](https://github.com/camunda/camunda-modeler/blob/develop/resources/element-templates/samples.json#L190)
When we start validating these combinations (https://github.com/bpmn-io/element-templates-json-schema/issues/9), we should ensure valid combinations are not permitted. 
I double-checked all other cases and this one seems to be the only missing one.
> docs(element-templates): update supported types for <property> binding

- client/src/app/plugins/PluginsRoot.js
- client/src/app/plugins/__tests__/PluginsRootSpec.js
- client/src/plugins/element-templates-modal/components/ElementTemplatesModalView.js
- client/src/plugins/element-templates-modal/components/__tests__/ElementTemplatesModalViewSpec.js
Closes https://github.com/camunda/camunda-modeler/issues/2012
> fix(element-templates-modal): get local and global element templates

- .travis.yml
Adds `git` paths to PATH. Note that on Travis CI we need to use
`export` instead of `set` for environment variables on Windows.
Closes bpmn-io/build-on-demand#4
> fix(ci): correct Windows config for build-on-demand

- client/.babelrc
This is the Chrome version shipped with Electron@7.
> chore: update preset-env target to Chrome@78

- package-lock.json
- package.json
This updates the Camunda Modeler to the latest Electron@7 release.
Knowing that we'll not tackle the bigger update soon, I guess it still makes sense to at least keep up with the `@7` series.
Tried it and seems to work (on my machine). Best time to update now, too, as we just released.
> deps: update to Electron@7.3.3

- app/lib/menu/mac-os/mac-menu-builder.js
> feat(menu): open fullscreen with Ctrl+Cmd+F on Mac

- .github/workflows/CI.yml
Allows us to get early, quick feedback on our CI status.
> chore: add basic GitHub CI action

- app/lib/menu/mac-os/mac-menu-builder.js
- app/lib/menu/menu-builder.js
- client/src/plugins/privacy-preferences/PrivacyPreferences.js
- client/src/plugins/privacy-preferences/PrivacyPreferencesView.js
- client/src/plugins/privacy-preferences/__tests__/PrivacyPreferencesSpec.js
- client/src/plugins/privacy-preferences/__tests__/PrivacyPreferencesViewSpec.js
- client/src/plugins/update-checks/NewVersionInfoView.js
- client/src/plugins/update-checks/PrivacyPreferencesLink.js
- client/src/plugins/update-checks/UpdateChecks.js
- client/src/plugins/update-checks/__tests__/PrivacyPreferencesLinkSpec.js
- client/src/plugins/update-checks/__tests__/UpdateChecksSpec.js
Accessible via
```sh
npx @bpmn-io/sr camunda/camunda-modeler#2010-updates-check-menu-item
```
_______
* Add "Check for Updates" menu item under
* "Help" (Linux/ Windows)
* App Menu (macOS)
* Make it possible to trigger update checks manually (unscheduled)
* Make it possible to display a notification when no updates available
* Reference Privacy Preferences Modal if update checks are disabled
Closes #2010 
> Updates Check Menu Action

- client/src/plugins/camunda-plugin/deployment-tool/DeploymentTool.js
- client/src/plugins/camunda-plugin/deployment-tool/__tests__/DeploymentToolSpec.js
Re-throw non DeploymentErrors during deployment
related to #2078 
> Re-throw non deploymentErrors during deployment

- client/src/plugins/camunda-plugin/start-instance-tool/StartInstanceTool.js
- client/src/plugins/camunda-plugin/start-instance-tool/__tests__/StartInstanceToolSpec.js
> fix(start-instance-tool): re-throw errors when unknown

- client/src/plugins/usage-statistics/event-handlers/__tests__/DeploymentEventHandlerSpec.js
- client/src/plugins/usage-statistics/event-handlers/__tests__/DiagramOpenEventHandlerSpec.js
- client/src/util/metrics/userTasks.js
Bug was directly reported by @volkergersabeck based on data from the nightly modeler build
Closes #2062 
> fix(telemetry): use 'generated' keyword for formkey usertask tracking

- package-lock.json
- package.json
This fixes the devtools extension after a breaking
change in Chrome Web Store API.
Related to https://github.com/MarshallOfSound/electron-devtools-installer/issues/157#issuecomment-704792363
Fixes a problem noticable when you run `npm start`.
> fix: repair React devtools extension in dev mode

- README.md
Aligns with our move to phase out CMMN support.
CMMN editing support is still there, it is simply not presented prominently anymore.
> docs(README): remove mention of CMMN

- client/src/plugins/camunda-plugin/deployment-tool/DeploymentTool.js
- client/src/plugins/camunda-plugin/deployment-tool/__tests__/DeploymentToolSpec.js
As preparation for the Unified Modeler, we should display the Deployment Tool only on Camunda tabs.
Related to #2029 
> feat(camunda-plugin): display Deployment Tool on Camunda tabs only

- app/package-lock.json
- app/package.json
This is done due to unexpected breaking change in zeebe-node@0.23.3.
As we don't want to depend on the native implementation of grpc,
the package version needs to be pinned.
> chore: pin zeebe-node to 0.23.2

- client/src/plugins/usage-statistics/UsageStatistics.js
- client/src/plugins/usage-statistics/__tests__/UsageStatisticsSpec.js
This makes sure we do not send events with missing installation to E.T., to not rubbish our usage statistics data.
It also fixes the root cause of the missing installation id:
* start plugin with disabled configuration
* enable on runtime
* editor id is missing due to missing early configuration
Closes #1965
Closes #2076
> fix(usage-statistics): ensure editor id

- app/package-lock.json
- app/package.json
- build/entitlements.mac.inherit.plist
- package.json
Thanks to `electron-builder install-app-deps` command, we don't need to rebuild the application native dependencies from the source on each `npm install / npm ci`. Instead, `electron-builder` downloads the pre-built binary for our Electron version. 
Closes #2114
> chore: update to zeebe-node@0.26.0

- docs/flags/README.md
We somehow missed this flag in the documentation.
> docs(flags): add `disable-remote-interaction`

- client/package-lock.json
- client/package.json
- client/src/app/tabs/cloud-bpmn/modeler/BpmnModeler.js
- client/src/util/Flags.js
- docs/flags/README.md
* Disables Zeebe User Tasks support per default
* Adds a flag `enable-zeebe-user-tasks` so that we can enable it until it got properly released in May.
```json
// flags.json
{
"enable-zeebe-user-tasks": true
}
```
Closes #2140
> chore(cloud-bpmn): add flag to enable zeebe user tasks

- client/src/app/TabsProvider.js
- client/src/app/__tests__/TabsProviderSpec.cloud.bpmn
- client/src/app/__tests__/TabsProviderSpec.js
Take `cloud-bpmn` first, `bpmn` as fallback
Closes #2130
> fix(tabs-provider): change order of bpmn providers

- client/src/index.js
- client/src/remote/__tests__/RemoteSpec.js
- client/src/remote/index.js
This prevents using `window.getAppPreload` by other code than
the application. Thus, only the application has access to
the IPCRenderer and can decide which APIs it provides.
Closes #2143.
Related to https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2021-28154
> fix(remote): remove `getAppPreload` once loaded

- client/src/plugins/zeebe-plugin/deployment-plugin/DeploymentPluginConstants.js
- client/src/styles/_forms.less
Closes #2141
Note: I had to adjust the column space to properly align the longer labels. This also touches the other part where we use those radio buttons (Camunda Platform Auth Configuration)
I think that's okayish, I wouldn't add extra effort to make this dynamic.
> chore(zeebe-plugin): update deployment target labels

- client/src/app/EmptyTab.js
- client/src/app/TabsProvider.js
- client/src/app/__tests__/EmptyTabSpec.js
- client/src/app/__tests__/TabsProviderSpec.js
- client/src/util/Flags.js
This PR demonstrates how to disable our new Zeebe features temporarily using a feature toggle.
If merged, only once given `--no-disable-zeebe` Zeebe features are actually activated.
> feat: disable zeebe without feature toggle

- client/public/index.html
- client/src/app/tabs/form/FormTab.js
- client/src/index.js
Inline scripts are not executed in production mode for security reasons. Moved the fix to the bundle.
> Fix Form Editor

- client/src/app/App.js
- client/src/app/__tests__/AppSpec.js
This fixes the grammar of the Unsupported file message if only one file type is enabled.
closes #2028
> fix(client): fix file error message

- electron-builder.json
Dangling comma is not allowed in JSON.
> Fix typo in electron-builder.json

- app/package-lock.json
- app/package.json
Due to changes in Zeebe latest alpha, `zeebe-node` dependency needs to be updated.
Supports Zeebe@1.0.0-alpha.7.
> deps: update to zeebe-node@1.0.0-alpha.7

- app/lib/index.js
Sets minimum window size to 640x480.
Can be tested with artifacts:
- https://camunda-modeler-on-demand.s3.eu-central-1.amazonaws.com/minimum-size/camunda-modeler-minimum-size-linux-x64.tar.gz
- https://camunda-modeler-on-demand.s3.eu-central-1.amazonaws.com/minimum-size/camunda-modeler-minimum-size-mac.dmg
- https://camunda-modeler-on-demand.s3.eu-central-1.amazonaws.com/minimum-size/camunda-modeler-minimum-size-mac.zip
- https://camunda-modeler-on-demand.s3.eu-central-1.amazonaws.com/minimum-size/camunda-modeler-minimum-size-win-ia32.zip
- https://camunda-modeler-on-demand.s3.eu-central-1.amazonaws.com/minimum-size/camunda-modeler-minimum-size-win-x64.zip
---
Related to SUPPORT-10593
> fix: set minimum window size

- package.json
This way we can avoid publishing `camunda-modeler-builder` by accident. This has happened at least once.
> chore: mark root package as private

- app/lib/index.js
Before this PR, the Flags object was passed to the preload script. Then, it was serialized to `{ flags: ... }` but we expect the flag names to be the keys of the object.
So instead of:
```json
{
"disable-remote-interaction": true
}
```
we got:
```json
{
"flags": {
"disable-remote-interaction": true
}
}
```
> pass flags correctly

- app/package-lock.json
- app/package.json
- client/package-lock.json
- client/package.json
Updates `@sentry` dependencies from v5 to v6. According to the release notes, there are no breaking changes: https://github.com/getsentry/sentry-javascript/releases/tag/6.0.0
> deps: update @sentry/browser and @sentry/node dependencies

- tasks/distro.js
This makes sure that we don't need to include too broad permissions for the nightly AWS credentials. Without specifying region, it needs to be able to list buckets.
> ci: use AWS_REGION for nightly build

- client/src/remote/Plugins.js
- client/webpack.config.js
This ensures plug-ins can rely on their styles being loaded before they are executed.
For context, cf. https://github.com/bpmn-io/bpmn-js-token-simulation-plugin/pull/32#issuecomment-845075888.
> Await styles

- app/lib/__tests__/cli-spec.js
- app/lib/cli.js
I've decided to simply ignore any known Chromium switches since reordering the list of arguments is error-prone. For now, the only known Chromium switch is `--allow-file-access-from-files`. My assumption is that it's unlikely that the list of arguments will change that often and if it does we will find out if the flags feature is broken during our integration tests.
Closes #2268
> fix(app): ignore Chromium switches when parsing CLI arguments

- client/src/app/App.js
- client/src/app/tabs/MultiSheetTab.js
- client/src/app/tabs/bpmn/BpmnEditor.js
- client/src/app/tabs/bpmn/__tests__/BpmnEditorSpec.js
Closes #2287
This PR handles element [template validation errors](https://github.com/bpmn-io/bpmn-js-properties-panel/blob/master/lib/provider/camunda/element-templates/ElementTemplatesLoader.js#L82) as warnings - and avoids showing the stacktrace for these since it will be the same for each validation warning (no real benefit). I also think it's okay to assume these errors are only validation errors since we handle [template loading errors](https://github.com/camunda/camunda-modeler/blob/develop/client/src/app/tabs/bpmn/BpmnEditor.js#L142) separately. 
This also prevents sending the validation errors to Sentry.
**before**
**after**
> Handle template errors as warnings

- client/src/app/TabsProvider.js
Closes #2312
* Ambiguity results from the fact that we now support CamundaCloud and
CamundaPlatform
* However, the feature to have a shortcut creation of a new tab, shall
be re-added soon. Also see #2309
> chore(TabsProvider): remove ambigious CTRL+T hotkey

- client/src/plugins/usage-statistics/event-handlers/BaseEventHandler.js
- client/src/plugins/usage-statistics/event-handlers/PingEventHandler.js
- client/src/plugins/usage-statistics/event-handlers/VersionInfoLinkOpenedEventHandler.js
- client/src/plugins/usage-statistics/event-handlers/VersionInfoOpenedEventHandler.js
- client/src/plugins/usage-statistics/event-handlers/__tests__/BaseEventHandlerSpec.js
- client/src/plugins/usage-statistics/event-handlers/__tests__/VersionInfoLinkOpenedEventHandlerSpec.js
- client/src/plugins/usage-statistics/event-handlers/__tests__/VersionInfoOpenedEventHandlerSpec.js
- client/src/plugins/usage-statistics/event-handlers/index.js
- client/src/plugins/version-info/VersionInfo.js
- client/src/plugins/version-info/VersionInfoOverlay.js
- client/src/plugins/version-info/__tests__/VersionInfoSpec.js
- client/src/shared/ui/__tests__/OverlaySpec.js
- client/src/shared/ui/overlay/Overlay.js
- docs/telemetry/README.md
This allows us to track whether users open the version info and which links they are interested in.
Closes #2303
---
To test this in action, I used the following setup:
In a terminal tab run:
```sh
npx http-echo-server 3000
```
In parallel, in Camunda Modeler repo root directory you can run then:
```sh
ET_ENDPOINT=http://localhost:3000 npm start
```
> Add usage tracking for Version Info

- .github/workflows/NIGHTLY.yml
This adds a Slack notification when we detect nightly build failure. The notification includes the link to the failed build. Tested in action: https://github.com/camunda/camunda-modeler/actions/runs/985796985
Closes #2336
> ci: send Slack notification if nightly build fails

- app/package-lock.json
- app/package.json
This updates the `zeebe-node` dependency to v1.4.0 which supports Zeebe 1.1.0.
Closes #2319
---
Tests status:
I've talked to @menski and he shared that there are some infrastructure changes ongoing. Once they're finished, the client should work with Zeebe 1.0.x clusters on Camunda Cloud. Nevertheless, we should not need to do any changes on our side.
> Support Zeebe 1.1.0

- client/src/app/tabs/dmn/modeler/DmnModeler.js
This was missing with https://github.com/camunda/camunda-modeler/pull/2348, as I did not have the overview open while testing.
---
Notice that there exists no automated tests for the feature. I did not add any, too, due to time constraints.
> chore(client): migrate DMN overview feature to dmn-js@11

- client/src/styles/_base.less
When setting the OS color scheme to dark and opening the developer tools the app background is the color of the dark color scheme:
Making the white app background explicit fixes the issue:
> style(client): make white app background explicit

- .github/workflows/RELEASE.yml
This should fix the problem revealed in https://github.com/camunda/camunda-modeler/runs/2999852513?check_suite_focus=true#step:9:32
> ci: fetch full git history in release job

- resources/element-templates/samples.json
`expression` was set to `"true"` instead of `true` resulting in an error logged everytime you'd open a BPMN tab in development mode.
> fix(element-templates): fix example

- resources/element-templates/samples.json
* the camunda:in and camunda:out samples were referencing the same
source/target variables. This would not make sense from a business
perspective, it would also lead to strange behavior in the UX, since one
input in the propertiesPanel would change the value of other inputs.
> Make element template samples more meaningful

- client/src/app/tabs/cloud-bpmn/diagram.bpmn
* With Camunda Modeler 4.9 we support cloud 1.1 (incl. new element types)
> chore: set executionPlatformVersion to 1.1.0 for new cloud tab

- client/package-lock.json
- client/package.json
- client/src/app/tabs/PropertiesContainer.less
- client/src/app/tabs/bpmn/modeler/features/properties-panel-keyboard-bindings/PropertiesPanelKeyoardBindings.js
- client/src/app/tabs/cloud-bpmn/modeler/BpmnModeler.js
Replaces old with new properties panel in Cloud Bpmn Editor
Related to bpmn-io/properties-panel#5
Closes #2347
Depends on https://github.com/bpmn-io/bpmn-properties-panel/pull/14
> feat(cloud-bpmn): integrate `@bpmn-io/bpmn-properties-panel`

- client/src/app/tabs/bpmn/BpmnEditor.js
- client/src/app/tabs/bpmn/__tests__/BpmnEditorSpec.js
- client/src/app/tabs/cloud-bpmn/BpmnEditor.js
- client/src/app/tabs/cloud-bpmn/__tests__/BpmnEditorSpec.js
- client/src/app/tabs/dmn/DmnEditor.js
- client/src/app/tabs/dmn/__tests__/DmnEditorSpec.js
As discussed in the hour of code (cf. https://github.com/bpmn-io/hour-of-code/blob/master/snippets/CamundaModelerAsyncTest.md) a bunch of tests weren't actually testing anything.
* fix and refactor BPMN, Cloud BPMN and DMN tests
* handle export SVG errors
> Fix and Refactor Async Tests

- client/package-lock.json
- client/package.json
- client/src/app/tabs/form/FormEditor.js
- client/src/app/tabs/form/FormEditor.less
- client/src/app/tabs/form/__tests__/FormEditorSpec.js
- client/src/app/tabs/form/editor/FormEditor.js
- client/src/app/tabs/form/getFormEditMenu.js
- client/test/mocks/bpmn-js/Modeler.js
- client/test/mocks/form-js/index.js
- package-lock.json
- package.json
Integrates form-js v0.3.0 into the Camunda Modeler.
* form editor instances are reused
* import is asynchronous
* undo and redo is supported
* ensure async tests are working (cf. https://github.com/bpmn-io/hour-of-code/blob/master/snippets/CamundaModelerAsyncTest.md)
> Integrate form-js v0.3.0

- client/src/app/App.js
- client/src/app/__tests__/AppSpec.js
> fix: keep tab open when save dialog is canceled

- app/lib/zeebe-api.js
- client/src/plugins/zeebe-plugin/deployment-plugin/DeploymentPlugin.js
- client/src/plugins/zeebe-plugin/deployment-plugin/DeploymentPluginConstants.js
- client/src/plugins/zeebe-plugin/deployment-plugin/DeploymentPluginModal.js
- client/src/plugins/zeebe-plugin/deployment-plugin/DeploymentPluginValidator.js
- client/src/plugins/zeebe-plugin/deployment-plugin/__tests__/DeploymentPluginModalSpec.js
- client/src/plugins/zeebe-plugin/deployment-plugin/__tests__/DeploymentPluginSpec.js
- client/src/plugins/zeebe-plugin/deployment-plugin/__tests__/DeploymentPluginValidatorSpec.js
- client/src/remote/ZeebeAPI.js
closes #2375 
Note that:
* In the Modal, we want to have the clusterURL as input (since it is
inline with the Camunda Cloud Config modal and it only requires the
user to copy/paste one value)
* However, with version 1.4.0 zeebe-node does not take an entire URL
anymore. It requires to be passed clusterId and clusterRegion
seperately. (see
https://github.com/camunda-community-hub/zeebe-client-node-js/blob/master/CHANGELOG.md)
* Therefore, we extract that info from the URL before
passing it to zeebe-node.
I manually tested that this works with `bru-2` and `chs-1` clusters.
> 2375 support cluster url

- client/src/app/tabs/dmn/DmnEditor.js
- client/src/app/tabs/dmn/__tests__/DmnEditorSpec.js
Root cause: The literalExpressions editor does not fire events when elements are selected, so `inputActive` is not set correctly.
As introducing these events would be a bigger refactoring and the action should never be performed without `role: delete`, I decided to fix it in the modeler by setting `inputActive` to true. 
closes #2095
> fix(dmn): enable backspace in literalExpressions editor

- client/src/app/tabs/form/__tests__/FormEditorSpec.js
* Tests for linting in the Form Editor check for any event being dispatched.
* If dispatches of other events that are not relevant to this test case are added, it will cause these tests to fail. 
* Tests assertions were modified to only consider events of type `lint-tab`
> fix: linting tests on Form Editor

- .github/dependabot.yml
* configure our prefix
* make dependabot recognize our monorepository structure
---
See [dependabot general configuration hints](https://help.github.com/github/administering-a-repository/configuration-options-for-dependency-updates).
> chore: add dependabot configuration file

- client/package-lock.json
- client/package.json
Closes #2423 and related to #2420
> Bump camunda-bpmn-js from 0.9.3 to 0.10.0

- client/package-lock.json
- client/package.json
- client/src/app/Log.less
- client/src/app/modals/keyboard-shortcuts/View.less
- client/src/app/tabs/PropertiesContainer.less
- client/src/app/tabs/bpmn/BpmnEditor.less
- client/src/app/tabs/cloud-bpmn/BpmnEditor.less
- client/src/app/tabs/dmn/DmnEditor.less
- client/src/app/tabs/form/FormEditor.less
- client/src/app/tabs/json/JSONEditor.less
- client/src/app/tabs/xml/XMLEditor.less
- client/src/styles/_base.less
- client/src/styles/_buttons.less
- client/src/styles/_font.less
- client/src/styles/_forms.less
- client/src/styles/_modal.less
- client/src/styles/style.less
Closes #2458 
Artifacts
- https://camunda-modeler-on-demand.s3.eu-central-1.amazonaws.com/2458-ibm-plex-font/camunda-modeler-2458-ibm-plex-font-linux-x64.tar.gz
- https://camunda-modeler-on-demand.s3.eu-central-1.amazonaws.com/2458-ibm-plex-font/camunda-modeler-2458-ibm-plex-font-mac.dmg
- https://camunda-modeler-on-demand.s3.eu-central-1.amazonaws.com/2458-ibm-plex-font/camunda-modeler-2458-ibm-plex-font-mac.zip
- https://camunda-modeler-on-demand.s3.eu-central-1.amazonaws.com/2458-ibm-plex-font/camunda-modeler-2458-ibm-plex-font-win-ia32.zip
- https://camunda-modeler-on-demand.s3.eu-central-1.amazonaws.com/2458-ibm-plex-font/camunda-modeler-2458-ibm-plex-font-win-x64.zip
Using IBM Plex Sans as default font family
Using IBM Plex Mono as monospace font family (e.g. code editors)
------ …
> Add IBM Plex Font

- client/src/app/tabs/EngineProfile.js
- client/src/app/tabs/__tests__/EngineProfileSpec.js
- client/src/app/tabs/bpmn/BpmnEditor.js
- client/src/app/tabs/dmn/DmnEditor.js
- client/src/plugins/camunda-plugin/deployment-tool/DeploymentTool.js
- client/src/plugins/camunda-plugin/start-instance-tool/StartInstanceTool.js
- client/src/plugins/usage-statistics/event-handlers/DeploymentEventHandler.js
- client/src/plugins/usage-statistics/event-handlers/DiagramOpenEventHandler.js
- client/src/plugins/zeebe-plugin/deployment-plugin/DeploymentPlugin.js
- client/src/util/Engines.js
Closes #2544
- define engine strings and supported engine profiles globally
- replace `engineProfiles` for global const in `EngineProfile.js`
- replace 'Camunda Platform' and 'Camunda Cloud' strings with global consts
> Define engine profiles globally

- client/src/shared/ui/form/ToggleSwitch.js
- client/src/styles/_forms.less
Related to camunda/cloud-connect-modeler-plugin/issues/49
- add `disabled` prop
- change slider color based on `disabled` prop - temporary until new form items are aligned (talked over with @andreasgeier)
__Screenshot__
Switched off vs disabled:
> feat(toggle): allow toggle switch to be `disabled`

- client/src/plugins/report-feedback/ReportFeedbackOverlay.js
- client/src/plugins/report-feedback/ReportFeedbackOverlay.less
- client/src/plugins/report-feedback/ReportFeedbackSystemInfo.js
- client/src/plugins/report-feedback/ReportFeedbackSystemInfoSection.js
- client/src/plugins/report-feedback/__tests__/ReportFeedbackSystemInfoSpec.js
- client/src/plugins/version-info/ReleaseInfo.less
- client/src/plugins/version-info/VersionInfoOverlay.js
- client/src/plugins/version-info/VersionInfoOverlay.less
- client/src/shared/ui/Section.js
- client/src/shared/ui/Section.less
- client/src/shared/ui/__tests__/OverlaySpec.js
- client/src/shared/ui/__tests__/SectionSpec.js
- client/src/shared/ui/index.js
- client/src/shared/ui/overlay/Overlay.js
- client/src/shared/ui/overlay/Overlay.less
This contribution adds a re-usable section component.
Sections are fully pluggeable into existing UI components (i.e. overlays) and shall be used when the existing abstractions (overlay with single header, body and footer) do not work.
Sections and overlays are now properly max-sizeable without the need for a custom CSS:
---
General spirit of this PR:
* We shall not ever require custom CSS for basic UI (https://github.com/camunda/camunda-modeler/commit/21cd1f9fdd0f5202b59dfac778fe965b92615522) but rely on pre-built components entirely.
* We shall centralize the UI components we need and break out of the existing usage patter _explicitly_, where needed.
---
---
This PR is work in progress, as we need to discuss this as a team. Needs to be adjusted to …
> Add re-usable section component

- client/src/shared/ui/__tests__/OverlaySpec.js
- client/src/shared/ui/overlay/Overlay.js
- client/src/shared/ui/overlay/Overlay.less
This allows specifying more dimension properties as the existing `maxHeight`, `bottom`, `right`, `left`:
* `maxWidth`
* `minHeight`
* `minWidth`
* `top`
Rationale: it should be possible to place an overlay anywhere on the screen, not only above the status bar. This makes things as the coming tab actions possible, also in setting a specific minimal width.
> feat(overlay): add more dimen options

- client/src/app/primitives/Tabbed.less
Related to #2440
This is a follow-up to the discussions in [this issue](https://github.com/camunda/camunda-modeler/issues/2440). Note that I didn't touch the font size. Rationale: we use 14px in the status bar as well, and personally I think it's better to keep that consistent.
> style(tabbed): increase tab max-width

- app/lib/menu/menu-builder.js
- app/test/spec/menu/menu-builder-spec.js
This allows separating new file menu entries by defining groups. An alternative could be to simply add the separators to the tabs provider. Since one can disable certain providers by flags, that would be hard to order properly. Touching the `menu-builder` instead gives enough flexibility.
Example: we want to separate creating new tabs by execution platform (Platform + Cloud). 
```js
[
[
{ label: 'BPMN diagram', group: 'Camunda Platform', action: 'create-bpmn-diagram' }
],
[
{ label: 'BPMN diagram', group: 'Camunda Cloud', action: 'create-cloud-bpmn-diagram' }
],
[
{ label: 'DMN diagram', group: 'Camunda Platform', action: 'create-dmn-diagram' }
],
[
{ label: 'Form', group: 'Camunda Platform', action: 'create-form' }
],
[
{ label: 'Form', group: 'Camunda Cloud', action: 'create-cloud-form' …
```
> feat(app/menu): separate new file menus by group

- .github/workflows/BUILD_ON_DEMAND.yml
- .github/workflows/CI.yml
- .github/workflows/NIGHTLY.yml
- .github/workflows/RELEASE.yml
LTS now changed to 16 and we're not compatible with it yet.
> ci: run against node@14, not LTS

- client/src/plugins/zeebe-plugin/deployment-plugin/DeploymentPluginValidator.js
- client/src/plugins/zeebe-plugin/deployment-plugin/__tests__/DeploymentPluginValidatorSpec.js
* according to: `<uuid>.<region>.zeebe.<someHost>.<someTopLevelDomain>:443`
closes #2636
> chore(DeploymentPlugin): relax cloud URL validation

- client/resources/icons/TabContext.svg
- client/src/app/App.js
- client/src/app/__tests__/AppSpec.js
- client/src/plugins/create-new-action/CreateNewAction.js
- client/src/plugins/index.js
- client/src/plugins/tab-context-action/TabContextAction.js
- client/src/plugins/tab-context-action/__tests__/TabContextActionSpec.js
- client/src/plugins/tab-context-action/index.js
- client/src/shared/ui/__tests__/OverlayDropdownSpec.js
- client/src/shared/ui/overlay/OverlayDropdown.js
- client/src/shared/ui/overlay/OverlayDropdown.less
Closes #2630 
This includes
* firing an `app.tabsChanged` event whenever the tabs change
* adding a `maxHeight` prop for overlay dropdown option groups
* adding the tab context action (requirements cf. #2630)
------
Artifacts are ready to use 
* https://camunda-modeler-on-demand.s3.eu-central-1.amazonaws.com/2630-tab-context-menu/camunda-modeler-2630-tab-context-menu-linux-x64.tar.gz
* https://camunda-modeler-on-demand.s3.eu-central-1.amazonaws.com/2630-tab-context-menu/camunda-modeler-2630-tab-context-menu-mac.dmg
* https://camunda-modeler-on-demand.s3.eu-central-1.amazonaws.com/2630-tab-context-menu/camunda-modeler-2630-tab-context-menu-mac.zip
* https://camunda-modeler-on-demand.s3.eu-central-1.amazonaws.com/2630-tab-context-menu/camunda-modeler-2630-tab-context-menu-win-ia32.zip
* …
> Tab context action

- client/src/app/App.js
- client/src/app/__tests__/AppSpec.js
Closes #2581
Explanation: the spread operator only keeps the enumerable properties of the object itself. Therefore, functions like `getTitle()` were getting lost.
> fix: update tab with new attributes

- client/src/app/tabs/Linting.js
- client/src/app/tabs/Linting.less
- client/src/app/tabs/form/linting/FormLinter.js
- client/src/app/tabs/form/linting/__tests__/FormLinterSpec.js
- client/src/app/tabs/form/linting/__tests__/camunda-cloud-1-2-0.json
- client/src/app/tabs/form/linting/__tests__/camunda-platform-7-16-0.json
* Account for full `major.minor.patch` being serialized in diagrams.
* Show `major.minor` in error messages only
---
* https://camunda-modeler-on-demand.s3.eu-central-1.amazonaws.com/form-semver-maj-mi-pa/camunda-modeler-form-semver-maj-mi-pa-linux-x64.tar.gz
* https://camunda-modeler-on-demand.s3.eu-central-1.amazonaws.com/form-semver-maj-mi-pa/camunda-modeler-form-semver-maj-mi-pa-mac.dmg
* https://camunda-modeler-on-demand.s3.eu-central-1.amazonaws.com/form-semver-maj-mi-pa/camunda-modeler-form-semver-maj-mi-pa-mac.zip
* https://camunda-modeler-on-demand.s3.eu-central-1.amazonaws.com/form-semver-maj-mi-pa/camunda-modeler-form-semver-maj-mi-pa-win-ia32.zip
* https://camunda-modeler-on-demand.s3.eu-central-1.amazonaws.com/form-semver-maj-mi-pa/camunda-modeler-form-semver-maj-mi-pa-win-x64 …
> feat(form/linting): account for full semver specifiying version

- client/src/app/primitives/TabLinks.js
- client/src/app/primitives/Tabbed.less
- client/src/app/primitives/__tests__/TabLinksSpec.js
Closes #2639 
_Artifacts build [is running](https://github.com/camunda/camunda-modeler/runs/4701274691)_
- https://camunda-modeler-on-demand.s3.eu-central-1.amazonaws.com/2639-tab-close-non-active/camunda-modeler-2639-tab-close-non-active-linux-x64.tar.gz
- https://camunda-modeler-on-demand.s3.eu-central-1.amazonaws.com/2639-tab-close-non-active/camunda-modeler-2639-tab-close-non-active-mac.dmg
- https://camunda-modeler-on-demand.s3.eu-central-1.amazonaws.com/2639-tab-close-non-active/camunda-modeler-2639-tab-close-non-active-mac.zip
- https://camunda-modeler-on-demand.s3.eu-central-1.amazonaws.com/2639-tab-close-non-active/camunda-modeler-2639-tab-close-non-active-win-ia32.zip
- https://camunda-modeler-on-demand.s3.eu-central-1.amazonaws.com/2639-tab-close-non-active/camunda-modeler-2639- …
> fix(tabs): show close on non active tabs until threshold width

- client/src/plugins/camunda-plugin/deployment-tool/DeploymentTool.js
- client/src/plugins/camunda-plugin/deployment-tool/__tests__/DeploymentToolSpec.js
There was some discussion here as if further unit testing was needed. The way I see it not in this case, as the deployment tool  (platform plugin) doesn't conditionally provide that targetType, and the deployment event handler simply tunnels the targetType to a payload, irrespective of its nature (and we have a test which checks that this works). 
I'd love some thoughts here, give me a shout if you'd like me to clarify some things. 
Closes #2238
> feat: supplying default target type for platform deployment telemetry

- client/src/plugins/update-checks/NewVersionInfoView.js
* Note: when this is released, we shall not include the releaseVersion
in the releaseNoteBody in updateServer anymore
* closes #2422
I will also add a note to updateServer
> feat(updateChecks): always include versionInfo prior to releaseNote

- client/src/plugins/tab-context-action/__tests__/TabContextActionSpec.js
- client/src/shared/ui/__tests__/OverlayDropdownSpec.js
- client/src/shared/ui/overlay/OverlayDropdown.js
- client/src/shared/ui/overlay/OverlayDropdown.less
This adds arrow key navigation for all overlay dropdowns (e.g. create tab, context action, ...). It mirrors the behavior we already have with tab navigation.
Closes #2626
**Build on demand artefacts** (_[Build is running](https://github.com/camunda/camunda-modeler/actions/runs/1707490832) ..._)
- https://camunda-modeler-on-demand.s3.eu-central-1.amazonaws.com/2626-navigate-with-arrow-keys/camunda-modeler-2626-navigate-with-arrow-keys-linux-x64.tar.gz
- https://camunda-modeler-on-demand.s3.eu-central-1.amazonaws.com/2626-navigate-with-arrow-keys/camunda-modeler-2626-navigate-with-arrow-keys-mac.dmg
- https://camunda-modeler-on-demand.s3.eu-central-1.amazonaws.com/2626-navigate-with-arrow-keys/camunda-modeler-2626-navigate-with-arrow-keys-mac.zip
- …
> feat(overlay-dropdown): add arrow key navigation

- client/src/app/tabs/bpmn/BpmnEditor.js
- client/src/app/tabs/bpmn/__tests__/BpmnEditorSpec.js
- client/src/app/tabs/cloud-bpmn/BpmnEditor.js
- client/src/app/tabs/cloud-bpmn/__tests__/BpmnEditorSpec.js
- client/src/app/tabs/dmn/DmnEditor.js
- client/src/app/tabs/dmn/__tests__/DmnEditorSpec.js
- client/test/mocks/bpmn-js/Modeler.js
- client/test/mocks/dmn-js/Modeler.js
closes #2654
Tests were already present for this behavior, but because we mocked bpmn-js it was not caught:
https://github.com/camunda/camunda-modeler/blob/ff14d9615b8fb78ea1e41b17a24cf7a330f24840/client/src/app/tabs/bpmn/__tests__/BpmnEditorSpec.js#L1212-L1227
I adjusted the modeler mock accordingly
> fix(tabs): don't mark dirty after save

- package-lock.json
- package.json
Electron was updated recently on `develop` (cf. https://github.com/camunda/camunda-modeler/commit/599b1948d71d89e4ee1429f96cd2ca69744bef7b). However, only `package-lock.json` was updated. When running `npm i` and `npm run dev` I get an error saying that the GRPC dependency was built for the wrong platform (`electron@12.1` instead of `electron@12.0`). The goal of this pull request is to update the versions specified in `package.json` and `package-lock.json` and to eventually merge `master` into `develop` to algin the versions.
> chore: update electron to v12.1.x

- app/lib/zeebe-api.js
- client/src/plugins/camunda-plugin/start-instance-tool/StartInstanceConfigOverlay.js
- client/src/plugins/zeebe-plugin/deployment-plugin/DeploymentPlugin.js
- client/src/plugins/zeebe-plugin/deployment-plugin/DeploymentPluginConstants.js
- client/src/plugins/zeebe-plugin/deployment-plugin/DeploymentPluginOverlay.js
- client/src/plugins/zeebe-plugin/deployment-plugin/__tests__/DeploymentPluginSpec.js
- client/src/plugins/zeebe-plugin/start-instance-plugin/StartInstanceConfigOverlay.js
- client/src/plugins/zeebe-plugin/start-instance-plugin/StartInstanceConfigOverlay.less
- client/src/plugins/zeebe-plugin/start-instance-plugin/StartInstancePlugin.js
- client/src/plugins/zeebe-plugin/start-instance-plugin/__tests__/StartInstanceConfigOverlaySpec.js
- client/src/plugins/zeebe-plugin/start-instance-plugin/__tests__/StartInstancePluginSpec.js
- client/src/styles/_forms.less
Closes #2693
**Note:** to implement a 2-step approach for deploy+start instance like we do for platform, the **deployment** needed to be tweaked to be able to be controlled with **start instance** (get deploy config -> get start instance config -> deploy -> run instance)
> feat(startInstance): add overlay to Cloud start instance

- client/src/plugins/zeebe-plugin/deployment-plugin/DeploymentPluginValidator.js
- client/src/plugins/zeebe-plugin/deployment-plugin/__tests__/DeploymentPluginValidatorSpec.js
* closes #2636
* This reverts [30813a3](https://github.com/camunda/camunda-modeler/pull/2644/commits/30813a3e91120c16d91e6a4d4eeb52770c767d82)
> fix(cloudDeployPlugin): ensure only camunda URL for SaaS deployment

- CHANGELOG.md
* I noticed that Valentin for example was not aware of the blog post
* Hopefully this helps users, to better find the guidance we have in place
> chore(CHANGELOG): link to blogpost guiding plugin migration

- client/src/plugins/usage-statistics/event-handlers/__tests__/DeploymentEventHandlerSpec.js
- client/src/plugins/usage-statistics/event-handlers/__tests__/DiagramOpenEventHandlerSpec.js
- client/src/plugins/usage-statistics/event-handlers/__tests__/fixtures/user-tasks.bpmn
- client/src/util/metrics/userTasks.js
* Working with telemetry data, I realized that we have not updated our logic to also track `formRef` userTask form implementations
> feat(usageStatistics): track userTask formRef implementation

- .codecov.yml
Adjust codecov to allow slight regressions in patch coverage. Repositories in the camunda github org are not covered by our global bpmn-io yaml.
related to https://github.com/bpmn-io/internal-docs/issues/459
> chore(codecov): make PR checks more lenient

- .github/workflows/CI.yml
> CI: pin windows version to `windows-2019`

- client/package-lock.json
- client/package.json
- client/src/app/tabs/bpmn-shared/modeler/features/apply-default-templates/__tests__/applyDefaultTemplatesSpec.js
- client/src/app/tabs/bpmn-shared/modeler/features/apply-default-templates/applyDefaultTemplates.js
- client/src/app/tabs/bpmn/BpmnEditor.js
- client/src/app/tabs/bpmn/__tests__/BpmnEditorSpec.js
- client/src/app/tabs/cloud-bpmn/BpmnEditor.js
- client/src/app/tabs/cloud-bpmn/__tests__/BpmnEditorSpec.js
- client/src/plugins/element-templates-modal/ElementTemplatesModal.js
- client/src/plugins/element-templates-modal/__tests__/ElementTemplatesModalSpec.js
- client/src/plugins/element-templates-modal/modeler/EditorActions.js
- client/src/plugins/element-templates-modal/modeler/__tests__/bpmn-io-modelers/EditorActionsSpec.js
- client/src/util/__tests__/elementTemplatesSpec.js
- client/src/util/__tests__/fixtures/templates.json
- client/src/util/elementTemplates.js
- resources/element-templates/cloud-samples.json
Closes #2731 
Closes https://github.com/camunda/camunda-modeler/issues/2496
Closes https://github.com/camunda/camunda-modeler/issues/2749
Closes https://github.com/camunda/camunda-modeler/issues/2673
* Updates to `camunda-bpmn-js@0.13.0-alpha.3`
* Adds the `cloud-element-templates` feature to `cloud-bpmn` tabs
* Makes sure we only load specific element templates in the respective editors
* by using the cloud `ElementTemplatesValidator` provided via `camunda-bpmn-js`
* by checking the `$schema` attribute => needs to be provided + reference `@camunda/zeebe-element-templates-json-schema` (that needs to be documented, cf. #2723) 
* Enabled the catalog select plugin for `cloud-bpmn` tabs
* Adds samples for cloud templates
Some samples to try out, note that `$schema` needs to be set for cloud …
> Integrate cloud templates

- client/src/plugins/camunda-plugin/deployment-tool/DeploymentTool.js
- client/src/plugins/camunda-plugin/deployment-tool/__tests__/DeploymentToolSpec.js
- client/src/plugins/camunda-plugin/start-instance-tool/StartInstanceTool.js
- client/src/plugins/camunda-plugin/start-instance-tool/__tests__/StartInstanceToolSpec.js
- client/src/plugins/zeebe-plugin/deployment-plugin/DeploymentPlugin.js
- client/src/plugins/zeebe-plugin/deployment-plugin/__tests__/DeploymentPluginSpec.js
- client/src/plugins/zeebe-plugin/start-instance-plugin/StartInstancePlugin.js
- client/src/plugins/zeebe-plugin/start-instance-plugin/__tests__/StartInstancePluginSpec.js
Closes #2762
Seems like a lot of changes but just because I needed to add test structure to test this.
Added test cases for each of the deploy/start instance that test (1) if the overlay opens and (2) closes if the active tab changes.
> fix(deploy/start): clear overlay state when activeTab changes

- app/package-lock.json
- app/package.json
Bumps to [`zeebe-node@2`](https://github.com/camunda-community-hub/zeebe-client-node-js/blob/master/CHANGELOG.md#version-240) (builds on top of https://github.com/camunda/camunda-modeler/pull/2797).
Reduces the modeler distribution size from 130 MB to 100 MB (Linux).
Speeds up the build process significantly.
----
(https://github.com/camunda/camunda-modeler/actions/runs/1922103601)
* https://camunda-modeler-on-demand.s3.eu-central-1.amazonaws.com/update-zeebe-node/camunda-modeler-update-zeebe-node-linux-x64.tar.gz
* https://camunda-modeler-on-demand.s3.eu-central-1.amazonaws.com/update-zeebe-node/camunda-modeler-update-zeebe-node-mac.dmg
* https://camunda-modeler-on-demand.s3.eu-central-1.amazonaws.com/update-zeebe-node/camunda-modeler-update-zeebe-node-mac.zip
* …
> deps: update to zeebe-node@2

- client/package-lock.json
- client/package.json
- client/src/plugins/usage-statistics/event-handlers/DeploymentEventHandler.js
- client/src/plugins/usage-statistics/event-handlers/DiagramOpenEventHandler.js
- client/src/util/metrics/processVariables.js
- client/src/util/metrics/serviceTasks.js
- client/src/util/metrics/subprocessPlanes.js
- client/src/util/metrics/userTasks.js
- client/src/util/parse.js
With the latest `zeebe-bpmn-moddle` extension version, both Camunda and Zeebe define the `modelerTemplate` attrribute. Therefore, we can no longer use both when parsing XML and have to pass the diagram type to the parser.
> deps: bump to `camunda-bpmn-js@0.13.0-alpha.4`

- client/src/app/TabsProvider.js
Related to https://github.com/bpmn-io/internal-docs/issues/481
**Reminder:** This PR only covers the renaming and re-ordering of the menu options. The enhanced version will be handled by https://github.com/bpmn-io/internal-docs/issues/490
**Artifacts:**
https://camunda-modeler-on-demand.s3.eu-central-1.amazonaws.com/rename-c7-c8-file-menus/camunda-modeler-rename-c7-c8-file-menus-linux-x64.tar.gz
https://camunda-modeler-on-demand.s3.eu-central-1.amazonaws.com/rename-c7-c8-file-menus/camunda-modeler-rename-c7-c8-file-menus-mac.dmg
https://camunda-modeler-on-demand.s3.eu-central-1.amazonaws.com/rename-c7-c8-file-menus/camunda-modeler-rename-c7-c8-file-menus-mac.zip
https://camunda-modeler-on-demand.s3.eu-central-1.amazonaws.com/rename-c7-c8-file-menus/camunda-modeler-rename-c7-c8-file-menus-w …
> Rename to C7/C8 in new file menus

- app/lib/menu/menu-builder.js
Closes #2733
Works in built artifacts:
https://camunda-modeler-on-demand.s3.eu-central-1.amazonaws.com/2733-colors-file-menu/camunda-modeler-2733-colors-file-menu-linux-x64.tar.gz
https://camunda-modeler-on-demand.s3.eu-central-1.amazonaws.com/2733-colors-file-menu/camunda-modeler-2733-colors-file-menu-mac.dmg
https://camunda-modeler-on-demand.s3.eu-central-1.amazonaws.com/2733-colors-file-menu/camunda-modeler-2733-colors-file-menu-mac.zip
https://camunda-modeler-on-demand.s3.eu-central-1.amazonaws.com/2733-colors-file-menu/camunda-modeler-2733-colors-file-menu-win-ia32.zip
https://camunda-modeler-on-demand.s3.eu-central-1.amazonaws.com/2733-colors-file-menu/camunda-modeler-2733-colors-file-menu-win-x64.zip
> Fix color icon path in edit menu

- client/src/app/App.js
- client/src/app/TabsProvider.js
- client/src/app/__tests__/AppSpec.js
- client/src/app/__tests__/TabsProviderSpec.cloud.dmn
- client/src/app/__tests__/TabsProviderSpec.js
- client/src/app/__tests__/mocks/index.js
- client/src/app/tabs/cloud-dmn/DmnEditor.js
- client/src/app/tabs/cloud-dmn/DmnTab.js
- client/src/app/tabs/cloud-dmn/__tests__/DiagramSpec.js
- client/src/app/tabs/cloud-dmn/__tests__/DmnEditorSpec.js
- client/src/app/tabs/cloud-dmn/__tests__/diagram.dmn
- client/src/app/tabs/cloud-dmn/__tests__/diagram11.dmn
- client/src/app/tabs/cloud-dmn/diagram.dmn
- client/src/app/tabs/cloud-dmn/index.js
- client/src/app/tabs/cloud-dmn/modeler/DmnModeler.js
- client/src/app/tabs/cloud-dmn/modeler/index.js
- client/test/bpmn-io-modelers/dmn/CloudDmnModelerSpec.js
- client/test/mocks/dmn-js/Modeler.js
Closes #2525 
---
Built on top of https://github.com/camunda/camunda-modeler/pull/2838
The Cloud DMN diagrams can be created via menu; the welcome page button will be implemented via https://github.com/camunda/camunda-modeler/issues/2844
Use [cloud.dmn.txt](https://github.com/camunda/camunda-modeler/files/8351505/cloud.dmn.txt) to open existing file.
Artifacts:
- https://camunda-modeler-on-demand.s3.eu-central-1.amazonaws.com/2525-add-cloud-dmn-tab/camunda-modeler-2525-add-cloud-dmn-tab-linux-x64.tar.gz
- https://camunda-modeler-on-demand.s3.eu-central-1.amazonaws.com/2525-add-cloud-dmn-tab/camunda-modeler-2525-add-cloud-dmn-tab-mac.dmg
- https://camunda-modeler-on-demand.s3.eu-central-1.amazonaws.com/2525-add-cloud-dmn-tab/camunda-modeler-2525-add-cloud-dmn-tab-mac.zip
- …
> Add Cloud DMN tab

- client/src/plugins/version-info/VersionInfoOverlay.js
* We should link to desktop modeler rather than generic "Modeler" docs
from the Camunda Modeler
> fix(versionOverlay): link to desktop modeler docs

- client/src/plugins/usage-statistics/event-handlers/BaseEventHandler.js
- client/src/plugins/usage-statistics/event-handlers/PingEventHandler.js
- client/src/plugins/usage-statistics/event-handlers/__tests__/PingEventHandlerSpec.js
Closes #2818
To be able to use `config.get()`, I made the `enable` function async. I tested manually and ran the tests and it doesn't seem to mess up anything. But let me know if there is a better way to do this.
> chore(telemetry): track plugins usage

- client/src/plugins/usage-statistics/UsageStatistics.js
- client/src/plugins/usage-statistics/__tests__/UsageStatisticsSpec.js
- client/src/plugins/usage-statistics/event-handlers/BaseEventHandler.js
- client/src/plugins/usage-statistics/event-handlers/PingEventHandler.js
- client/src/plugins/usage-statistics/event-handlers/__tests__/PingEventHandlerSpec.js
Fix https://github.com/camunda/camunda-modeler/pull/2857
After merging, I realised that `config` only stores the plugins properties.  So if a plugin doesn't store any properties, it would not appear there. The proper way to do this is to use `_getGlobal("plugins")`, which also fixes the async problem in #2857 since it's synchronous.
> fix(telemetry): get plugins with `getGlobal`

- client/src/plugins/usage-statistics/event-handlers/DiagramOpenEventHandler.js
- client/src/plugins/usage-statistics/event-handlers/__tests__/DiagramOpenEventHandlerSpec.js
This is a preparation for once we support template icons in the Modeler.
Related to https://github.com/bpmn-io/internal-docs/issues/445
> feat(usage-statistics): track icons usage

- app/lib/index.js
* Replace deprecated `new-window` handler with `setWindowOpenHandler`.
* Suppress any navigation (we don't use it).
Closes #2905
> Open target=_blank links once

- client/src/plugins/report-feedback/ReportFeedbackOverlay.js
- client/src/shared/ui/overlay/Overlay.less
Closes #2882
https://user-images.githubusercontent.com/25825387/162963040-9987c8d4-82ac-45ec-937d-bf34cfb780a6.mov
> fix(overlay): adjust max heights to always fit viewport

- app/lib/menu/menu-builder.js
Closes #2873 
`lastTab` was only set on tab driven menu updates, which don't happen on a blank start
For menu entries, `enabled: undefined` defaults to `true`, as it should (if we're not defining it the menu entry should just always work)
> 2873 reopen last tab startup

- .github/workflows/COMMENT_DEVELOP_FIX.yml
* I realized that we in some cases don't follow our best-pratice to do fixes for camunda-modeler on `master` rather than on `develop`
* example: https://github.com/camunda/camunda-modeler/pull/2893
* This GHA is meant to support us with this, by notifying us via a comment:
> feat(GHA): add GHA to comment on fix commits to develop

- client/src/remote/Dialog.js
- client/src/remote/__tests__/DialogSpec.js
Closes #2970
**Artefacts**
- https://camunda-modeler-on-demand.s3.eu-central-1.amazonaws.com/file-dialog-consistency/camunda-modeler-file-dialog-consistency-linux-x64.tar.gz
- https://camunda-modeler-on-demand.s3.eu-central-1.amazonaws.com/file-dialog-consistency/camunda-modeler-file-dialog-consistency-mac.dmg
- https://camunda-modeler-on-demand.s3.eu-central-1.amazonaws.com/file-dialog-consistency/camunda-modeler-file-dialog-consistency-mac.zip
- https://camunda-modeler-on-demand.s3.eu-central-1.amazonaws.com/file-dialog-consistency/camunda-modeler-file-dialog-consistency-win-ia32.zip
- https://camunda-modeler-on-demand.s3.eu-central-1.amazonaws.com/file-dialog-consistency/camunda-modeler-file-dialog-consistency-win-x64.zip
Could you have a look if the appropriate action button is …
> fix: improved file dialog consistency across OSes

- client/src/plugins/usage-statistics/event-handlers/DeploymentEventHandler.js
- client/src/plugins/usage-statistics/event-handlers/DiagramOpenEventHandler.js
- client/src/plugins/usage-statistics/event-handlers/__tests__/DeploymentEventHandlerSpec.js
- client/src/plugins/usage-statistics/event-handlers/__tests__/DiagramOpenEventHandlerSpec.js
Follow up from https://github.com/camunda/camunda-modeler/pull/2941#issuecomment-1134215534
- Use existing `getEngineProfile` utility and remove duplicate code
- Adjust tests (some were missing execution platform version)
> refactor(usageStatistics): use existing `getEngineProfile` utility

- app/lib/menu/menu-builder.js
- app/test/spec/menu/menu-builder-spec.js
- client/src/app/TabsProvider.js
_Originated from https://github.com/camunda/camunda-modeler/pull/3035._
This prevents duplicated help menu entries in the backend.
Closes #3032
> Prevent duplicated help menu entries

- CHANGELOG.md
* `FEAT`: toggle properties panel errors when toggling error panel ([#3014](https://github.com/camunda/camunda-modeler/pull/3014))
* `FIX`: fix error panel styles ([#3015](https://github.com/camunda/camunda-modeler/pull/3015))
* `FIX`: load modeling styles globally ([#3031](https://github.com/camunda/camunda-modeler/pull/3031))
* `DEPS`: bump @camunda/linting to v0.3.4 ([#3065](https://github.com/camunda/camunda-modeler/pull/3065))
* `DEPS`: bump diagram-js to v8.7.1 ([#3065](https://github.com/camunda/camunda-modeler/pull/3065))
* `DEPS`: bump diagram-js-direct-editing to v1.7.0 ([#3065](https://github.com/camunda/camunda-modeler/pull/3065))
* `DEPS`: bump diagram-js-origin to v1.3.3 ([#3065](https://github.com/camunda/camunda-modeler/pull/3065))
* `DEPS`: bump min-dom to v3.2.1 …
> chore(CHANGELOG): update to v5.2.0

- client/package-lock.json
- client/package.json
Change log update isn't necessary as this feature will only be added with Camunda Modeler 5.2,
Closes #3067
> deps: update @camunda/linting to v0.3.5

- client/src/plugins/version-info/ReleaseInfo.js
As suggested by @christian-konrad I changed it to say _diagram errors_.
> chore: adjust release info

- .github/ISSUE_TEMPLATE/RELEASE.md
Adds the Release checklist as a issue template 
required by https://github.com/bpmn-io/fake-join/pull/42
> chore(TEMPLATES): add release to issue templates

- CHANGELOG.md
- client/src/app/tabs/cloud-dmn/modeler/DmnModeler.js
- client/src/app/tabs/dmn/modeler/DmnModeler.js
I wasn't using the API correctly and attached the DRD viewer directly instead of attaching the dmn-js container. 🤦🏻 We don't have tests for this at the moment. 😞 I'd still like to include this fix in v5.2.
Closes #3048
> fix: attach and detach DMN overview properly

- client/src/plugins/user-journey-statistics/MixpanelHandler.js
We recently discovered we were tracking user's paths to the application (which we shouldn't). This was because Mixpanel tracks `$current_url` automatically.
This PR blacklists that property
> Remove `$current_url` from Mixpanel tracking

- client/src/plugins/version-info/ReleaseInfo.js
> chore(version-info): update release notes

- app/package-lock.json
- app/package.json
- package-lock.json
Follow up of https://github.com/camunda/camunda-modeler/pull/3116
Seems like I missed this one after latest `rebase`...
> deps(app): bump to `zeebe-node@8.0.3`

- app/lib/index.js
- app/lib/zeebe-api.js
- app/lib/zeebe-api/get-system-certificates.js
- app/lib/zeebe-api/index.js
- app/lib/zeebe-api/zeebe-api.js
- app/package.json
- app/test/spec/zeebe-api-spec.js
- client/src/plugins/zeebe-plugin/deployment-plugin/DeploymentPlugin.js
- client/src/plugins/zeebe-plugin/deployment-plugin/DeploymentPluginConstants.js
- client/src/plugins/zeebe-plugin/deployment-plugin/DeploymentPluginValidator.js
- client/src/plugins/zeebe-plugin/deployment-plugin/__tests__/DeploymentPluginValidatorSpec.js
- package-lock.json
This adds a flag for custom SSL certificate: `--zeebe-ssl-certificate=<path-to-file>`.
Protocol http(s) is now required for the contact points of self-hosted Zeebe instances.
Closes #3028
---
* Running Docker.
* Installed openssl.
1. Clone this repo: https://github.com/barmac/zeebe-tls-connection-test
2. In the repo, run `npm run cert`. This will generate `cert.pem` file which will be our certificate. Note that you may need to adjust the `generate-cert.sh` file, namely the `/usr/local/opt/openssl/bin/openssl` part to work on your OS. This is done specifically for MacOS.
3. Run `npm run zeebe` in a separate terminal window. This will run locally a Zeebe instance which will use the certificate for SSL.
Run Camunda Modeler with flag `--zeebe-ssl-certificate=<path-to-cert.pem>`, and try to …
> Allow to connect to Zeebe with a custom certificate

- client/src/app/tabs/bpmn/BpmnEditor.js
- client/src/app/tabs/bpmn/__tests__/BpmnEditorSpec.js
- client/src/app/tabs/bpmn/modeler/BpmnModeler.js
- client/src/app/tabs/cloud-bpmn/BpmnEditor.js
- client/src/app/tabs/cloud-bpmn/__tests__/BpmnEditorSpec.js
- client/test/mocks/bpmn-js/Modeler.js
* activate and deactivate linting only on toggle error panel
* simplify implementation
* rename #onToggleLinting to #handleToggleLinting
* add linting annotations to Camunda 7 BPMN editor
---
Closes #3127
> fix: toggle linting only when error panel toggled

- app/lib/zeebe-api/zeebe-api.js
- app/test/spec/zeebe-api-spec.js
- client/src/plugins/zeebe-plugin/deployment-plugin/DeploymentPlugin.js
- client/src/plugins/zeebe-plugin/deployment-plugin/__tests__/DeploymentPluginSpec.js
- client/src/plugins/zeebe-plugin/start-instance-plugin/StartInstancePlugin.js
- client/src/plugins/zeebe-plugin/start-instance-plugin/__tests__/StartInstancePluginSpec.js
closes https://github.com/camunda/camunda-modeler/issues/3223
Changes:
- rename `workflow` -> `process`
- API: `createProcessInstance({bpmnProcessId, variables})` -> `createProcessInstance(bpmnProcessId, variables)`
> fix(zeebe): use non-deprecated zeebe-node API

- app/lib/index.js
- package-lock.json
- package.json
I had to explicitly disable the new sandboxing behavior shipped with Electron@20 (cf. [breaking docs](https://www.electronjs.org/docs/latest/breaking-changes#default-changed-renderers-without-nodeintegration-true-are-sandboxed-by-default), [preload documentation](https://www.electronjs.org/docs/latest/tutorial/sandbox#preload-scripts)).
Otherwise our existing preload script fails to execute.
> Update to Electron@21.0.0

- app/lib/zeebe-api/zeebe-api.js
- app/test/spec/zeebe-api-spec.js
> fix: set explicitly `useTLS=false` for http endpoints

- client/src/app/TabsProvider.js
- client/src/app/__tests__/TabsProviderSpec.js
sort by priority when multiple providers specified for the extension
closes #2957
> fix: create C8 diagram from empty bpmn file

- .github/workflows/ADD_TO_PROJECT.yaml
This is to prevent action runs for community PRs (which fortunately fail due to missing secrets): https://github.com/camunda/camunda-modeler/actions/runs/3335186161/jobs/5518891113
> fix(ci): don't run ADD_TO_PROJECT for fork PRs

- app/lib/menu/menu-builder.js
- app/test/spec/menu/menu-builder-spec.js
- client/src/app/tabs/form/FormEditor.js
- client/src/app/tabs/form/FormPreviewToggle.js
- client/src/app/tabs/form/__tests__/FormEditorSpec.js
- client/src/app/tabs/form/getFormWindowMenu.js
- client/src/plugins/user-journey-statistics/__tests__/UserJourneyStatisticsSpec.js
- client/src/plugins/user-journey-statistics/event-handlers/FormEditorEventHandler.js
- client/src/plugins/user-journey-statistics/event-handlers/__tests__/FormEditorEventHandlerSpec.js
- client/src/plugins/user-journey-statistics/event-handlers/index.js
- client/src/util/parse.js
- client/test/mocks/form-js/index.js
Closes #3247 
This one
* exposes `triggeredByShortcut` to menu click events. This is needed to distinguish whether menu actions are triggered by keyboard shortcuts or not.
* adds the following three Mixpanel events 
> Every time a playground panel got collapsed or expanded.
```json
{
"event": "desktopModeler:formEditor:layoutChanged",
"properties": {
"executionPlatform": "Camunda Platform|Camunda Cloud",
"executionPlatformVersion": "x.y",
"layout": {
"form-input": {
"open": true
},
"form-output": {
"open": true
},
"form-preview": {
"open": true
}
},
"triggeredBy": "keyboardShortcut|previewPanel|statusBar|windowMenu", 
}
}
```    
> Interactions with the Form Input Data panel (not every edit, but focusin + focusout + changed)
```json
{
"event": "desktopModeler:formEditor:inputDataChanged", …
```
> Form Playground Tracking

- client/src/app/tabs/panel/tabs/LintingTab.js
- client/src/app/tabs/panel/tabs/LintingTab.less
- client/src/app/tabs/panel/tabs/__tests__/LintingTabSpec.js
Sort lint reports by
1. category
2. name or ID
thus ensuring that errors will be shown first.
---
Closes https://github.com/camunda/camunda-modeler/issues/3272
> Sort Lint Reports by Category

- client/src/app/TabsProvider.js
- client/src/app/__tests__/TabsProviderSpec.js
- client/src/util/Engines.js
- client/src/util/__tests__/EnginesSpec.js
I decided to stick with "Camunda 8.2" as target label (instead of "8.2-alpha") to keep the naming consistent with the lint warnings. 
closes #3284
> feat(Engines): add Camunda 8.2 profile

- client/package.json
- package-lock.json
> deps: update @camunda/linting to v0.9.1

- client/package.json
- client/src/app/tabs/bpmn/modeler/BpmnModeler.js
- package-lock.json
Remove workaround necessary for 5.5.1 release.
----
Closes https://github.com/camunda/camunda-modeler/issues/1753
Closes https://github.com/camunda/camunda-modeler/issues/3276
Closes https://github.com/camunda/camunda-modeler/issues/1371
Closes https://github.com/camunda/camunda-modeler/issues/1705
Closes https://github.com/camunda/camunda-modeler/issues/1750
> deps(client): update to camunda-bpmn-js@0.23.1

- app/lib/index.js
- app/package.json
- package-lock.json
With this in place, the app should be still usable even if the output is piped to a closed stream, e.g. `npm start | head`. Check out linked issue for more details.
Closes #3313
> fix(app): suppress EPIPE errors for app output

- docs/.project/RELEASE_TEMPLATE.md
Releases are reoccurring events now
> docs: remove manually adding release appointments

- docs/.project/RELEASE.md
- docs/.project/RELEASE_TEMPLATE.md
Proposal to:
* To make process more consistent with other Product component teams
> chore(RELEASE): announce releases in #c8-release-announcements

- app/util/get-version.js
- dev.js
Ensures the `dev` version of the modeler has a `minorInc-dev` tag rather than showing the currently released version:
> chore: tag development build with `minorInc-dev`

- app/lib/zeebe-api/zeebe-api.js
- app/test/spec/zeebe-api/zeebe-api-spec.js
So that we can still detect problems and give guidance but not enforce too rigid validation.
> feat: pass certificate to zeebe even if appears invalid

- tasks/distro.js
closes #3394
- `--repo-version=` --> drop for positional parameter
- `--skip-npm` --> replaced by using `lerna version` instead of `lerna publish`
- `--skip-git` --> replaced by `--no-git-tag-version` + `--no-push`
Output for distro task to show that all deprecation warnings are gone:
```
% node tasks/distro.js --linux --nightly                                                                                                                                                    
PUBLISH: undefined
Bumping camunda-modeler version to 5.8.0-nightly.20230201
---
lerna version 5.8.0-nightly.20230201 --no-git-tag-version --no-push --yes
---
lerna notice cli v5.6.2
lerna info current version 5.7.0
lerna notice FYI git repository validation has been skipped, please ensure your version bumps are …
```
> chore(distro): fix lerna build warnings

- .github/workflows/NIGHTLY.yml
- tasks/distro.js
This migrates the nightly GitHub Action to upload artifacts directly to Camunda Download Center. After it's merged, we should disable the Jenkins action and can safely remove the nightly buckets on AWS.
Related to https://github.com/bpmn-io/internal-docs/issues/470
> Migrate nightly out of AWS

- docs/.project/RELEASE_TEMPLATE.md
This improves the current publishing steps:
* updates to latest blog publishing flow
* simplifies getting started with the blog by using a tailored template
> docs(RELEASE_TEMPLATE): clarify publishing steps

- app/lib/menu/mac-os/mac-menu-builder.js
- app/lib/menu/menu-builder.js
Closes #3444 
MacOS shortcuts for switching tabs next and previous is now `Cmd+SHIFT+[`  and `Cmd+SHIFT+]` respectively. Window shortcut remain `Control+TAB` and `Control+SHIFT+TAB` respectively.
> feat: 3444 Add MacOS specific switch tabs keyboard shortcuts

- app/lib/menu/mac-os/mac-menu-builder.js
- client/src/plugins/zeebe-plugin/deployment-plugin/DeploymentPlugin.js
- client/src/plugins/zeebe-plugin/deployment-plugin/__tests__/DeploymentPluginSpec.js
- client/src/plugins/zeebe-plugin/start-instance-plugin/StartInstancePlugin.js
- client/src/plugins/zeebe-plugin/start-instance-plugin/__tests__/StartInstancePluginSpec.js
Closes #3457 
bug: 3457 hide "Check for Updates" on MacOS menu when disable-remote-interaction flag is true.
> Hide `Check for Updates` on MacOS menu when disable-remote-interaction is set

- client/src/plugins/update-checks/NewVersionInfoView.js
- client/src/plugins/update-checks/NewVersionInfoView.less
- client/src/plugins/update-checks/PrivacyPreferencesLink.js
- client/src/plugins/update-checks/__tests__/NewVersionInfoViewSpec.js
- client/src/plugins/update-checks/constants.js
This PR proposes a sensible improvement to our existing release note container:
> Update check release note container rework

- client/src/app/AppParent.js
- client/src/app/KeyboardBindings.js
- client/src/app/__tests__/AppParentSpec.js
- client/src/app/__tests__/KeyboardBindingsSpec.js
**Context**
I was trying to open create the create menu on the position of the keyboard shortcut event that triggered it  
**Issue**
Currently there isn’t really a way to trigger an editor action via keyboard bindings and send the event as an argument. I discovered that we actually allow for a `event` param [here](https://github.com/camunda/camunda-modeler/blob/develop/client/src/app/AppParent.js#L52) but we don’t use it. Also, we have the `event` in KeyboardBindings but we [choose to pass it as `null`](https://github.com/camunda/camunda-modeler/blob/develop/client/src/app/KeyboardBindings.js#L150). 
Me and Martin discussed this and figured that there is no reason not to send the event, and this is probably an oversight (because it hasn’t been needed yet).
**Suggestion**
Use the second …
> fix(app): allow to send event via keyboard shortcuts

- client/package.json
- client/src/app/util/__tests__/generateImageSpec.js
- client/src/app/util/generateImage.js
- package-lock.json
This replaces warnings-triggering `canvg-browser` with `canvg`, and upgrades some deps via npm audit fix.
Note that this touches PNG/JPG export facility. It works on my Mac though.
----
Closes https://github.com/camunda/camunda-modeler/issues/3434
> Fix vulnerable deps

- client/src/plugins/user-journey-statistics/UserJourneyStatistics.js
- client/src/plugins/user-journey-statistics/__tests__/UserJourneyStatisticsSpec.js
- client/src/plugins/user-journey-statistics/event-handlers/PingEventHandler.js
- client/src/plugins/user-journey-statistics/event-handlers/__tests__/PingEventHandlerSpec.js
Related to https://github.com/camunda/camunda-modeler/issues/3486
**Context:**
The "ping" event was not being sent initially because it was being configured before Mixpanel was enabled. I added `tracking.enabled`/`tracking.disabled` emitted events to manage this.
This didn't happen before because previous events are only triggered via user actions. With "ping", we want to send it specifically after tracking has been enabled.
> Fix "ping" event

- app/package.json
- package-lock.json
Update to `8.2` version.
I integration tested this against self-managed using [zeebe-connection-test](https://github.com/camunda/zeebe-connection-test).
> deps: bump `zeebe-node`

- .snyk
This will remove clutter from Snyk reports as `tasks` is not part of the application.
> chore: exclude tasks from Snyk Code reports

- CHANGELOG.md
- app/lib/zeebe-api/zeebe-api.js
- app/test/spec/zeebe-api/zeebe-api-spec.js
Before this fix, we did not pass certificates to the oauth config
which is separated from customSSL.
Related to https://github.com/camunda-community-hub/zeebe-client-node-js#oauth
This popped up via [SUPPORT-15807](https://jira.camunda.com/browse/SUPPORT-15807)
> fix: use custom SSL certificate for oAuth connection

- resources/platform/base/resources/element-templates/README.md
Based on feedback from @GeethaParthasarathy I've added an `element-templates` directory to avoid confusion.
> chore: add empty element templates directory

- client/package.json
- client/src/app/tabs/bpmn/modeler/BpmnModeler.js
- client/src/app/tabs/cloud-bpmn/modeler/BpmnModeler.js
- client/src/plugins/user-journey-statistics/MixpanelHandler.js
- client/src/plugins/user-journey-statistics/__tests__/UserJourneyStatisticsSpec.js
- client/src/plugins/user-journey-statistics/event-handlers/ModelingEventHandler.js
- client/src/plugins/user-journey-statistics/event-handlers/__tests__/ModelingEventHandlerSpec.js
- client/src/plugins/user-journey-statistics/event-handlers/index.js
- package-lock.json
Closes #3572 
This PR integrates `bpmn-js-tracking` by:
* including modules in platform and cloud modelers
* adding `ModelingEventHandler` (similar to existing tracking) that handles the `bpmn-js-tracking` events
* transforming `bpmn-js-tracking` events data. Only send relevant information for elements: currently id, element type, template applied. We can expand this as needed (cc @christian-konrad )
While doing this I found these issues with `bpmn-js-tracking`, but we can start with this review and just bump the version when these are implemented:
* https://github.com/bpmn-io/bpmn-js-tracking/issues/21 
* https://github.com/bpmn-io/bpmn-js-tracking/issues/22
> Integrate `bpmn-js-tracking`

- client/src/plugins/zeebe-plugin/deployment-plugin/DeploymentPlugin.js
- client/src/plugins/zeebe-plugin/deployment-plugin/__tests__/DeploymentPluginSpec.js
- client/src/plugins/zeebe-plugin/shared/__tests__/utilSpec.js
- client/src/plugins/zeebe-plugin/shared/util.js
- client/src/plugins/zeebe-plugin/start-instance-plugin/StartInstancePlugin.js
Closes #3605
Apart from version change, this includes also `instances -> processes` endpoint change, as without it the link worked only for second and next deployments of the same version.
Before:
https://github.com/camunda/camunda-modeler/assets/28307541/2ec48eae-6c21-44cc-8c00-ad00af286d9e
After:
https://github.com/camunda/camunda-modeler/assets/28307541/753a756f-8aa6-4725-a779-b9af1866cdff
> feat: link directly to deployed process definition

- client/src/app/tabs/form/FormEditor.js
- client/src/app/tabs/form/__tests__/FormEditorSpec.js
- client/test/mocks/form-js/index.js
Closes #3640
The issue went under the radar because in tests we mock Forms Editor even to an extent where we mock non-existing module 🤡
> fix: remove non-existing linting module usage in forms

- client/src/app/resizable-container/ResizableContainer.less
> fix(resizable-container): resizer is behind overlays and modals

- CHANGELOG.md
- app/package.json
- package-lock.json
Accounts for `customSSL.rootCerts` when connecting to Camunda 8 SaaS.
Related to upstream bug https://github.com/camunda-community-hub/zeebe-client-node-js/issues/319.
-----
Related to SUPPORT-16844
> deps: update to zeebe-node@8.2.4

- client/src/app/tabs/bpmn/modeler/BpmnModeler.js
- client/src/app/tabs/cloud-bpmn/modeler/BpmnModeler.js
_Fixing a oopsie I made._
When updating the `bpmn-js-tracking` last time, I forgot to add the newest tracking module, seeing as we add each one explicitly.
> feat(mixpanel): add templates tracking module

- client/src/app/tabs/bpmn/BpmnEditor.js
- client/src/app/tabs/cloud-bpmn/BpmnEditor.js
- client/src/app/tabs/cloud-dmn/DmnEditor.js
- client/src/app/tabs/dmn/DmnEditor.js
As found in https://github.com/camunda/camunda-modeler/issues/3687 post import errors in the BPMN editors were not appropriately handled.
Reviewing the existing code it was clear that it 
(1) swallowed existing exceptions
(2) did not catch exceptions in all cases, i.e. https://github.com/camunda/camunda-modeler/issues/3687.
This PR should clean up the matter.
> Handle post import errors

- client/webpack.config.js
Applies upgrade notices as found [here](https://github.com/getsentry/sentry-javascript-bundler-plugins/blob/main/MIGRATION.md#upgrading-from-1x-to-2x-webpack-plugin-only).
Fixes [our release building](https://github.com/camunda/camunda-modeler/actions/runs/5461919291/jobs/9940561568).
----
Related to https://github.com/camunda/camunda-modeler/issues/3689
> chore(client): migrate webpack config to use @sentry/webpack-plugin@2

- client/package.json
- package-lock.json
Includes https://github.com/bpmn-io/bpmn-js-tracking/issues/34 fix
> deps: update to `bpmn-js-tracking@0.3.2`

- client/src/plugins/zeebe-plugin/deployment-plugin/DeploymentPluginOverlay.less
Applies standard link styles.
---
This unifies across desktop and web modeler.
> fix(deploy): color troubleshooting link in standard way

- client/src/app/TabsProvider.js
- client/src/app/__tests__/TabsProviderSpec.js
- client/src/app/tabs/EngineProfile.js
- client/src/util/Flags.js
This implements two new flags:
* `c8-engine-version`
* `c7-engine-version`
The version passed to a flag (e.g. `--c8-engine-version=8.2.0`) determines the default engine version for new files.
Closes #3515
---
Thanks to @strangelookingnerd for the initial implementation.
> feat: add flags for default execution version

- client/src/app/primitives/TabLinks.js
Closes #3729.
I wasn't sure if any additional tests are needed for this, as it basically is just a copy of what is done when clicking the "x" button on the right side of a tab. Let me know if I should add anything here.
> feat(tabs): close tabs on middle mouse button click

- app/lib/zeebe-api/zeebe-api.js
- app/package.json
- app/test/spec/zeebe-api/zeebe-api-spec.js
- package-lock.json
Closes #3772. 
Adds the alpha package of zeebe-node, and modifies the code to use the new APIs that support tenantId.
> Use `zeebe-node@8.3.0-alpha4` to stub `tenantId`

- app/lib/util/error-tracking.js
- client/src/plugins/error-tracking/ErrorTracking.js
- client/src/plugins/error-tracking/__tests__/ErrorTrackingSpec.js
- client/webpack.config.js
related to #3689
As we have no easy way of experimenting with sentry releases, let's try this out on nightly builds instead.
b2316208e90ff7e89cb0ddad68c6225182500703 should fix sentry not recognizing the URL of reported file paths:
1c6b1be2ff1057e412c9618900ae985af24a84c3 should fix source-map uploading
> chore(sentry): fix sourcemaps

- app/lib/util/error-tracking.js
- client/package.json
- client/src/plugins/error-tracking/ErrorTracking.js
- client/src/plugins/error-tracking/__tests__/ErrorTrackingSpec.js
- client/webpack.config.js
- package-lock.json
it took some time to figure everything out, but here it is:
https://camunda-modeling.sentry.io/issues/4399063171/?project=5223041&query=release%3Aupload-sourcemap-test-dev&referrer=release-issue-stream
Unfortunately, it seems we need legacy sourcemaps for our setup so everything gets referenced correctly after we normalize the path
closes #3689
> fix sentry source maps (for real this time)

- client/src/app/resizable-container/ResizableContainer.js
- client/src/app/resizable-container/__tests__/ResizableContainerSpec.js
Instead of setting the width or height to 0, it's set to the last width or height.
Closes #3753
> fix(resizable-container): use last width/height if closed through resize

- .github/workflows/CI.yml
This improves our CI behavior, working around shaky MacOS builds.
We'll not fail all other jobs (so feedback is discarted), but let them continue.
> ci: always complete matrix builds

- app/lib/util/__tests__/files-spec.js
- app/lib/util/files.js
This ensures we don't change path handling semantics on Windows as we migrate from `glob` to `fast-glob` (https://github.com/camunda/camunda-modeler/commit/e33c4b68f4c479188ea484f2efa120ab1afd1c22).
> chore(app): restore windows path handling

- app/lib/config/providers/ElementTemplatesProvider.js
Parents assumes the argument passed in is a directory name, not a file name.
fast-glob handles non-directory files that are glob roots with an error that we want to avoid. Hence we fix this bug. 
----
Error reported through the application log (also console) without this fix when reading local to `test (51).bpmn` element templates:
```
ERROR app:config:element-templates templates /home/foo/test (51).bpmn/.camunda glob error Error: ENOTDIR: not a directory, scandir '/home/foo/test (51).bpmn/.camunda/element-templates'
at Object.readdirSync (node:fs:1452:3)                                                                 
at Object.readdirSync (node:electron/js2c/asar_bundle:2:10837)                                         
at readdirWithFileTypes …
```
> fix: use directory name to match element templates

- .github/workflows/RELEASE.yml
This will ensure anything we do in the release pipeline is meant for production.
Closes #3835
> fix: set NODE_ENV=production in release pipeline

- client/src/plugins/zeebe-plugin/deployment-plugin/__tests__/DeploymentPluginSpec.js
- client/src/plugins/zeebe-plugin/shared/__tests__/utilSpec.js
- client/src/plugins/zeebe-plugin/shared/util.js
- client/src/plugins/zeebe-plugin/start-instance-plugin/StartInstancePlugin.js
- client/src/plugins/zeebe-plugin/start-instance-plugin/__tests__/StartInstancePluginSpec.js
Adjusts an oversight from https://github.com/camunda/camunda-modeler/pull/3773.
Previously I did not properly adjust client-side usages of the new response.
> fix: adjust code base to ZeebeNode#deployResource API responses

- .github/workflows/RELEASE.yml
In the very recent https://github.com/camunda/camunda-modeler/commit/0573f6d57e21d6025f5064ae2f779876561d1b2f, I set `NODE_ENV=production` for each of the steps of the release pipeline. This broke installation due to:
>  With the --production flag (or when the NODE_ENV environment variable is set to production), npm will not install modules listed in devDependencies. To install all modules listed in both dependencies and devDependencies when NODE_ENV environment variable is set to production, you can use --production=false.
With that change, the build step couldn't use the devDependencies as they were not installed at all.
> ci: set NODE_ENV=production for build only

- app/lib/config/providers/ElementTemplatesProvider.js
- app/lib/flags.js
- app/lib/plugins.js
- app/lib/util/__tests__/files-spec.js
- app/lib/util/files.js
- app/test/spec/plugins-spec.js
Added https://github.com/camunda/camunda-modeler/pull/3863/commits/5578416fedbe8caa32b555fb09c5140ab398b284 to verify the fix. `globFiles` is now being used by element templates and plugins feature.
Closes https://github.com/camunda/camunda-modeler/issues/3862
> Use POSIX Paths Consistently With `fast-glob`

- .github/workflows/RELEASE.yml
This is to prevent a situation when an otherwise successful step is cancelled due to other step failing. For example, in https://github.com/camunda/camunda-modeler/actions/runs/6249575466/attempts/1 the Windows job was cancelled, even though it succeeded to upload the artifacts.
> ci: do not cancel release when one step fails

- client/src/plugins/zeebe-plugin/deployment-plugin/DeploymentPluginOverlay.js
Proposes to drop the miss-leading audience hint. Cf. #3864 for rationale.
Closes #3864
> fix(zeebe-plugin): drop missleading hint

- app/lib/zeebe-api/zeebe-api.js
- app/test/spec/zeebe-api/zeebe-api-spec.js
Recent versions of `zeebe-node` do not return the error code anymore (for self-managed at least), instead I get the following error:
```
ERROR app:zeebe-api connection check failed {                            
parameters: {                                                          
endpoint: {                                                          
type: 'oauth',     
url: 'https://****non-existing-zeepe-api',
oauthURL: 'https://login.cloud.ultrawombat.com/oauth/token',
audience: 'zeebe-api',
clientId: '******',                                                
clientSecret: '******'   
}                                                                    
}                                                                      
} Error: 13 INTERNAL: Received RST_STREAM with code 2 triggered …
```
> feat(zeebe-api): infer error codes (where unavailable) from message

- client/src/app/panel/tabs/linting/LintingTab.js
We cannot rely on the report being unique. For example, there can easily be two equal reports caused by a rule error:
```
{
"message": "I blow up",
"category": "rule-error",
"executionPlatform": "Camunda Cloud",
"executionPlatformVersion": "8.3.0",
"propertiesPanel": {
"entryIds": []
},
"documentation": {
"url": null
},
"rule": "custom/rule-error"
}
```
Reports don't have unique IDs and even if they had, they wouldn't be stable since the linter is stateless and the IDs would change every time we lint. Therefore we can only use the index as the key even though it's considered a bad practice. Alternatively, we could assign a random ID to every report. 🤔
> Prevent Duplicate React ™️ Keys in Problems Panel

- .github/workflows/RELEASE_ISSUE.yml
related to https://github.com/bpmn-io/internal-docs/issues/803
this ensures that the slack role for the release manager is in sync with the current assignee, both for newly created issues and reassignments.
As always with Github actions, I am about 80% sure this works but there is no way to test it without merging first 🙈
> chore(CI): automatically sync slack roles

- docs/.project/RELEASE_TEMPLATE.md
Follow-up to https://github.com/camunda/camunda-modeler/pull/3923
This is done automatically now
> chore(docs): remove manual slack assignment step

- client/.babelrc
- client/package.json
- package-lock.json
We now target current Electron version via `@babel/preset-env`, and can safely remove some babel plugins.
> chore: transpile to electron version

- app/lib/zeebe-api/zeebe-api.js
- app/package.json
- client/src/plugins/camunda-plugin/deployment-tool/__tests__/DeploymentToolSpec.js
- client/src/plugins/zeebe-plugin/deployment-plugin/DeploymentPlugin.js
- client/src/plugins/zeebe-plugin/deployment-plugin/DeploymentPluginConstants.js
- client/src/plugins/zeebe-plugin/deployment-plugin/DeploymentPluginOverlay.js
- client/src/plugins/zeebe-plugin/deployment-plugin/__tests__/DeploymentPluginOverlaySpec.js
- client/src/plugins/zeebe-plugin/deployment-plugin/__tests__/DeploymentPluginSpec.js
- client/src/plugins/zeebe-plugin/start-instance-plugin/StartInstancePlugin.js
- client/src/remote/__tests__/ZeebeAPISpec.js
- package-lock.json
This adds visual editing of `tenantId`. We keep the existing pattern that `tenantId` is maintained with the _deployment_, and simply carried over by the _run_ tool.
----
----
> Allow passing `tenantId` to Camunda 8 self-managed

- client/src/plugins/user-journey-statistics/event-handlers/TabEventHandler.js
- client/src/plugins/user-journey-statistics/event-handlers/__tests__/TabEventHandlerSpec.js
- client/src/plugins/user-journey-statistics/event-handlers/__tests__/fixtures/nested.form
- client/src/util/parse.js
Closes #3132
Related to https://github.com/camunda/team-hto/issues/350
This updates the `desktopModeler:diagram:closed` event with `formFieldTypes` in case a Form was closed. We run the element type collection recursively as we can have nested forms nowadays.
Example:
```json
"formFieldTypes": {
"textfield": 6,
"group": 2,
"image": 4 
}
```
> feat(mixpanel): add formFieldTypes to diagram closed event

- app/lib/zeebe-api/zeebe-api.js
- app/package.json
- app/test/spec/zeebe-api/zeebe-api-spec.js
- client/src/app/util/parseDiagramType.js
- client/src/plugins/user-journey-statistics/event-handlers/DeploymentEventHandler.js
- client/src/plugins/user-journey-statistics/event-handlers/OverlayEventHandler.js
- client/src/plugins/user-journey-statistics/event-handlers/TabEventHandler.js
- client/src/plugins/user-journey-statistics/util.js
- client/src/plugins/zeebe-plugin/deployment-plugin/DeploymentPlugin.js
- client/src/plugins/zeebe-plugin/deployment-plugin/__tests__/DeploymentPluginSpec.js
- client/src/remote/ZeebeAPI.js
- client/src/remote/__tests__/ZeebeAPISpec.js
- client/src/util/parse.js
- package-lock.json
---
Related to https://github.com/camunda/camunda-modeler/issues/3656
> Deploy Camunda 8 Forms

- client/src/app/tabs/cloud-dmn/DmnEditor.js
- client/src/app/tabs/cloud-dmn/__tests__/DmnEditorSpec.js
- client/src/app/tabs/dmn/DmnEditor.js
- client/src/app/tabs/dmn/__tests__/DmnEditorSpec.js
- client/src/app/tabs/dmn/getDmnEditMenu.js
> fix: integrate DRD find

- client/src/app/panel/tabs/linting/LintingTab.less
> chore: always show linting documentation link if available

- client/src/app/panel/Panel.js
- client/src/app/panel/__tests__/PanelSpec.js
fixes #4021
We now rerender the Tab entry when the content (children/label/id/...) changes
> fix(Panel): rerender Tab on prop changes

- client/src/plugins/zeebe-plugin/start-instance-plugin/StartInstanceConfigOverlay.js
Spellchecking the _Variables_ JSON doesn't make sense. Ideally, the textarea should be a code editor anyway.
> fix: do not spellcheck Variables JSON

- client/src/app/tabs/dmn/DmnEditor.less
Closes #4053
This `outline: none` is not adding anything (not present in the bpmn.io demo) and breaks the focus style. Alternatively, we could just reinforce on focus but as far as I can see, this doesn't change anything.
> chore: allow focus on dmn buttons

- client/webpack.config.js
This is a common extension for ES module exports.
Adresses [`[headsu`](https://camunda.slack.com/archives/GP70M0J6M/p1706869768978479).
> fix(client): don't bundle `cjs` files as strings

- client/src/plugins/version-info/ReleaseInfo.js
Proposing the following what's new communication:
> feat(version-info): update to v5.20.0

- client/src/app/tabs/bpmn/modeler/features/properties-panel-keyboard-bindings/FeelPopupKeyboardBindings.js
> fix: unbind popup editor `focusout` mock in a safe manner

- client/src/plugins/version-info/ReleaseInfo.js
> chore(ReleaseInfo): prepare 5.21.0

- docs/.project/RELEASE_TEMPLATE.md
We moved to branch names `main` for this and all referenced projects. This Updates links and snippets to reflect that
> chore(RELEASE_TEMPLATE): update branch names

- .github/workflows/BUILD_ON_DEMAND.yml
- .github/workflows/CI.yml
- .github/workflows/NIGHTLY.yml
- .github/workflows/RELEASE.yml
MacOS 11 is not supported anymore.
> ci: build on MacOS 12

- CHANGELOG.md
- client/package.json
- package-lock.json
> deps(client): update to `camunda-bpmn-js@4.5.1`

- .github/workflows/BUILD_ON_DEMAND.yml
- .github/workflows/NIGHTLY.yml
- .github/workflows/RELEASE.yml
This ensures we can build windows releases until a solution for #4243 is integrated.
Tested with build on demand:
https://github.com/camunda/camunda-modeler/actions/runs/8874773314/job/24362837554
Windows artifacts from the build are available here: 
https://camunda-modeler-on-demand.s3.eu-central-1.amazonaws.com/disable-signing-on-windows/camunda-modeler-disable-signing-on-windows-win-ia32.zip
https://camunda-modeler-on-demand.s3.eu-central-1.amazonaws.com/disable-signing-on-windows/camunda-modeler-disable-signing-on-windows-win-x64.zip
> chore(CI): do not sign windows app

- .github/workflows/NEW_ALPHA_ISSUE.yml
- .github/workflows/NEW_MAJOR_ISSUE.yml
- docs/.project/RELEASE_TEMPLATE.md
With this PR we:
- automatically open issues before and after scheduled minor engine releases to remind us
- add a step to the release procedure as a sanity check and for unscheduled releases
> Ensure we updated engine profiles before/after major releases

- dev.js
- package-lock.json
- package.json
Related to https://github.com/bpmn-io/internal-docs/issues/892
> chore: load axe-devtools extension in dev mode

- resources/element-templates/new-fields.json
We'd otherwise get an error message due to new validation.
Related to 681d53db43ca47d84b68b9cb871bc93ef1f23743
> chore: correct `element-templates/new-fields` example

- app/lib/menu/menu-builder.js
- app/test/spec/menu/menu-builder-spec.js
> fix(menu-builder): remove new file options from tab menu

- client/package.json
- client/src/app/tabs/bpmn/BpmnEditor.less
- client/src/app/tabs/bpmn/__tests__/BpmnEditorSpec.js
- client/src/app/tabs/bpmn/modeler/BpmnModeler.js
- client/src/app/tabs/cloud-bpmn/BpmnEditor.less
- client/src/app/tabs/cloud-bpmn/__tests__/BpmnEditorSpec.js
- client/src/app/tabs/cloud-bpmn/modeler/BpmnModeler.js
- client/src/app/tabs/cloud-dmn/modeler/DmnModeler.js
- client/src/app/tabs/dmn/DmnEditor.less
- client/src/app/tabs/dmn/modeler/DmnModeler.js
- client/src/util/Flags.js
- client/test/bpmn-io-modelers/dmn/DmnModelerSpec.js
- client/test/mocks/bpmn-js/Modeler.js
- package-lock.json
Adds the ability to enable the new context pad through the `enable-new-context-pad` flag.
----
Related to https://github.com/camunda/camunda-modeler/issues/4263
> Integrate new context pad

- client/src/plugins/version-info/ReleaseInfo.js
This updates the release information to v5.24.0, proposal:
> chore: update release info for v5.24.0

- client/package.json
- client/src/index.js
- client/src/util/a11y.js
- package-lock.json
This dev tool should help us to identify accessibility issues. We will need to drop it with React 18 upgrade (some day...), but until then it should be useful.
Related to https://github.com/bpmn-io/internal-docs/issues/909
> chore: use `@axe-core/react` in dev

- docs/.project/INTEGRATION_TEST.md
Related to https://github.com/bpmn-io/camunda-modeler-plugin-a11y-checker/issues/1
We don't need to use dev console anymore.
> docs: update integration test to refer to the a11y plugin UI

- app/lib/index.js
- client/public/index.html
Closes #4376
This PR replaces the main process code used for the window title with an HTML `<title>` tag. The content is hard-coded as "Camunda Modeler" in contrast to the old solution where we added "(dev)" for dev mode, but this piece of information is already represented in the bottom-right "what's new" button. The main advantage of the current solution is that the a11y tools won't report missing title anymore.
> fix: set document title

- client/src/app/tabs/json/CodeMirror.js
- client/src/app/tabs/xml/CodeMirror.js
https://github.com/camunda/camunda-modeler/assets/28307541/d4edf538-e103-42a1-bb01-cbf00878a568
This PR:
- adds accessible names to the code editors
- adds tabindex necessary to satisfy ~~the beast~~ axe-core which currently reports lack of interactive content in the code editor.
Closes #4370
> Add accessible names and tabindex to code editors

- package-lock.json
- package.json
the latest lerna release breaks the package-lock during release. To ensure a smooth release, we should use the latest working version.
cf. https://github.com/lerna/lerna/issues/4026
> deps: pin lerna version to `8.1.2`

- package-lock.json
Update feel-editor to not include unsafe evaluation. This fixes the feel-editor. To test this, use the build artifacts since unsafe eval is allowed in the dev setup:
```
npm ci
npm run build
```
closes #4398
> deps: update to @bpmn-io/feel-editor@1.6.1

- client/src/app/tabs/bpmn/modeler/BpmnModeler.js
- client/src/app/tabs/bpmn/modeler/features/improved-canvas/EditorActions.js
- client/src/app/tabs/bpmn/modeler/features/improved-canvas/index.js
- client/src/app/tabs/cloud-bpmn/modeler/BpmnModeler.js
- client/test/bpmn-io-modelers/bpmn/BpmnModelerSpec.js
- client/test/bpmn-io-modelers/bpmn/CloudBpmnModelerSpec.js
- client/test/bpmn-io-modelers/bpmn/diagram.bpmn
Closes #4349
This adds a small adapter to register `appendElement` action again.
https://github.com/camunda/camunda-modeler/assets/28307541/bb681fd8-d751-4ef6-b57e-3936549f5ee2
We could change the improved canvas code to use the `appendElement` as the name of the action, but that would mean we introduce a dependency between create-append and improved-canvas. Another option would be to patch `getEditMenu`, but I excluded that to not make it depend on the flags if unnecessary.
> fix: register `appendElement` action with improved context pad

- CHANGELOG.md
- client/package.json
- package-lock.json
This removes linting error for converging inclusive gateway when execution platform is set to Camunda 8.6
Closes #3613
deps: update to `@camunda/linting@3.22.0`
> feat: support converging inclusive gateway

- .github/workflows/NIGHTLY.yml
- .github/workflows/RELEASE.yml
This PR migrates nightly and release jobs to use Sentry secrets pulled from the vault. The secrets are also migrated to the new organisation.
Closes #4413
> Migrate sentry to new org / import sentry secrets from vault

- client/src/app/tabs/EngineProfile.js
- client/src/app/tabs/EngineProfileHelper.js
- client/src/app/tabs/__tests__/EngineProfileSpec.js
- client/src/app/tabs/bpmn/__tests__/BpmnEditorSpec.js
- client/src/app/tabs/cloud-bpmn/__tests__/BpmnEditorSpec.js
- client/src/app/tabs/cloud-dmn/__tests__/DmnEditorSpec.js
- client/src/app/tabs/dmn/__tests__/DmnEditorSpec.js
- client/src/app/tabs/form/__tests__/FormEditorSpec.js
closes #2682
Optimistically open all diagrams, even if the engine/version is not supported. 
- If the version is unsupported, show it as `unsupported` in the Version selection and add link to the modeler download page to update the modeler:
- If the execution platform is unknown, open it as C8 diagram
- (fix) If unknown patch version is set in the diagram, map to minor version
You can try it out by either editing the XML directly in the modeler or changing the file externally and then open it using the file dialog.
> feat(engineProfile): open all diagrams

- .github/workflows/RELEASE_ISSUE.yml
Closes #4417
This PR makes us use `curl --fail-with-body` so that when API call fails, the action fails too.
Cf. https://superuser.com/questions/590099/can-i-make-curl-fail-with-an-exitcode-different-than-0-if-the-http-status-code-i
> ci: make curl fail on unsuccessful call to slack API

- CHANGELOG.md
- client/src/util/Engines.js
Closes #4396
Removes Camunda 8 versions < 8.0.
> chore: remove old Zeebe versions

- CHANGELOG.md
- client/package.json
- package-lock.json
- feat: change Header value and Field Injection value to text areas ([bpmn-io/bpmn-js-properties-panel#1065](https://github.com/bpmn-io/bpmn-js-properties-panel/pull/1065))
- feat: support Zeebe execution listeners ([bpmn-io/bpmn-js-properties-panel#1048](https://github.com/bpmn-io/bpmn-js-properties-panel/pull/1048))
- fix: improve behavior of text areas with `autoResize` property ([#4419](https://github.com/camunda/camunda-modeler/issues/4419))
- deps: update to `camunda-bpmn-js@4.14.0`
- deps: update to `@bpmn-io/properties-panel@3.22.3`
- deps: update to `bpmn-js-properties-panel@5.19.0`
- deps: update to `zeebe-bpmn-moddle@1.2.0`
Closes #2982
Closes #4419
> chore: update dependencies and changelog

- CHANGELOG.md
- client/package.json
- package-lock.json
Updates BPMN modeling dependencies, adding support for #4450.
Closes https://github.com/camunda/camunda-modeler/issues/4450
Closes https://github.com/camunda/camunda-modeler/issues/4140
Closes https://github.com/camunda/camunda-modeler/issues/3534
* Add a user task
* Priority field should be available under assignment
* Should be feel optional
* Should take any integer between 0 & 100, or a feel expression, and should have corresponding linting rules + properties panel errors when not
* Should be unsupported pre 8.6, and have corresponding linting rules
* Should have a tooltip explaining more or less how it works
* Should set extension property `priorityDefinition`, attribute `priority`
* Should clean the extension property on clearing the priority
To ensure you provided everything we …
> deps: update BPMN modeling libraries

- client/package.json
- client/src/app/panel/tabs/linting/LintingTab.js
- client/src/app/panel/tabs/log/LogTab.js
- client/src/app/panel/tabs/variable-outline/VariableOutlineTab.js
- client/src/app/tabs/cloud-bpmn/BpmnEditor.js
- client/src/app/tabs/cloud-bpmn/__tests__/BpmnEditorSpec.js
- client/test/mocks/bpmn-js/Modeler.js
- package-lock.json
Adds the Variable tab to the desktop modeler. 
related to https://github.com/camunda/camunda-modeler/issues/4267
Integration was also tested in the variable-outline PR: https://github.com/bpmn-io/variable-outline/pull/1
> feat(cloud-bpmn): add variable outline tab

- app/lib/index.js
Renames the flag from `enable-connector-templates` to `disable-*`, as you explicitly have to "opt out".
Related to https://github.com/camunda/camunda-modeler/issues/4455.
> chore: rename flag to `disable-connector-templates`

- CHANGELOG.md
- package-lock.json
- package.json
Related to #4483
Related to https://github.com/camunda/camunda-modeler/issues/4467
Since electron@32 introduces breaking changes which require to modify multiple parts of the app (cf. https://github.com/camunda/camunda-modeler/issues/4483#issuecomment-2311778398), for now we can keep electron@31. The version in this PR contains a fix for https://github.com/camunda/camunda-modeler/issues/4467
> deps: upgrade to `electron@31.4.0`

- client/src/app/panel/tabs/variable-outline/VariableOutlineTab.js
- client/src/app/panel/tabs/variable-outline/VariableOutlineTab.less
Adjusts the IBM Carbon styles of the variable outline tab so that it looks more like it's part of the modeler. This is a proposal that needs discussion in terms of how and where to actually fix the IBM Carbon styles and whether the fixes should also work for the next IBM Carbon component we introduce.
> Fix variable outline styles

- client/src/util/Engines.js
- client/src/util/__tests__/EnginesSpec.js
Makes Camunda 7.22 and Camunda 8.6 the latest released versions.
> feat: mark Camunda 7.22 and Camunda 8.6 as latest

- client/src/app/panel/tabs/linting/LintingTab.js
- client/src/app/panel/tabs/linting/__tests__/LintingTabSpec.js
Closes #4473
Linting tab can now handle reports that are missing both name and id.
> fix: handle linting reports without name and id

- .github/workflows/ASSIGN_MILESTONE.yml
As observed in [this action run](https://github.com/camunda/camunda-modeler/actions/runs/10983777044/job/30493543868) our automatic assignment utility insufficiently handles multiple open [development milestones](https://github.com/camunda/camunda-modeler/milestones). These can be open in case we push things to a future milestone.
The following query properly returns only the first (supposed to be active) development milestone:
```
gh api -H "Accept: application/vnd.github.v3+json" \
/repos/camunda/camunda-modeler/milestones \
--jq '[.[] | select(.title | startswith("M")) | .number ][0]'
```
> ci: correctly handle multiple open milestones

- package-lock.json
Bump to @bpmn-io/feel-editor@1.9.1, correcting variable completion for non-arg FEEL built-ins:
Closes #4539 
> Correct completion for non-arg FEEL built-ins

- client/src/plugins/version-info/ReleaseInfo.js
Adds release info for [v5.28.0 release](https://github.com/camunda/camunda-modeler/issues/4521):
> chore: add v5.28.0 release info

- CHANGELOG.md
- client/package.json
- package-lock.json
@nikku When updating `form-js` we forgot to bump playground. This caused the CSS to be broken
Not sure if we can still make the release since the freeze is already in place
> deps: bump to @camunda/form-playground@0.16.1

- CHANGELOG.md
- client/package.json
- package-lock.json
As we were not able to easily find the problem cause, this reverts commit 8f6662dc5a8e6e558a6d2052a747b5654673d031.
Closes #4559
> deps: downgrade to form-js@1.10.0

- client/src/app/App.js
- client/src/app/EmptyTab.js
- client/src/app/TabsProvider.js
- client/src/app/__tests__/TabsProviderSpec.js
- client/src/index.js
- client/src/remote/Plugins.js
- client/src/remote/__tests__/PluginsSpec.js
This PR adds the client plugin point `tabs` that allows users to create custom file type editors. This can be used to ship editors, e.g. for `.robot` files as a plugin.
The changes are fairly straight forward:
- allow expansion of `TabsProvider`
- Export commonly used Tab Components in `Plugins.js` so they can be used in Plugins
- Add Slot for additional file types on Welcome page
To allow tabs to be created, I added a new command `create-diagram` in `App.js`. This allows files to trigger `createDiagram` without hardcoding the file type in the command, which is not possible from Plugins.
You can check an example integration of the plugin point here: https://github.com/camunda/camunda-modeler/blob/RPA-spike/resources/plugins/test-tab/client/index.js
related to …
> feat: allow custom filetype support via plugins

- client/package.json
- package-lock.json
- package.json
This prevents duplicated react and broken builds
Use correct `@testing-library/react` version for React 16.
Background: 
- The current nighly can't open the variables tab
- This is caused by https://github.com/camunda/camunda-modeler/commit/6ff1d3ee2df19ea9e7f7b72732e60449abfc92b3 adding a testing library
- This added react@18 to node_modules, breaking deduplication for additional react modules with peer dependencies, causing them to use different react versions than the main app
To try out:
- Start the modeler using `npm dev`
- Try to open variable outline in C8 diagram
- It should work
> fix(package.json): use correct testing library version

- .github/workflows/BUILD_ON_DEMAND.yml
- .github/workflows/CI.yml
- .github/workflows/NIGHTLY.yml
- .github/workflows/RELEASE.yml
Related to https://github.com/actions/runner-images/issues/10721
MacOS-12 runner is soon going out of support. I suggest we run on the latest version from now on.
> ci: use macos-latest runner

- client/package.json
- package-lock.json
Updates @camunda/linting to fix https://github.com/camunda/camunda-modeler/issues/4562.
Closes #4562
> deps(client): update @camunda/linting to v3.27.2

- CHANGELOG.md
- client/src/app/EmptyTab.less
- client/src/app/primitives/TabLinks.js
- client/src/plugins/privacy-preferences/PrivacyPreferencesView.less
- client/src/plugins/update-checks/NewVersionInfoView.less
- client/src/shared/ui/overlay/Overlay.less
- client/src/styles/_base.less
- client/src/styles/_font.less
- client/src/styles/_forms.less
- client/src/styles/_modal.less
Closes #4555
Welcome tab now always looks the same, even if you open and close some diagrams.
> fix: add explicit styles for welcome tab

- tasks/link-dependencies.js
Use `yarn link` without additional scripts for diagram-js and bpmn-js.
> chore: simplify link-dependencies task

- tasks/link-dependencies.js
Node_modules dir is hoisted to the root. Previously, the linked package was added in client but the one hoisted to root was used in build.
> Fix dependencies linking

- client/src/app/EmptyTab.js
- client/src/app/EmptyTab.less
The gap can be configured directly in CSS. This is a cleanup so there are no visual changes.
> chore: remove flex-spacer from welcome tab

- app/lib/util/__tests__/error-tracking-spec.js
- app/lib/util/error-tracking.js
- client/src/plugins/error-tracking/ErrorTracking.js
- client/src/plugins/error-tracking/__tests__/ErrorTrackingSpec.js
- set Sentry tags according to v8 standards (cf. https://github.com/getsentry/sentry-javascript/blob/develop/CHANGELOG.md#other-deprecation-removalschanges). `configureScope` is deprecated.
- Explicitly set user to editor ID
closes https://github.com/bpmn-io/internal-docs/issues/1062
You can see the user is set in this sample report: https://camunda.sentry.io/issues/6018899142/events/a2096dc4c3724384bd6ab2db61403ed5/
> fix(errorTracking): add user configuration to sentry

- .github/workflows/CREATE_MILESTONE.yml
- add some basic error handling to the `create milestone` action, to gracefully handle the case when we try to create a milestone that already exists (e.g. https://github.com/camunda/camunda-modeler/actions/runs/11072955308/job/30768404834)
related to https://github.com/bpmn-io/internal-docs/issues/1052
> Gracefully handle creating milestone with existing name

- client/src/app/tabs/bpmn/diagram.bpmn
- client/src/app/tabs/cloud-bpmn/__tests__/DiagramSpec.js
- client/src/app/tabs/cloud-bpmn/diagram.bpmn
closes #4488
Changes the initial positioning of the initial diagrams start event so it snaps properly to the grid
> fix(client): fix initial diagram coordinates

- .github/workflows/ADD_TO_PROJECT.yml
- .github/workflows/ASSIGN_MILESTONE.yml
- .github/workflows/BUILD_ON_DEMAND.yml
- .github/workflows/CI.yml
- .github/workflows/CODE_SCANNING.yml
- .github/workflows/COMMENT_DEVELOP_FIX.yml
- .github/workflows/CREATE_MILESTONE.yml
- .github/workflows/MERGE_MAIN_TO_DEVELOP.yml
- .github/workflows/NEW_ALPHA_ISSUE.yml
- .github/workflows/NEW_MAJOR_ISSUE.yml
- .github/workflows/NIGHTLY.yml
- .github/workflows/PUBLISH_RELEASE.yml
- .github/workflows/RELEASE.yml
- .github/workflows/RELEASE_ISSUE.yml
As discussed today in the morning, we want the release manager update to be explicitly notified to the team. This allows to react early in case the new release manager is not available. The PR is aiming to achieve that.
In [the boy scout rule](https://backendtea.com/post/boyscout-rule/) spirit, I also unified the slack integration in this repo to use the same version tag of the action, and consistently import the secrets from the vault.
> Notify the release manager & slack integration improvements

- .github/workflows/ASSIGN_MILESTONE.yml
- .github/workflows/CODE_SCANNING.yml
- .github/workflows/CREATE_MILESTONE.yml
- .github/workflows/NEW_ALPHA_ISSUE.yml
- .github/workflows/NEW_MAJOR_ISSUE.yml
- .github/workflows/PUBLISH_RELEASE.yml
- .github/workflows/RELEASE_ISSUE.yml
Proposal to make workflow names follow the file names they are defined in.
> ci: unify workflow names (follow file name)

- client/src/app/resizable-container/ResizableContainer.less
This slightly adjusts the position of the resizer, so folks can somewhat interact with crowded contents above or right to it, cf. the following screen captures:
Closes #4093
Try out via 
```
npx @bpmn-io/sr camunda/camunda-modeler#reposition-resizer
```
> feat: adjust resizer position to be more friendly

- CHANGELOG.md
- app/lib/menu/menu-builder.js
- client/src/app/App.js
- client/src/app/__tests__/AppSpec.js
- client/src/app/panel/tabs/variable-outline/VariableOutlineStatusBarItem.js
- client/src/app/panel/tabs/variable-outline/VariableOutlineTab.js
- client/src/app/panel/tabs/variable-outline/__tests__/VariableOutlineStatusBarItemSpec.js
- client/src/app/tabs/bpmn/BpmnEditor.js
- client/src/app/tabs/bpmn/__tests__/BpmnEditorSpec.js
- client/src/app/tabs/bpmn/getBpmnWindowMenu.js
- client/src/app/tabs/cloud-bpmn/BpmnEditor.js
- client/src/app/tabs/cloud-bpmn/__tests__/BpmnEditorSpec.js
- client/src/app/tabs/cloud-dmn/DmnEditor.js
- client/src/app/tabs/cloud-dmn/__tests__/DmnEditorSpec.js
- client/src/app/tabs/cmmn/CmmnEditor.js
- client/src/app/tabs/cmmn/__tests__/CmmnEditorSpec.js
- client/src/app/tabs/cmmn/getCmmnWindowMenu.js
- client/src/app/tabs/dmn/DmnEditor.js
- client/src/app/tabs/dmn/__tests__/DmnEditorSpec.js
- client/src/app/tabs/dmn/getDmnWindowMenu.js
Closes #4516 
(For Mac OS): Press `Command + Shift + V`
> Improve Variables Tab Access and Bottom Panel Controls

- client/src/plugins/camunda-plugin/deployment-tool/DeploymentTool.js
- client/src/plugins/camunda-plugin/deployment-tool/__tests__/DeploymentToolSpec.js
- client/src/shared/ui/form/FileInput.js
- client/src/shared/ui/form/__tests__/FileInputSpec.js
This makes sure we can again deploy with attachments which was broken since the Electron 32 migration.
We solve both the new file deployment as well as the already broken config:
Closes #4694
> Make multi file deployment work again

- client/src/plugins/report-feedback/ReportFeedback.js
- client/src/plugins/update-checks/UpdateChecks.js
- client/src/plugins/version-info/VersionInfo.js
This reverts the recent change of the group names which caused the issue in the linked comment.
Related to https://github.com/camunda/camunda-modeler/commit/b79fe1dec26fac603980b2639a46dc8656661dcd#r149356417
Use group name starting with `Z` for the nudge, and old group names for other buttons.
> fix: display status bar in correct order

- CHANGELOG.md
- client/package.json
- package-lock.json
This PR:
* updates zeebe-bpmn-moddle (apparently the new version was used already in build, so this is for clarity only)
* updates changelog for the release
Related to #4691
> Update changelog for v5.30.0

- client/src/plugins/version-info/ReleaseInfo.js
> chore: update release info to v5.30

- client/src/plugins/version-info/ReleaseInfo.js
Related to #4691
Related to https://github.com/camunda/camunda-modeler/pull/4713
This captures the @crobbins215's suggestions:
Side-by-side:
| current | proposal
| ------- | -------- |
| ![image](https://github.com/user-attachments/assets/6c5f6ba7-b96b-4c93-8e60-7c179ed5017a) | ![_Users_maciej_workspace_bpmn-io_camunda-modeler_client_build_index html](https://github.com/user-attachments/assets/1d9f0379-0964-4b3d-923d-fbebcc6161eb)
|
> chore: reword release info

- CHANGELOG.md
- client/package.json
- package-lock.json
Closes #4718
This removes the error as user tasks implemented as job workers are still allowed in Camunda 8.7.
> fix: do not mark job worker user task as incorrect

- docs/.project/INTEGRATION_TEST.md
This adds missing links on file type bindings.
To check: Do we still need them on Windows? How does it work on Linux?
> docs: document file bindings

- .github/workflows/CREATE_MILESTONE.yml
This fixes a bug introduced in https://github.com/camunda/camunda-modeler/commit/e6cef095be3951b7e0e9bd53ec9e462327655174
In the added step, the GH token was not passed which resulted in job failures, cf. https://github.com/camunda/camunda-modeler/actions/runs/12034593870/job/33551510382
> ci: add GH token

- CHANGELOG.md
- client/src/plugins/zeebe-plugin/start-instance-plugin/StartInstancePlugin.js
- client/src/plugins/zeebe-plugin/start-instance-plugin/__tests__/StartInstancePluginSpec.js
This changes the route to accommodate for Operate's routes change.
Closes #4741
https://github.com/user-attachments/assets/5dccac7d-9670-4ade-9793-1d75c14189a5
> Use `/processes` route for run instance link

- client/package.json
- client/src/app/panel/Panel.less
- client/src/app/primitives/TabLinks.js
- client/src/app/primitives/Tabbed.less
- client/src/app/resizable-container/ResizableContainer.js
- client/src/app/resizable-container/ResizableContainer.less
- client/src/app/status-bar/StatusBar.less
- client/src/app/tab-actions/TabActions.less
- client/src/shared/ui/Section.less
- client/src/styles/_base.less
- package-lock.json
- resources/plugins/test/style.css
Earlier: no focus 
Now: 
Earlier: 
Now: 
Changes: 
Earlier: no focus 
Changes: 
Earlier: no focus 
Changes: 
Earlier: <img width="886" alt="image" src="https://github.com/user-attachments/assets/63c70928-95aa-44c7-8aff-3385e762614a">
Changes: 
Earlier: <img width="445" alt="image" src="https://github.com/user-attachments/assets/66a24fbd-19f1-4daf-9538-ecb5d176263e">
Changes: 
Earlier: grey background 
Changes: 
Earlier: no focus 
Changes: 
Closes https://github.com/camunda/camunda-modeler/issues/4632
Depends on https://github.com/bpmn-io/variable-outline/pull/6
Depends on https://github.com/bpmn-io/properties-panel/pull/390
> Focus indicators consistent

- client/src/plugins/version-info/ReleaseInfo.js
Related to #4753
For suggestions:
<ul className="dashed">
<li>
<h4>Element template runtime versions</h4>
Define the runtime version for each element template to ensure compatibility with the Camunda runtime.
</li>
<li>
<h4>Zeebe user task is now Camunda user task</h4>
Implement user tasks as Camunda user tasks to ensure full compatibility.
</li>
<li>
<h4>Improved FEEL support</h4>
Access script task result expression easily thanks to context keys suggestions.
</li>
<li>
<h4>Document preview component in Forms</h4>
Model and view uploaded documents in a new preview component.
</li>
<li>
<h4>Bug fixes and more</h4>
This release includes bug fixes and additional minor improvements to enhance your experience.
</li>
</ul>
> feat: update release info to v5.31.0

- .github/workflows/RELEASE.yml
Related to #4689
As a supplement to https://github.com/camunda/camunda-modeler/pull/4768, this automates the slack message sent to support.
This is how the message will look like when the PR is merged:
The message will be sent after the release (not RC) is built.
> ci: automate release notification

- .github/workflows/CI.yml
- client/src/app/EmptyTab.js
- client/src/app/TabsProvider.js
This adds the migration page link to the help menu so that it's always accessible:
It also adds `utm` tags to the empty page camunda docs links so that we can see whether users use them.
> Add migrate link to help menu

- client/src/app/drop-zone/DropHandler.js
- client/src/util/dom/dragger.js
This pull requests fixes two problems I found when resizing DRD preview:
1. When resizing, diagram drop zone would trigger occasionally and flash.
3. When resizing on macOS, the default (unloaded image) icon would show next to the cursor.
Before:
https://github.com/user-attachments/assets/716c9aa4-a0bc-492f-946d-95a41c3c9361
After:
https://github.com/user-attachments/assets/42816b13-b439-4903-a265-5aa49948d50b
> DRD overview resizing fix

- client/src/app/tabs/getEditMenu.js
Link to issue - #4756
Updated  the color map
> Fix: Wrong color used when applying from menu action #4756

- CHANGELOG.md
- client/package.json
- package-lock.json
deps: update to `@camunda/improved-canvas`
fix: suggest ad-hoc subprocess with new context pad
Closes #4813
> Suggest ad-hoc subprocess with new context pad

- CHANGELOG.md
- client/src/util/Engines.js
This adds Camunda 8.8 to the engines map. This allows to validate diagrams with Camunda 8.8 features, e.g. user task listeners.
> feat: support Camunda 8.8

- client/src/app/resizable-container/PropertiesPanelContainer.less
Closes https://github.com/camunda/camunda-modeler/issues/4834
Make text inside of a tooltip selectable.
> fix: make text in tooltip selectable

- .github/workflows/RELEASE.yml
Changelog link missed the opening (`<`) but it's now added.
The milestone part expects that there is only a single issue, so if merge this, I will change the labels of [the remaining `release` issues](https://github.com/camunda/camunda-modeler/issues?q=is%3Aissue%20state%3Aopen%20label%3Arelease) to `infrastructure`.
```
❯ gh api -H "Accept: application/vnd.github.v3+json" \
"/repos/camunda/camunda-modeler/issues?state=open&labels=release" \
--jq "[.[] | .milestone.title ][0]"
M86
```
Syntax for highlighting the user group: https://api.slack.com/reference/surfaces/formatting#mentioning-groups
Closes #4866
> Fix links in the release notice

- app/lib/zeebe-api/zeebe-api.js
- app/test/spec/zeebe-api/zeebe-api-spec.js
Closes #4871
Issue initially reported in https://camunda.slack.com/archives/C0693F1NFK5/p1740732406983989
Stage env https://ultrawombat.com/
Zeebe audience property was not setup and it was taking default property for audience. 
logs: 
Audience property can be set by `CAMUNDA_ZEEBE_OAUTH_AUDIENCE`.
logs: ![Screenshot 2025-03-04 at 22 51 16](https://github.com/user-attachments/assets/27be6877-0d0c-4ca1-b44b-0087c9dac707)
> camunda self managed oauth not connecting

- docs/.project/PATCH_RELEASE_TEMPLATE.md
Ensure the template is reasonably up to date with [RELEASE_TEMPLATE](https://github.com/camunda/camunda-modeler/blob/main/docs/.project/RELEASE_TEMPLATE.md), but also meaningful for the purpose at hand ("cut a patch release, quickly"):
* Removed need to check for vulnerabilities: This may introduce additional unwanted noise during a patch release, we want to ship these with maximum confidence, minimum uncertainty, and prevent any kind of unneeded noise.
* Ensure that it is clear that we usually don't update the release info (in modeler)
* Link Windows signing, mirroring https://github.com/camunda/camunda-modeler/pull/4880
* Fix dead link 
----
Identified when cutting the [v5.33.1 patch](https://github.com/camunda/camunda-modeler/issues/4881).
To ensure you provided everything we need to …
> docs(project): update PATCH_RELEASE_TEMPLATE

- .github/workflows/RELEASE_ISSUE.yml
This aims to fix the blowup from https://github.com/camunda/camunda-modeler/actions/runs/13674718309
Since no issue was created, JSON parser could not parse missing output. This caused the action to fail. 
With the change from this PR, the reassigned issue will be used instead.
> ci: handle release issue reassignment correctly

- client/package.json
- client/src/app/TabsProvider.js
- client/src/app/__tests__/EmptyTabSpec.js
- client/src/app/__tests__/TabsProviderSpec.js
- package-lock.json
This PR enables the RPA as default. It also bumps the RPA library to the latest version, which includes some minor fixes.
closes https://github.com/camunda/camunda-modeler/issues/4895
> chore: enable rpa by default

- client/src/plugins/process-applications/ResourcesProvider.js
- client/src/plugins/process-applications/__tests__/ResourcesProviderSpec.js
This makes sure that a file without metadata (case of broken files) can still be handled correctly by the resources provider. We ignore such files instead of crashing the application.
https://github.com/user-attachments/assets/97be214c-036f-43c7-9ed5-a1819330d8a8
Closes #4917
> fix: ignore files without metadata

- app/lib/index.js
- app/lib/preload.js
- client/src/plugins/process-applications/ProcessApplications.js
- client/src/plugins/process-applications/__tests__/ProcessApplicationsSpec.js
Closes https://github.com/camunda/camunda-modeler/issues/4915
Fixes two issues:
* indexer item not found when active tab changed and process applications feature is trying to find process application item
* root cause of the issue above: when closing a tab the item is removed from the file context even if it is part of a process application
A little more context:
The file context is a generic feature controlled by [App.js](https://github.com/camunda/camunda-modeler/blob/develop/client/src/app/App.js#L2092) when opening, saving or closing a tab. All tabs will be added to the file context regardless of whether they are part of a process application. The file context doesn't know about process applications, only about roots and items.
Example:
```
roots = [ …
```
> Fix file context file closed

- client/src/plugins/process-applications/ProcessApplications.js
- client/src/plugins/process-applications/__tests__/ProcessApplicationsSpec.js
* on both `activeTab-changed` and `items-changed`
* tab might not have a file (empty tab)
* file might not have path (unsaved tab)
* item might not be found
* we have account for that
Closes #4924
> fix(process-applications): handle unsaved tab

- client/src/app/notifications/Notification.less
- client/src/app/notifications/Notifications.less
Closes #4932
* makes sure notifications are always on top including modals
We don't really have a clear convention when it comes to `z-index` in the modeler but it appears that it is mostly 10^n so 10000 makes sure notifications are always on top.
> fix: notifications are always on top

- client/src/app/tabs/rpa/RPAEditor.js
- client/src/app/tabs/rpa/__tests__/RPAEditorSpec.js
Gracefully handle broken `JSON` in RPA editor
[screencap-2025-03-27-13-11-40.webm](https://github.com/user-attachments/assets/03ae3cc3-eb06-4cb1-80ad-5a7f906efcb2)
closes https://github.com/camunda/camunda-modeler/issues/4929
> fix(RPA): open fallback editor on invalid JSON

- .fossa.yml
- .github/workflows/CHECK_LICENSES.yml
Related to https://github.com/camunda/team-infrastructure/issues/751.
Add a new workflow to analyze licenses using FOSSA.
This workflow uploads only a dependency graph to FOSSA, the source code itself is not uploaded; The file-level scan of the dependencies is performed by the FOSSA platform asynchronously, making/keeping this workflow fast (execution time).
It currently analyzes licenses without enforcing any blocking checks and targets the main branch. Tag analysis will be added later, along with PR checks.
Configuration (`.fossa.yml`) has been set up to exclude `npm` projects in the `./resources` directory, focusing the scan on the top-level project and the `app` and `client` workspaces. This ensures that the same dependencies used to generate the licensing book (cf. `license-book.js`) …
> chore: new github workflow for license analysis with FOSSA

- client/src/plugins/process-applications/ProcessApplicationsPlugin.js
This fixes the link to process applications docs to point to Desktop Modeler documentation.
> fix: use Desktop Modeler docs link

- .github/workflows/COMMENT_DEVELOP_FIX.yml
This removes the peter-evans action from the workflow which should save us some time updating the action. We don't use the `update` section of the action anyway.
Solution based on https://docs.github.com/en/actions/use-cases-and-examples/project-management/commenting-on-an-issue-when-a-label-is-added
I used `fix` in the initial comment to test the new workflow in action.
> Use `gh` to comment on PR 

- electron-builder.json
- resources/platform/linux/support/mime-types.xml
- resources/platform/linux/support/xdg_register.sh
- resources/platform/win32/support/fileassoc.reg
Closes https://github.com/camunda/camunda-modeler/issues/4963
Add rpa file association for macOS, windows, and linux. For windows and linux the file association needs to be [rewired](https://docs.camunda.io/docs/components/modeler/desktop-modeler/install-the-modeler/#wire-file-associations) manually. On macOS a relaunch of finder should be enough and `.rpa` files should be linked with camunda modeler.
As I can only test it for macOS, someone with a matching OS please verify its working on others OSs:
> Add `.rpa` file association

- .github/workflows/BUILD_ON_DEMAND.yml
- .github/workflows/CI.yml
- .github/workflows/NIGHTLY.yml
- .github/workflows/RELEASE.yml
This makes sure that we use the same shell across the multi-platform jobs. We should not fall into Windows-specific problems this way.
Related to https://github.com/npm/cli/issues/7375
> ci: use bash as default shell

- CHANGELOG.md
- client/package.json
- package-lock.json
This PR updates camunda-bpmn-js to 5.9.0 which accounts for new message ref behavior in bpmn-js. In C8, we don't want to keep message ref in throw events as it's not supported, and cannot be removed via UI.
https://github.com/user-attachments/assets/da6239a5-6b77-4e4f-9ac7-c25b63f245fe
Closes #5003
> deps: update to `camunda-bpmn-js@5.9.0`

- client/src/plugins/zeebe-plugin/deployment-plugin/DeploymentPluginOverlay.js
- client/src/plugins/zeebe-plugin/deployment-plugin/__tests__/DeploymentPluginOverlaySpec.js
Closes https://github.com/camunda/camunda-modeler/issues/4992
Tenant ID field is available for basic auth:
> Make Tenant ID available for C8 self-managed deployment with basic auth

- client/src/plugins/settings/__tests__/useBuiltInSettingsSpec.js
- client/src/plugins/settings/useBuiltInSettings.js
Closes #5041
Use latest stable as the default version. No need to hard-code version number.
> Use latest stable as default engine version

- .fossa.yml
- .github/workflows/CHECK_LICENSES.yml
Related to https://github.com/camunda/team-infrastructure/issues/752.
This PR introduces a new job step in `CHECK_LICENSES.yml` workflow that runs only on pull requests, and checks for newly introduced license policy violations, such as those from new dependencies or updated versions:
- if license issues are found, they are listed in the logs with actionable links to the FOSSA dashboard and Confluence [page](https://confluence.camunda.com/spaces/HAN/pages/277024795/FOSSA#FOSSA-Handlelicenseissues)
- a job annotation is added for visibility, showing `License Check: X issues found. Please check the logs and resolve before merging`
- the step does not fail for pre-existing license issues in the base branch
The job waits for the FOSSA analysis to complete, which typically takes under a …
> chore(fossa): check PRs for newly introduced license issues

- .github/workflows/CHECK_LICENSES.yml
Related:
- https://camunda.slack.com/archives/C0693F1NFK5/p1748590218514959?thread_ts=1748446713.039439&cid=C0693F1NFK5
- https://github.com/camunda/infra-global-github-actions/pull/417
- https://github.com/camunda/team-infrastructure/issues/752
This PR enhances the robustness of FOSSA license violation checks on PRs.
> chore(fossa): compare PR scan against most recent base commit with available FOSSA scan

- app/util/get-version.js
- tasks/distro.js
- tasks/test-distro.js
Closes https://github.com/camunda/camunda-modeler/issues/3922
For dev builds, simply take current package version and add `-dev` to it without incrementing the minor part.
Skip lerna publish action for dev builds, which means no workspace changes after local build.
> chore: do not run lerna publish on dev build

- client/src/plugins/zeebe-plugin/deployment-plugin/DeploymentPluginOverlay.js
- client/src/plugins/zeebe-plugin/start-instance-plugin/StartInstancePluginOverlay.js
- client/src/plugins/zeebe-plugin/start-instance-plugin/__tests__/StartInstancePluginOverlaySpec.js
* remember entered deployment config locally
* go to deployment config form immediately if no valid deployment config
Closes #5083
Closes #5048
> Remember entered deployment config locally

- docs/.project/PATCH_RELEASE_TEMPLATE.md
- docs/.project/RELEASE_TEMPLATE.md
We don't need to additionally ensure that artifacts are signed. We will notice if they are not signed once we open the Modeler.
> chore: remove checkbox for Windows signing

- CHANGELOG.md
- client/src/app/Settings.js
- client/src/app/__tests__/SettingsSpec.js
The following changes are related to my findings when rewriting the auto-save plugin to use settings instead of a custom overlay.
Related to https://github.com/jarekdanielak/camunda-modeler-autosave-plugin/pull/1
Quality of life feature - no need to `get` the setting value right after registration. 
More gently handle a case when `Settings#get` is called with a key which doesn't exist.
> Settings: return values from `register` and handle non-existing key on `get`

- client/src/plugins/zeebe-plugin/deployment-plugin/ConnectionCheckErrors.js
Closes https://github.com/camunda/camunda-modeler/issues/5110
Related to https://github.com/camunda/camunda-docs/pull/6106
Renaming `zeebe` to `Orchestration cluster` in deployment tab. Links to docs did not change yet. 
> Rename `Zeebe` to 'Orchestration cluster'

- client/package.json
- client/src/index.js
- client/src/styles/_carbon.less
- client/src/styles/carbon.scss
- client/src/styles/style.less
- client/webpack.config.js
- package-lock.json
Drop the dependency on `sass` and simply import Carbon `styles.css`.
`_carbon.less` is where we can do our "Carbon theming" in the future.
> chore: import `@carbon/react` styles without `sass`

- app/lib/dialog.js
- app/lib/log/log.js
- app/test/spec/dialog-spec.js
- client/src/plugins/process-applications/ProcessApplicationsPlugin.js
- tsconfig.json
This PR addresses two issues identified in https://github.com/camunda/camunda-modeler/issues/4923 and https://github.com/camunda/camunda-modeler/issues/4928:
* saving the correct default path when creating a process application file
* we previously didn't account for the possibility of directory paths when setting the default path
* we would always `dirname` so if it's a directory path we'd accidentally set the parent directory path as the default path
Closes https://github.com/camunda/camunda-modeler/issues/4928
Related to https://github.com/camunda/camunda-modeler/issues/4923
> Improve file dialog when working with process applications

- CHANGELOG.md
- client/src/app/tabs/json/CodeMirror.js
- client/src/app/tabs/xml/CodeMirror.js
- client/src/shared/ui/form/JSONInput.js
This PR fixes the contrast issue by setting `monospace` as the font for code editors.
Closes #5140
Built on top of https://github.com/camunda/camunda-modeler/pull/5175 which needs to be merged first.
https://github.com/user-attachments/assets/a679c607-9796-4c6d-8dd1-4070013f1bed
> Use `monospace` font in code editors

- CHANGELOG.md
- client/package.json
- client/src/plugins/version-info/ReleaseInfo.js
- package-lock.json
Updating camunda/linting to revert inclusion of camunda feel builtins, also includes minor patch for priorityDefinition numbers.
I also removed camunda Builtins from the release notes
> Revert camundaBuiltins in linting

- app/lib/zeebe-api/zeebe-api.js
- app/test/spec/zeebe-api/zeebe-api-spec.js
Related to https://github.com/camunda/camunda-modeler/pull/5180
During testing of rest deployments I noticed missing port inference for grpcs
> fix: infer port 443 for grpcs endpoints

- client/src/app/EmptyTab.js
Related to https://github.com/camunda/camunda-modeler/pull/5236
adjust link to fixed version 8.8 (currently alpha) to prevent redirects to 8.9 (next alpha) once 8.8 gets stable 
https://docs.camunda.io/docs/8.8/guides/getting-started-agentic-orchestration/?utm_source=modeler&utm_medium=referral
redirects currently to next, but should be latest once its marked stable
Follow up: https://github.com/camunda/camunda-modeler/issues/5241 (adjust link to stable latest)
> fix: use fixed docs link

- client/src/app/panel/tabs/task-testing/TaskTestingApi.js
- client/src/app/panel/tabs/task-testing/TaskTestingTab.js
- client/src/app/panel/tabs/task-testing/hooks/useConnectionChecker.js
Related to [Slack discussion](https://camunda.slack.com/archives/GP70M0J6M/p1759158558147919).
Repetitive connection checking in task testing is causing unnecessary rerenders.
I extracted the connection checking logic out of the main component and made it only trigger a rerender if the connection result changed.
Additionally, I wrapped a bunch of callback functions into `useCallback` to prevent rerendering of ` <TaskTesting>`.
> Reduce number of rerenders cause by Task Testing
