camunda/camunda-modeler

- CHANGELOG.md
- app/lib/dialog.js
- app/lib/file-system.js
- app/lib/index.js
- app/lib/menu/menu-builder.js
- app/lib/util/renderer.js
- app/test/spec/dialog-spec.js
- client/lib/app/app.js
- client/lib/external/base-dialog.js
- client/lib/external/config.js
- client/lib/util/browser.js
- client/package-lock.json
- client/package.json
- client/test/helper/mock/dialog.js
- client/test/spec/app/app-spec.js
> 171 image export no multibutton

- app/lib/createDeployer.js
- app/lib/index.js
- app/test/.eslintrc
- app/test/helper/mock/fetch.js
- app/test/helper/mock/got.js
- app/test/spec/deploy-spec.js
- package-lock.json
- package.json
* smaller blue print
* based on whatwg-fetch standard
* :tada:
> chore(app): replace got with node-fetch

- .travis.yml
- package-lock.json
- package.json
- tasks/distro.js
> chore(distro): publish nightly builds to S3

- client/karma.config.js
- client/src/app/tabs/bpmn/BpmnEditor.js
- client/src/app/tabs/bpmn/__tests__/BpmnEditorSpec.js
- client/src/app/tabs/dmn/DmnEditor.js
- client/src/app/tabs/dmn/__tests__/DmnEditorSpec.js
- client/src/app/tabs/dmn/__tests__/diagram.dmn
- client/test/mocks/bpmn-js/Modeler.js
- client/test/mocks/dmn-js/Modeler.js
> Fix DMN endless loop

- client/karma.config.js
- client/src/app/App.js
- client/src/app/AppParent.js
- client/src/app/__tests__/AppSpec.js
- client/src/app/__tests__/mocks/index.js
- client/src/app/tabs/MultiSheetTab.js
- client/src/app/tabs/__tests__/MultiSheetTabSpec.js
- client/src/app/tabs/__tests__/mocks/index.js
- client/src/app/tabs/bpmn/BpmnEditor.js
- client/src/app/tabs/bpmn/__tests__/BpmnEditorSpec.js
- client/src/app/tabs/cmmn/CmmnEditor.js
- client/src/app/tabs/cmmn/__tests__/CmmnEditorSpec.js
- client/src/app/tabs/cmmn/__tests__/diagram.cmmn
- client/src/app/tabs/dmn/DmnEditor.js
- client/src/app/tabs/dmn/__tests__/DmnEditorSpec.js
- client/test/mocks/cmmn-js/Modeler.js
- client/test/mocks/dmn-js/Modeler.js
* handle import errors and warnings
* show errors and warnings in log
Closes #936
> feat(client): show errors and warnings in log

- client/src/app/tabs/MultiSheetTab.js
- client/src/app/tabs/__tests__/MultiSheetTabSpec.js
- client/src/app/tabs/__tests__/mocks/index.js
- client/src/app/tabs/bpmn/BpmnEditor.js
- client/src/app/tabs/bpmn/__tests__/BpmnEditorSpec.js
- client/src/app/tabs/cmmn/CmmnEditor.js
- client/src/app/tabs/cmmn/__tests__/CmmnEditorSpec.js
- client/src/app/tabs/dmn/DmnEditor.js
- client/src/app/tabs/dmn/__tests__/DmnEditorSpec.js
* MultiSheetTab opens fallback sheet on import error
Closes #945
> feat(client): open fallback sheet on import error

- app/lib/dialog.js
- app/lib/index.js
- app/test/spec/dialog-spec.js
- client/src/app/App.js
- client/src/app/__tests__/AppSpec.js
- client/src/app/__tests__/mocks/index.js
- client/src/app/tabs/MultiSheetTab.js
- client/src/app/tabs/__tests__/MultiSheetTabSpec.js
- client/src/app/tabs/__tests__/mocks/index.js
- client/src/remote/Dialog.js
* be able to open dialog from client
* be able to open external URL from client
* open error dialog on import error
Closes #937
> Restore import error dialog behavior

- app/dev.js
- app/package.json
- package-lock.json
This PR adds [React DevTools](https://github.com/facebook/react-devtools) in the dev mode, a very useful tool for React apps development.
> Add React DevTools for dev

- client/package-lock.json
- client/package.json
- client/src/app/App.js
- client/src/app/__tests__/AppSpec.js
- client/src/app/primitives/TabLinks.js
- client/src/app/primitives/Tabbed.less
- client/src/app/primitives/__tests__/TabLinksSpec.js
- client/src/app/primitives/__tests__/mocks/index.js
- client/src/app/util/dragger.js
- client/src/app/util/scroller.js
- package-lock.json
* select tabs through scrolling
* move tabs through dragging
Closes #895
> Restore scrolling / dragging

- app/lib/menu/menu-builder.js
- client/karma.config.js
- client/src/app/tabs/bpmn/BpmnEditor.js
- client/src/app/tabs/bpmn/__tests__/BpmnEditorSpec.js
- client/src/app/tabs/cmmn/CmmnEditor.js
- client/src/app/tabs/cmmn/__tests__/CmmnEditorSpec.js
- client/src/app/tabs/dmn/DmnEditor.js
- client/src/app/tabs/dmn/__tests__/DmnEditorSpec.js
- client/src/app/tabs/xml/XMLEditor.js
- client/src/app/tabs/xml/__tests__/XMLEditorSpec.js
- client/src/app/tabs/xml/__tests__/diagram.bpmn
- client/test/mocks/bpmn-js/Modeler.js
- client/test/mocks/cmmn-js/Modeler.js
- client/test/mocks/codemirror/Codemirror.js
- client/test/mocks/dmn-js/Modeler.js
* correctly configure file menu
* clean up updating state in editors
Closes #963
> Restore file menu behavior

- app/lib/dialog.js
- app/lib/index.js
- client/src/app/App.js
- client/src/app/__tests__/AppSpec.js
- client/src/app/tabs/MultiSheetTab.js
- client/src/app/tabs/bpmn/BpmnEditor.js
- client/src/app/tabs/bpmn/__tests__/BpmnEditorSpec.js
- client/src/app/tabs/bpmn/__tests__/activiti.bpmn
- client/src/app/tabs/bpmn/util/__tests__/activiti.bpmn
- client/src/app/tabs/bpmn/util/__tests__/namespaceSpec.js
- client/src/app/tabs/bpmn/util/namespace.js
- client/test/mocks/bpmn-js/Modeler.js
This pull request restores the convert namespace functionality. 
Closes #979
> 979 refactor convert namespace

- app/lib/dialog.js
- app/lib/file-system.js
- app/lib/index.js
- app/test/spec/dialog-spec.js
- app/test/spec/file-system-spec.js
- client/src/app/App.js
- client/src/app/TabsProvider.js
- client/src/app/__tests__/AppSpec.js
- client/src/app/__tests__/mocks/index.js
- client/src/app/tabs/__tests__/MultiSheetTabSpec.js
- client/src/app/tabs/bpmn/__tests__/BpmnEditorSpec.js
- client/src/remote/Dialog.js
- client/src/remote/FileSystem.js
- client/src/remote/__tests__/DialogSpec.js
- client/src/remote/__tests__/FileSystemSpec.js
* refactor app/lib/dialog.js
* refactor app/lib/file-system.js
* refactor use of Dialog and FileSystem in app/lib/index.js
* refactor client/src/remote/Dialog.js
* refactor client/src/remote/FileSystem.js
* refactor saving and exporting tabs in client/src/app/App.js
Closes #972 
Closes #974 
Closes #978
> Refactor file saving/exporting

- app/lib/menu/menu-builder.js
This PR fixes key bindings used to move canvas.
> Fix move canvas feature

- CHANGELOG.md
- app/lib/menu/menu-builder.js
- client/package-lock.json
- client/package.json
> Correct / Add key bindings for CMMN and DRD editor

- client/package-lock.json
- client/package.json
> feat(bpmn): allow editing of camunda:isStartableInTasklist

- client/src/app/App.js
- client/src/app/__tests__/AppSpec.js
This PR disables save callback for not dirty (=> disabled) save button.
Closes #1010
> fix(client/App): do not call save when save button is disabled

- package-lock.json
- package.json
* fixes accelerators not correctly being displayed
* potentially fixes other issues
> chore(project): bump to electron@3.10

- app/lib/dialog.js
- app/lib/file-system.js
- app/lib/index.js
- app/lib/util/renderer.js
- app/test/spec/dialog-spec.js
- app/test/spec/file-system-spec.js
- client/src/app/App.js
- client/src/app/TabsProvider.js
- client/src/app/__tests__/AppSpec.js
- client/src/app/__tests__/mocks/index.js
- client/src/remote/Backend.js
- client/src/remote/Dialog.js
- client/src/remote/FileSystem.js
- client/src/remote/__tests__/BackendSpec.js
- client/src/remote/__tests__/DialogSpec.js
- client/src/remote/__tests__/FileSystemSpec.js
- client/src/remote/__tests__/mocks/index.js
* whenever there is an error when trying to open/save a file a dialog is shown
* contains a couple of refactorings
Closes #977
> Refactor saving denied dialog

- app/lib/createDeployer.js
- app/test/spec/deploy-spec.js
> 744 deploy changed only

- app/lib/index.js
- app/lib/workspace.js
> chore(app/workspace): use fileSystem to read files

- CHANGELOG.md
- client/package-lock.json
- client/package.json
- Bump to current `camunda-bpmn-moddle` version, Closes #1074 
- Update changelog to version `v2.2.4`
> Bump camunda bpmn moddle

- client/src/app/App.js
- client/src/app/__tests__/AppSpec.js
- client/src/app/__tests__/mocks/index.js
- client/src/app/tabs/MultiSheetTab.js
- client/src/app/tabs/bpmn/BpmnEditor.js
- client/src/app/tabs/bpmn/__tests__/BpmnEditorSpec.js
- client/src/app/tabs/bpmn/modeler/BpmnModeler.js
- client/src/app/tabs/bpmn/modeler/features/apply-default-templates/__tests__/applyDefaultTemplatesSpec.js
- client/src/app/tabs/bpmn/modeler/features/apply-default-templates/applyDefaultTemplates.js
- client/src/app/tabs/bpmn/modeler/features/apply-default-templates/index.js
- client/src/index.js
- client/src/remote/Config.js
- client/src/remote/index.js
- client/test/mocks/bpmn-js/Modeler.js
This PR restores element templates feature.
Closes #1001
> Integrate element templates

- client/src/app/App.js
- client/src/app/AppParent.js
- client/src/app/EmptyTab.js
- client/src/app/__tests__/AppParentSpec.js
- client/src/app/__tests__/AppSpec.js
This PR adds window resize listener to resize active editor along with the window.
Closes #1082
> Make editor responsive

- client/src/app/tabs/bpmn/BpmnEditor.js
- client/src/app/tabs/bpmn/modeler/BpmnModeler.js
- client/src/app/tabs/bpmn/modeler/features/properties-panel-keyboard-bindings/PropertiesPanelKeyoardBindings.js
- client/src/app/tabs/bpmn/modeler/features/properties-panel-keyboard-bindings/__tests__/PropertiesPanelKeyboardBindingsSpec.js
- client/src/app/tabs/bpmn/modeler/features/properties-panel-keyboard-bindings/index.js
- client/src/app/tabs/cmmn/modeler/CmmnModeler.js
- client/src/app/tabs/dmn/DmnEditor.js
- client/src/app/tabs/dmn/__tests__/DmnModelerSpec.js
- client/src/app/tabs/dmn/modeler/DmnModeler.js
- client/src/app/tabs/dmn/modeler/index.js
* handle undo/redo/selectAll
Closes #1059 
Closes #1095
> feat(client): add properties panel keyboard bindings

- client/src/app/tabs/bpmn/BpmnEditor.js
- client/src/app/tabs/bpmn/__tests__/BpmnEditorSpec.js
- client/src/app/tabs/cmmn/CmmnEditor.js
- client/src/app/tabs/cmmn/__tests__/CmmnEditorSpec.js
- client/src/app/tabs/dmn/DmnEditor.js
- client/src/app/tabs/dmn/__tests__/DmnEditorSpec.js
- client/test/mocks/bpmn-js/Modeler.js
- client/test/mocks/cmmn-js/Modeler.js
- client/test/mocks/dmn-js/Modeler.js
* listen for focusin and focusout
* add tests to verify editor is listening for specific events
Closes #1105
> fix(client): listen for properties panel focus events

- client/package-lock.json
- client/package.json
- client/src/app/App.js
- client/src/app/__tests__/AppSpec.js
- client/src/app/primitives/TabLinks.js
- client/src/app/primitives/__tests__/TabLinksSpec.js
- client/src/app/util/dragger.js
- package-lock.json
> 1120 drag tabs update

- client/src/app/App.js
- client/src/util/dom/__tests__/draggerSpec.js
- client/src/util/dom/dragger.js
Fixes drag spikes by switching from `drag` to `dragover` event.
> Drag spikes

- client/package-lock.json
- client/package.json
- package-lock.json
> chore(client): update bpmn-js to v3.2.0

- app/lib/deployer.js
- app/test/spec/deployer-spec.js
> feat(deploy): set deployment-source to Camunda Modeler

- client/src/app/tabs/bpmn/BpmnEditor.js
- client/src/app/tabs/bpmn/__tests__/BpmnEditorSpec.js
- client/src/app/tabs/bpmn/getBpmnWindowMenu.js
- client/src/app/tabs/cmmn/CmmnEditor.js
- client/src/app/tabs/cmmn/__tests__/CmmnEditorSpec.js
- client/src/app/tabs/cmmn/getCmmnWindowMenu.js
- client/src/app/tabs/dmn/DmnEditor.js
- client/src/app/tabs/dmn/__tests__/DmnEditorSpec.js
- client/src/app/tabs/dmn/getDmnWindowMenu.js
> Repair window menu

- client/src/app/App.js
- client/src/app/AppParent.js
- client/src/app/__tests__/AppParentSpec.js
- client/src/app/__tests__/AppSpec.js
- client/src/app/__tests__/mocks/index.js
> feat(client): close all tabs before quitting the app

- client/src/app/App.js
- client/src/app/EmptyTab.js
- client/src/app/TabsProvider.js
- client/src/app/__tests__/EmptyTabSpec.js
- client/src/app/__tests__/TabsProviderSpec.js
- client/src/util/Flags.js
Builds upon https://github.com/camunda/camunda-modeler/pull/1169.
Closes #872
> 872 bpmn only

- client/src/app/tabs/bpmn/modeler/BpmnModeler.js
- client/src/app/tabs/cmmn/modeler/CmmnModeler.js
- client/src/app/tabs/dmn/modeler/DmnModeler.js
- client/src/app/tabs/shared/fix-origin/FixOrigin.js
- client/src/app/tabs/shared/fix-origin/index.js
- client/src/util/Flags.js
Builds upon https://github.com/camunda/camunda-modeler/pull/1169.
Closes #982
> Move to origin save

- app/dev.js
- app/lib/cli.js
- app/lib/client-config/providers/find-templates.js
- app/lib/config.js
- app/lib/file-system.js
- app/lib/flags.js
- app/lib/index.js
- app/lib/log/__test__/log-spec.js
- app/lib/log/index.js
- app/lib/log/log.js
- app/lib/log/transports/client.js
- app/lib/log/transports/console.js
- app/lib/log/transports/file.js
- app/lib/log/transports/index.js
- app/lib/menu/menu-builder.js
- app/lib/platform/mac-os/index.js
- app/lib/plugins.js
- app/lib/workspace.js
- app/package-lock.json
- app/package.json
- client/src/app/App.js
- client/src/app/AppParent.js
- client/src/index.js
- client/src/remote/Log.js
- client/src/remote/index.js
This PR adds log utility on backend which allows to log to console, log file as well as the client log. Also, client errors will be shown in the backend log and stored in a file.
Closes #1156
> Improve log

- app/lib/index.js
This allows us to extract the used app version from the logs.
> Log app name and version on start

- client/src/app/App.js
The result of the `Hour of Code` on February, 13th. It refactors the procedure of finding and eventually creating new tabs for given files out of the `App.js#openFiles` method to a standalone functionality.
- See[ code snippet](https://github.com/bpmn-io/hour-of-code/blob/master/snippets/App_openFiles.md) for more explanations.
> chore(client/App): outsource file-tab detection

- CHANGELOG.md
- app/lib/__tests__/cli-spec.js
- app/lib/cli.js
> Mac open error

- app/lib/menu/menu-builder.js
- app/lib/plugins.js
- app/test/spec/menu/menu-builder-spec.js
- app/test/spec/plugins-spec.js
- client/src/remote/__tests__/PluginsSpec.js
> fix(menu): only show Plugins menu on actual plug-ins

- app/package-lock.json
- package-lock.json
- package.json
<app> and <client> are separate projects,
we do not benefit from hoisting anyway.
Closes #1263
> chore(project): do not --hoist dependencies

- client/package-lock.json
Builds upon #1265 and [bumps front-end dependencies](https://github.com/camunda/camunda-modeler/commit/a03d9cf140c0b80a92d6b6b521663fcb7cb43ca0) to latest patch versions.
> Bump client deps

- client/src/app/App.js
- client/src/app/__tests__/AppSpec.js
> UPDATE UNSAVED :horse:

- client/src/app/tabs/bpmn/BpmnEditor.js
- client/src/app/tabs/bpmn/__tests__/BpmnEditorSpec.js
> Display error dialog when broken diagram is open

- client/src/app/tabs/cmmn/CmmnEditor.js
- client/src/app/tabs/cmmn/__tests__/CmmnEditorSpec.js
- client/src/app/tabs/dmn/DmnEditor.js
- client/src/app/tabs/dmn/__tests__/DmnEditorSpec.js
- client/test/mocks/dmn-js/Modeler.js
Applies refactor pattern from https://github.com/camunda/camunda-modeler/commit/7fae39cebffa952967ded9787966740440fa4646; fixes tests where needed.
> Refactor import handling

- package-lock.json
- package.json
Related https://github.com/camunda/eslint-plugin-camunda-licensed/issues/3.
> chore(project): update eslint-plugin-camunda-licensed

- client/src/app/tabs/bpmn/BpmnEditor.js
- client/src/app/tabs/cmmn/CmmnEditor.js
- client/src/app/tabs/cmmn/__tests__/CmmnEditorSpec.js
- client/src/app/tabs/dmn/DmnEditor.js
- client/src/app/tabs/dmn/__tests__/DmnEditorSpec.js
Errors will be allowed to bubble up.
> Refactor exportAs feature

- client/src/app/tabs/bpmn/BpmnEditor.js
- client/src/app/tabs/bpmn/__tests__/BpmnEditorSpec.js
- client/src/app/tabs/bpmn/__tests__/activiti.bpmn
- client/src/app/tabs/bpmn/__tests__/activitiConverted.bpmn
- client/src/app/tabs/bpmn/util/__tests__/fixtures/activiti-expected.xml
- client/src/app/tabs/bpmn/util/__tests__/fixtures/activiti.xml
- client/src/app/tabs/bpmn/util/__tests__/fixtures/activitiCamunda-expected.xml
- client/src/app/tabs/bpmn/util/__tests__/fixtures/activitiCamunda.xml
- client/src/app/tabs/bpmn/util/__tests__/fixtures/activitiComplex-expected.xml
- client/src/app/tabs/bpmn/util/__tests__/fixtures/activitiComplex.xml
- client/src/app/tabs/bpmn/util/__tests__/fixtures/diagram.bpmn
- client/src/app/tabs/bpmn/util/__tests__/fixtures/specialChars-expected.xml
- client/src/app/tabs/bpmn/util/__tests__/fixtures/specialChars.xml
- client/src/app/tabs/bpmn/util/__tests__/namespaceSpec.js
- client/src/app/tabs/bpmn/util/namespace.js
Builds upon https://github.com/camunda/camunda-modeler/pull/1227.
New namespace util will parse only definitions to look for namespace.
> Fix namespace util

- app/lib/dialog.js
- app/test/spec/dialog-spec.js
`Dialog#showDialog` was called with wrong arguments.
Closes #1301
> fix(app): call Dialog#showDialog with correct arguments

- app/lib/__tests__/cli-spec.js
- app/lib/cli.js
- app/lib/index.js
- client/src/app/App.js
- client/src/app/AppParent.js
- client/src/app/Log.js
- client/src/app/__tests__/AppParentSpec.js
- client/src/app/__tests__/AppSpec.js
- client/src/app/__tests__/LogSpec.js
- client/src/app/__tests__/mocks/index.js
- client/src/app/modals/keyboard-shortcuts/KeyboardShortcutsModal.js
- client/src/app/modals/keyboard-shortcuts/__tests__/KeyboardShortcutsModalSpec.js
- client/src/remote/Backend.js
- client/src/remote/Plugins.js
- client/src/util/Flags.js
- resources/plugins/test/index.js
- resources/plugins/test/menu.js
> 1253 toggle plugins

- CHANGELOG.md
> chore(CHANGELOG): update to v3.0.0-beta.3

- client/src/app/tabs/dmn/DmnEditor.js
- client/src/app/tabs/dmn/__tests__/DmnEditorSpec.js
> 1309 fix dmn sheet changes

- CHANGELOG.md
* filter out internal changes
* correct formating
> chore(CHANGELOG): simplify

- client/package-lock.json
- client/package.json
- client/src/app/__tests__/AppSpec.js
- client/src/app/__tests__/IntegrationSpec.js
- client/src/app/__tests__/mocks/index.js
- client/src/app/tabs/MultiSheetTab.js
- client/src/app/tabs/__tests__/MultiSheetTabSpec.js
> Fix Switching Tabs With Unsaved Changes

- app/package.json
- app/prod.js
> Ensure Production Mode in Distro

- client/src/app/App.js
- client/src/app/__tests__/IntegrationSpec.js
> fix(client/App): allow retrival of globals from modals

- app/lib/index.js
> fix(app): correct log usage

- app/lib/index.js
> fix(app): fix name conflict

- .github/CONTRIBUTING.md
> feat(project): add contributing guidlines

- client/package-lock.json
- client/package.json
Closes https://github.com/camunda/camunda-modeler/issues/1242
Closes https://github.com/camunda/camunda-modeler/issues/903
Closes https://github.com/camunda/camunda-modeler/issues/637
Closes https://github.com/camunda/camunda-modeler/issues/1290
Closes https://github.com/camunda/camunda-modeler/issues/609
Closes https://github.com/camunda/camunda-modeler/issues/608
Closes https://github.com/camunda/camunda-modeler/issues/1206
Closes https://github.com/camunda/camunda-modeler/issues/464
Closes https://github.com/camunda/camunda-modeler/issues/1019
Closes https://github.com/camunda/camunda-modeler/issues/239
> feat(client): bump to bpmn-js@4.0.0-beta.1

- CHANGELOG.md
Update changelog with `v3.2.0` changes.
Related to #1422
> chore(CHANGELOG): update to v3.2.0

- client/src/app/App.js
- client/src/app/modals/deploy-diagram/DeployDiagramModal.js
- client/src/app/modals/deploy-diagram/__tests__/DeployDiagramModalSpec.js
> Prefill deploy config

- client/package-lock.json
- client/package.json
Otherwise align-to-origin will accidentally un-align the whole diagram. Ooops.
> fix(client): use grid-aware align-to-origin util

- app/lib/index.js
- client/src/remote/Plugins.js
- client/src/remote/__tests__/PluginsSpec.js
- client/src/remote/index.js
This aligns the way we expose `metadata` to the client with other things we expose (plugins, flags).
> Unify exposing meta data

- client/src/app/tabs/bpmn/BpmnEditor.js
- client/src/app/tabs/bpmn/__tests__/BpmnEditorSpec.js
- client/src/app/tabs/cmmn/CmmnEditor.js
- client/src/app/tabs/cmmn/__tests__/CmmnEditorSpec.js
> fix(editors): fire state updates on search pad opened/closed

- client/src/app/KeyboardBindings.js
- client/src/app/__tests__/KeyboardBindingsSpec.js
- client/src/app/tabs/bpmn/modeler/BpmnModeler.js
- client/src/app/tabs/bpmn/modeler/features/hand-tool-on-space/HandToolOnSpace.js
- client/src/app/tabs/bpmn/modeler/features/hand-tool-on-space/index.js
- client/src/app/tabs/getEditMenu.js
> feat(client): activate hand tool on space

- client/public/index.html
- client/src/app/modals/deploy-diagram/__tests__/DeployDiagramModalSpec.js
- client/src/app/modals/keyboard-shortcuts/__tests__/KeyboardShortcutsModalSpec.js
- client/src/app/primitives/__tests__/ModalSpec.js
- client/src/app/primitives/modal/Modal.js
I noticed that implementing Modal the way that [React docs suggest](https://reactjs.org/docs/portals.html) causes a problem of not working `autoFocus`. This PR fixes the problem, at the same time avoiding also monkey-patching the browser behavior.
> Fix modal autofocus

- app/lib/menu/menu-builder.js
- client/src/app/tabs/getEditMenu.js
`visible` property wasn't set to created menu entries.
Closes #1487
> Fix Menu Entry Visibility

- CHANGELOG.md
- client/package-lock.json
- client/package.json
Closes #1436 
Closes #1502 
Closes #1507
> Bump to bpmn-js@5.0.5

- client/public/style.css
- client/src/app/App.js
- client/src/app/__tests__/AppSpec.js
- client/src/app/notifications/Notification.js
- client/src/app/notifications/Notification.less
- client/src/app/notifications/Notifications.js
- client/src/app/notifications/Notifications.less
- client/src/app/notifications/__tests__/NotificationSpec.js
- client/src/app/notifications/__tests__/NotificationsSpec.js
- client/src/app/notifications/index.js
- client/src/app/plugins/PluginsRoot.js
Adds notifications appearing in the center below the toolbar.
Closes #1505
> Add Notifications

- client/src/app/App.js
- client/src/app/__tests__/AppSpec.js
- client/src/app/tabs/MultiSheetTab.js
- client/src/app/tabs/__tests__/MultiSheetTabSpec.js
Requires https://github.com/camunda/camunda-modeler/pull/1506
> Close notifications when sheet or tab changes

- client/src/plugins/deployment-tool/CamundaAPI.js
- client/src/plugins/deployment-tool/DeploymentDetailsModal.js
- client/src/plugins/deployment-tool/DeploymentTool.js
- client/src/plugins/deployment-tool/errors/ConnectionError.js
- client/src/plugins/deployment-tool/errors/DeploymentError.js
- client/src/plugins/deployment-tool/errors/index.js
This PR adds readable errors to the deployment tool in case of failure.
Closes #1426
Requires https://github.com/camunda/camunda-modeler/pull/1491
> 1426 improve error message formatting

- app/lib/index.js
> Remove dead code

- client/src/plugins/deployment-tool/DeploymentDetailsModal.js
- client/src/plugins/deployment-tool/DeploymentDetailsModal.less
- client/src/plugins/deployment-tool/DeploymentTool.js
- client/src/plugins/deployment-tool/__tests__/DeploymentDetailsModalSpec.js
- client/src/plugins/deployment-tool/__tests__/DeploymentToolSpec.js
- client/src/plugins/deployment-tool/__tests__/validatorsSpec.js
- client/src/plugins/deployment-tool/validators.js
> Remember deployment details with diagram

- client/src/app/App.js
- client/src/app/__tests__/AppSpec.js
- client/src/app/tabs/bpmn/modeler/BpmnModeler.js
- client/src/app/tabs/bpmn/modeler/features/complete-direct-editing/CompleteDirectEditing.js
- client/src/app/tabs/bpmn/modeler/features/complete-direct-editing/__tests__/CompleteDirectEditingSpec.js
- client/src/app/tabs/bpmn/modeler/features/complete-direct-editing/index.js
- client/src/app/tabs/cmmn/modeler/CmmnModeler.js
- client/src/app/tabs/dmn/modeler/DmnModeler.js
Closes #1473 
* ensure changes made through direct editing are being saved when tab is saved
> Complete Editing on Save

- docs/.project/PATCH_RELEASE_CHECKLIST.md
- docs/.project/RELEASE_CHECKLIST.md
> chore(project): add patch release checklist

- CHANGELOG.md
> chore(CHANGELOG): update to v3.4.0

- CHANGELOG.md
> Patch release 3.4.1 CHANGELOG

- docs/.project/RELEASE_CHECKLIST.md
This PR updates the mail list inside the release checklist, it also puts writing blogpost element after publishing the actual release.
> Update release checklist

- client/package-lock.json
- client/package.json
> chore(client): bump camunda-bpmn-moddle version

- client/src/plugins/deployment-tool/DeploymentDetailsModal.js
> fix(deploy): correctly attach click listener

- app/lib/index.js
- app/lib/log/__test__/log-spec.js
- app/lib/log/log.js
- app/lib/log/transports/console.js
- app/lib/log/transports/file.js
> 1555 node integration feature toggle

- client/karma.config.js
- client/package-lock.json
- client/package.json
- client/webpack.config.js
This allows us to load SVGs that start with a Capital letter as React SVG components and use them in place of icon fonts.
```
client/resources/icons/ArrowUp.svg
client/app/OtherIcon.svg
client/app/SomeComponent.js
```
In `SomeComponent.js`
```javascript
import ArrowUpIcon from 'icons/ArrowUp.svg';
import OtherIcon from './OtherIcon.svg';
export default Component(props) {
return (
<>
<ArrowUpIcon />
<OtherIcon /> 
</>
);
}
```
The reason why I added `client/resources` as a search path is because I'd like to be able to provide SVG icons in a single place (i.e. `client/resources/icons`).
> Svg components

- client/package-lock.json
- client/package.json
Closes #1517
Closes #1540
Related to #1590
> chore(client): bump bpmn-js-properties-panel dependency

- app/lib/menu/menu-builder.js
- client/src/app/primitives/__tests__/ModalSpec.js
- client/src/app/primitives/modal/Modal.js
- client/src/plugins/privacy-preferences/PrivacyPreferences.js
- client/src/plugins/privacy-preferences/PrivacyPreferencesView.js
- client/src/plugins/privacy-preferences/PrivacyPreferencesView.less
- client/src/plugins/privacy-preferences/__tests__/PrivacyPreferencesSpec.js
- client/src/plugins/privacy-preferences/__tests__/PrivacyPreferencesViewSpec.js
- client/src/plugins/privacy-preferences/constants.js
- client/src/plugins/privacy-preferences/index.js
- client/src/util/Flags.js
Closes #1543
This PR does the same thing with #1586 however, @barmac and I decided that the App.js growing bigger as the new features are added is concerning so I re-implemented the same feature as a built-in plugin here.
> Privacy preferences settings plugin

- client/src/plugins/camunda-plugin/deployment-tool/DeploymentTool.js
- client/src/plugins/camunda-plugin/deployment-tool/__tests__/DeploymentToolSpec.js
> Deploy: Hide toolbar button if there is no active tab

- client/package-lock.json
- client/package.json
> chore(client): bump deps

- app/lib/index.js
- client/public/index.html
- client/src/index.js
This PR adds an indicator to Camunda Modeler titles for nightly builds.
Related to: #1419
> Distinguish nightly builds with title

- client/src/plugins/update-checks/UpdateChecks.js
> Update check logs

- app/lib/menu/menu-builder.js
- client/src/plugins/privacy-preferences/PrivacyPreferences.js
- client/src/plugins/update-checks/UpdateChecks.js
- client/src/plugins/update-checks/__tests__/UpdateChecksSpec.js
- client/src/util/Flags.js
> chore(app): rename disable-{server->remote}-interaction

- client/src/plugins/update-checks/NewVersionInfoView.less
- client/src/plugins/update-checks/UpdateChecks.js
- client/src/plugins/update-checks/UpdateChecksAPI.js
- client/src/plugins/update-checks/__tests__/UpdateChecksSpec.js
- client/src/util/Flags.js
This improves a few things before we ship it.
I've tested the update check interaction end to end. It worked for me.
> Minor update check adjustments

- client/src/plugins/camunda-plugin/start-instance-tool/StartInstanceTool.js
- client/src/plugins/camunda-plugin/start-instance-tool/__tests__/StartInstanceToolSpec.js
- client/src/plugins/camunda-plugin/start-instance-tool/util/__tests__/fixtures/collaboration_executable.bpmn
- client/src/plugins/camunda-plugin/start-instance-tool/util/__tests__/fixtures/collaboration_not_executable.bpmn
- client/src/plugins/camunda-plugin/start-instance-tool/util/__tests__/fixtures/executable.bpmn
- client/src/plugins/camunda-plugin/start-instance-tool/util/__tests__/fixtures/not_executable.bpmn
- client/src/plugins/camunda-plugin/start-instance-tool/util/__tests__/isExecutableSpec.js
- client/src/plugins/camunda-plugin/start-instance-tool/util/isExecutable.js
Closes #1671 
This checks whether an executable process is available in the diagram _before_ trying to deploy & run
**Changing Non Executable --> Executable**
**Changing Executable --> Non Executable**
> Check For Executable Before Deploy & Run

- client/package-lock.json
- client/package.json
- client/src/app/tabs/bpmn/BpmnEditor.js
- client/src/app/tabs/bpmn/getBpmnEditMenu.js
- client/src/app/tabs/dmn/DmnEditor.js
- client/src/app/tabs/dmn/__tests__/DmnEditorSpec.js
- client/src/app/tabs/dmn/getDmnEditMenu.js
- client/src/app/tabs/getEditMenu.js
> Update DRD editing to new diagram-js foundations

- client/src/plugins/camunda-plugin/deployment-tool/DeploymentConfigModal.js
- client/src/plugins/camunda-plugin/deployment-tool/DeploymentTool.js
- client/src/plugins/camunda-plugin/deployment-tool/__tests__/DeploymentConfigModalSpec.js
- client/src/plugins/camunda-plugin/deployment-tool/__tests__/DeploymentToolSpec.js
- client/src/plugins/camunda-plugin/start-instance-tool/StartInstanceTool.js
- client/src/plugins/camunda-plugin/start-instance-tool/__tests__/StartInstanceToolSpec.js
> Support spring boot per default

- client/src/app/tabs/dmn/DmnEditor.js
Broken in Electron@7 / Chrome 78.
Closes #1687
> fix(client/dmn): correct DMN editor scrolling

- CHANGELOG.md
Related to https://github.com/camunda/camunda-modeler/issues/1680
> chore(CHANGELOG): update to v3.7.0

- client/src/plugins/camunda-plugin/start-instance-tool/StartInstanceConfigModal.js
- package-lock.json
- package.json
> Update eslint-plugin-bpmn-io to v0.11.0

- app/lib/index.js
- app/lib/window-manager/__tests__/window-manager-spec.js
- app/lib/window-manager/index.js
- app/lib/window-manager/window-manager.js
> feat(app): save and restore window size

- client/src/plugins/camunda-plugin/deployment-tool/DeploymentConfigModal.js
- client/src/plugins/camunda-plugin/deployment-tool/__tests__/DeploymentConfigModalSpec.js
- client/src/plugins/camunda-plugin/deployment-tool/validation/DeploymentConfigValidator.js
- client/src/plugins/camunda-plugin/deployment-tool/validation/EndpointURLValidator.js
> Reset isCanceled flag on dialog open for EndpointURLValidator

- client/src/plugins/camunda-plugin/deployment-tool/__tests__/DeploymentConfigModalSpec.js
- client/src/plugins/camunda-plugin/deployment-tool/__tests__/DeploymentConfigValidatorSpec.js
4 of deployment-tool related tests fail only on Appveyor. This PR addresses this issue.
> Fix tests on Appveyor platform

- client/package-lock.json
- client/package.json
Closes https://github.com/camunda/camunda-modeler/issues/1759
> chore(client): update to bpmn-js@6.3.5

- app/lib/cli.js
- app/lib/file-system.js
- app/lib/index.js
- app/lib/menu/menu.js
- app/lib/util/ensure-opts.js
- app/lib/util/files.js
- app/lib/util/filter-extensions.js
- app/lib/util/require-platform.js
- app/util/get-version.js
- client/src/app/App.js
- client/src/app/KeyboardBindings.js
- client/src/app/__tests__/KeyboardBindingsSpec.js
- client/src/app/slot-fill/SlotFillRoot.js
- client/src/app/tabs/bpmn/modeler/features/properties-panel-keyboard-bindings/__tests__/PropertiesPanelKeyboardBindingsSpec.js
- client/src/app/tabs/util/namespace.js
- client/src/app/util/parseDiagramType.js
- client/src/remote/Dialog.js
- client/src/remote/FileSystem.js
- client/src/remote/Plugins.js
- resources/plugins/test-client/dist/client.js
- resources/plugins/test-editor-events/dist/client.js
* replace {Boolean} with {boolean}
* replace {Number} with {number}
* replace {String} with {string}
> chore(documentation): fix JSDoc types

- client/src/styles/_forms.less
> Fix tooltip implementation does not match the designs

- client/package-lock.json
- client/package.json
--> dmn-js@7.5.1
Closes #1769 
Related to #1781
> chore(client): bump dmn-js

- CHANGELOG.md
> chore(CHANGELOG): v3.7.3

- docs/plugins/README.md
> fix(camunda-plugin): clarify plugin files location

- CHANGELOG.md
> Add v4.0.0-alpha.3 to CHANGELOG

- .travis.yml
Switched from apt to snap as the package manager.
> fix(ci): correctly install hub for release draft

- client/src/plugins/privacy-preferences/__tests__/PrivacyPreferencesSpec.js
This contains refactoring done previously in https://github.com/camunda/camunda-modeler/pull/1819
Basically it's about adding //given/when/then structure and having a setup helper.
> test(privacy-preferences): refactor tests

- client/src/app/App.js
- client/src/app/__tests__/AppSpec.js
- client/src/app/primitives/__tests__/KeyboardInteractionTrapSpec.js
- client/src/app/primitives/modal/KeyboardInteractionTrap.js
- client/src/app/primitives/modal/Modal.js
- client/src/plugins/camunda-plugin/deployment-tool/DeploymentTool.js
- client/src/plugins/camunda-plugin/start-instance-tool/StartInstanceTool.js
> fix(client/plugins): add keyboard interaction trap to all plugin modals

- app/lib/index.js
- app/lib/util/__tests__/error-tracking-spec.js
- app/lib/util/error-tracking.js
- client/src/plugins/error-tracking/ErrorTracking.js
- client/src/plugins/error-tracking/__tests__/ErrorTrackingSpec.js
> Add plugins into sentry metadata

- client/src/app/tabs/dmn/modeler/DmnModeler.js
No tests this time, proper test coverage for all `DmnModeler` features will be added with #1811.
Closes #1685
> fix(client/dmn-modeler): actually fire properties panel events

- app/lib/index.js
- app/lib/menu/menu.js
Menu is initiated in the constructor and not per each window.
Closes #1816
> fix(app/menu): initiate only once

- client/src/plugins/error-tracking/ErrorTracking.js
- client/src/plugins/usage-statistics/UsageStatistics.js
- client/src/plugins/usage-statistics/__tests__/UsageStatisticsSpec.js
- client/src/plugins/usage-statistics/event-handlers/BaseEventHandler.js
- client/src/plugins/usage-statistics/event-handlers/DiagramOpenEventHandler.js
- client/src/plugins/usage-statistics/event-handlers/PingEventHandler.js
- client/src/plugins/usage-statistics/event-handlers/__tests__/BaseEventHandlerSpec.js
- client/src/plugins/usage-statistics/event-handlers/__tests__/DiagramOpenEventHandlerSpec.js
- client/src/plugins/usage-statistics/event-handlers/__tests__/PingEventHandlerSpec.js
- client/src/plugins/usage-statistics/event-handlers/index.js
- client/src/plugins/usage-statistics/index.js
- client/src/util/Flags.js
- client/webpack.config.js
👽  Closes #1805 👽 
To test this locally, use the `et-endpoint` flag after cloning the ET repo and running it locally. It'll be available on: `http://localhost:8080/pings`
> ET Integration

- app/lib/index.js
- client/src/plugins/error-tracking/ErrorTracking.js
- client/src/plugins/error-tracking/__tests__/ErrorTrackingSpec.js
> Join plugin names before sending to Sentry

- client/src/plugins/usage-statistics/UsageStatistics.js
- client/src/plugins/usage-statistics/event-handlers/BaseEventHandler.js
- client/src/plugins/usage-statistics/event-handlers/DiagramOpenEventHandler.js
- client/src/plugins/usage-statistics/event-handlers/__tests__/DiagramOpenEventHandlerSpec.js
> Add element templates to diagramOpened ET event payload

- client/src/plugins/update-checks/UpdateChecksAPI.js
- client/src/plugins/update-checks/__tests__/UpdateChecksSpec.js
- client/webpack.config.js
Related to https://github.com/camunda/camunda-modeler-update-server/issues/36
> Send product name to updates-server

- client/src/app/tabs/dmn/modeler/DmnModeler.js
- client/test/bpmn-io-modelers/dmn/DmnModelerSpec.js
> feat(dmn/modeler): set default zoom scale on overview import

- client/src/app/App.js
- client/src/app/AppParent.js
- client/src/app/__tests__/AppParentSpec.js
- client/src/app/__tests__/AppSpec.js
> Save workspace on quit

- client/package-lock.json
- client/package.json
This integrates the recent release of dmn-js. 
-----
Fixing upstream issues:
Closes https://github.com/camunda/camunda-modeler/issues/1763
Closes https://github.com/camunda/camunda-modeler/issues/1702
Closes https://github.com/camunda/camunda-modeler/issues/1817
> chore(client/dmn): bump to dmn-js@9.0.0

- CHANGELOG.md
> chore(CHANGELOG): update to v4.1.0

- client/src/app/tabs/dmn/modeler/DmnModeler.js
> Hide watermark for non-drd viewers

- client/src/app/TabsProvider.js
> Remove "DMN Table" option from applications menu

- client/src/app/tabs/dmn/DmnEditor.js
- client/src/app/tabs/dmn/__tests__/DmnEditorSpec.js
- client/src/app/tabs/dmn/getDmnWindowMenu.js
- client/test/mocks/dmn-js/Modeler.js
> feat(dmn-modeler): add shortcuts for overview

- CHANGELOG.md
> chore(CHANGELOG): update to v4.1.1

- client/src/plugins/update-checks/NewVersionInfoView.js
- client/src/plugins/update-checks/__tests__/NewVersionInfoViewSpec.js
> feat(update-check): focus download button per default

- client/src/app/tabs/PropertiesContainer.js
- client/src/app/tabs/__tests__/PropertiesContainerSpec.js
- client/src/app/tabs/dmn/OverviewContainer.js
- client/src/app/tabs/dmn/__tests__/OverviewContainerSpec.js
> fix(client): update layout once per properties panel resize

- .gitignore
- .travis.yml
- app/util/get-version.js
- package.json
- tasks/after-sign/notarize.js
- tasks/distro.js
- tasks/link-dependencies.js
- tasks/test-distro.js
> Build on demand

- client/src/app/tabs/dmn/__tests__/DmnEditorSpec.js
- client/src/app/tabs/dmn/getDmnEditMenu.js
> feat(dmn): remove clause and rule menu entries

- client/package-lock.json
- client/package.json
Closes #1892
Closes #1895
Closes #1898
Closes #1900
Closes #1906
Closes #1907
> chore(dmn): update to v9.2.0

- client/package-lock.json
- client/package.json
> Update dmn-js to 9.2.1

- app/lib/config/__tests__/config-spec.js
- app/lib/config/__tests__/fixtures/broken/config/config.json
- app/lib/config/providers/DefaultProvider.js
> fix(config): prevent throwing error for invalid config

- client/src/app/tabs/dmn/modeler/DmnModeler.js
- client/test/bpmn-io-modelers/dmn/DmnModelerSpec.js
> Prevent Align-To-Origin Module to Hook in When Updating Overview

- client/package-lock.json
- client/package.json
- client/src/plugins/element-templates-modal/modeler/PropertiesProvider.js
- client/src/plugins/element-templates-modal/modeler/__tests__/bpmn-io-modelers/PropertiesProviderSpec.js
Closes #1889
Closes #1891
Closes #1894
Closes https://github.com/bpmn-io/internal-docs/issues/121
> Element Template Tab

- client/package-lock.json
- client/package.json
- client/src/plugins/element-templates-modal/modeler/PropertiesProvider.js
- resources/element-templates/samples.json
Requires https://github.com/bpmn-io/bpmn-js-properties-panel/pull/370 to be merged, released and included in the Camunda Modeler.
Related to https://github.com/bpmn-io/bpmn-js-properties-panel/pull/370
> Use New Properties Panel API

- client/src/app/tabs/bpmn/BpmnEditor.js
- client/src/app/tabs/bpmn/__tests__/BpmnEditorSpec.js
- client/src/app/tabs/cmmn/CmmnEditor.js
- client/src/app/tabs/cmmn/__tests__/CmmnEditorSpec.js
- client/src/app/tabs/dmn/DmnEditor.js
- client/src/app/tabs/dmn/__tests__/DmnEditorSpec.js
> fix(tabs): unset lastXML on import error

- client/src/plugins/element-templates-modal/components/ElementTemplatesModalView.js
- client/src/plugins/element-templates-modal/components/__tests__/ElementTemplatesModalViewSpec.js
> fix(element-template-modal-spec): construct time str for local timezone

- README.md
Related to https://github.com/camunda/camunda-modeler/issues/1976#issuecomment-711949497
> docs(README): clarify environment to build app

- docs/README.md
> chore(docs): add telemetry to overview page

- client/package.json
- client/src/plugins/camunda-plugin/deployment-tool/DeploymentTool.js
- client/src/plugins/camunda-plugin/start-instance-tool/StartInstanceTool.js
- client/src/plugins/usage-statistics/event-handlers/DeploymentEventHandler.js
- client/src/plugins/usage-statistics/event-handlers/DiagramOpenEventHandler.js
- client/src/plugins/usage-statistics/event-handlers/__tests__/DeploymentEventHandlerSpec.js
- client/src/plugins/usage-statistics/event-handlers/__tests__/DiagramOpenEventHandlerSpec.js
- client/src/plugins/usage-statistics/event-handlers/__tests__/fixtures/process-variables.bpmn
- client/src/plugins/usage-statistics/event-handlers/index.js
- client/src/util/extractProcessVariables.js
- client/src/util/index.js
- docs/telemetry/README.md
Closes #1970 
Closes #1971
Further alignments of the `diagramOpened` event
_Note for the reviewer_: I decided to bundle those changes in one PR since they are dependant on each other and it makes sense to have them together. If the changes are too complex to review at once, we can definitely move some parts to separate PRs.
> Send Deployment Event to E.T. + align diagram open event

- client/src/app/KeyboardBindings.js
> chore: update <removeSelection> entry earlier

- CHANGELOG.md
Updates the CHANGELOG to v4.4.0
> chore(CHANGELOG): update to v4.4.0

- client/src/plugins/element-templates-modal/components/ElementTemplatesModalView.js
- client/src/plugins/element-templates-modal/components/__tests__/ElementTemplatesModalViewSpec.js
> feat(element-template-modal): add fallback for date

- CHANGELOG.md
- client/src/app/TabsProvider.js
- client/src/app/__tests__/TabsProviderSpec.js
- docs/flags/README.md
> feat(flags): set default value of disable-cmmn to true

- client/src/app/tabs/bpmn/modeler/features/apply-default-templates/__tests__/applyDefaultTemplatesSpec.js
> test(bpmn): remove getDefaultTemplate stub

- client/package-lock.json
- client/package.json
Closes https://github.com/camunda/camunda-modeler/issues/664
Closes https://github.com/camunda/camunda-modeler/issues/1229
Closes https://github.com/camunda/camunda-modeler/issues/2022
> deps: update to bpmn-js@8

- client/package-lock.json
- client/package.json
Closes https://github.com/camunda/camunda-modeler/issues/2019
> deps: update to dmn-js@10

- resources/element-templates/rpa.json
Related to https://github.com/camunda/camunda-modeler/issues/1969
Closes #2033
> chore: add template version examples

- docs/.project/INTEGRATION_TEST.md
Related to https://github.com/camunda/camunda-modeler/issues/1969
Closes #2035
> chore: add Cawemo integration test

- CHANGELOG.md
Related to https://github.com/camunda/camunda-modeler/issues/2013
> chore: update changelog to v4.5.0

- client/package-lock.json
- client/package.json
> Update properties panel

- client/karma.config.js
- client/package-lock.json
- client/package.json
- dev.js
- package-lock.json
- package.json
The fix is applied via replacement of webpack-dev-server
with electron-reload.
Closes #2060
Closes #
> fix: reload client on cold start in dev mode

- client/package-lock.json
- client/package.json
Adds extraction of event definition variables.
> chore: bump @bpmn-io/extract-process-variables

- docs/telemetry/README.md
Along the lines of https://github.com/camunda/camunda-modeler/commit/1394581250e1e28226b8f8c9d5cea3bcbac08655
> chore(docs): correct formKey telemetry metrics doc

- app/lib/index.js
- client/src/plugins/error-tracking/ErrorTracking.js
- client/src/plugins/error-tracking/__tests__/ErrorTrackingSpec.js
> feat: set empty plugins tag to `none`

- client/src/plugins/camunda-plugin/deployment-tool/DeploymentConfigModal.js
- client/src/plugins/camunda-plugin/deployment-tool/DeploymentTool.js
- client/src/plugins/camunda-plugin/deployment-tool/__tests__/DeploymentConfigModalSpec.js
- client/src/plugins/camunda-plugin/deployment-tool/__tests__/DeploymentToolSpec.js
> fix(camunda-plugin): do not update credentials on non existing endpoints

- docs/element-templates/README.md
- resources/element-templates/samples.json
Related to #2083 
Closes #2008
> Add json schema to samples

- client/src/plugins/element-templates-modal/components/ElementTemplatesModalView.js
- client/src/plugins/element-templates-modal/components/__tests__/ElementTemplatesModalViewSpec.js
> fix(element-templates-modal): filter invalid templates

- README.md
Closes https://github.com/bpmn-io/internal-docs/issues/196
> chore(README): link to camunda Code of Conduct

- client/src/plugins/element-templates-modal/modeler/EditorActions.js
- client/src/plugins/element-templates-modal/modeler/__tests__/bpmn-io-modelers/EditorActionsSpec.js
- client/src/plugins/element-templates-modal/modeler/__tests__/bpmn-io-modelers/collaboration.bpmn
> fix(element-template-modal): support bpmn:Process and Collaboration

- client/package-lock.json
- client/package.json
> chore: bump camunda-bpmn-js

- client/package-lock.json
- client/package.json
- client/src/app/tabs/bpmn/diagram.bpmn
- client/src/plugins/usage-statistics/event-handlers/DeploymentEventHandler.js
- client/src/plugins/usage-statistics/event-handlers/DiagramOpenEventHandler.js
- client/src/plugins/usage-statistics/event-handlers/__tests__/DeploymentEventHandlerSpec.js
- client/src/plugins/usage-statistics/event-handlers/__tests__/DiagramOpenEventHandlerSpec.js
- client/src/plugins/usage-statistics/event-handlers/__tests__/fixtures/engine-profile.bpmn
- client/src/plugins/usage-statistics/event-handlers/__tests__/fixtures/user-tasks-with-participants.zeebe.bpmn
- client/src/plugins/usage-statistics/event-handlers/__tests__/fixtures/user-tasks-with-subprocess.zeebe.bpmn
- client/src/plugins/usage-statistics/event-handlers/__tests__/fixtures/user-tasks.zeebe.bpmn
- client/src/plugins/zeebe-plugin/deployment-plugin/DeploymentPlugin.js
- client/src/plugins/zeebe-plugin/deployment-plugin/__tests__/DeploymentPluginSpec.js
- client/src/util/formHelpers.js
- client/src/util/index.js
- client/src/util/metrics/index.js
- client/src/util/metrics/processVariables.js
- client/src/util/metrics/userTasks.js
- client/src/util/parse.js
- docs/telemetry/README.md
Closes #2115 
For example events refer to https://github.com/camunda/camunda-modeler/pull/2123#issuecomment-788034342.
> Handle open, deploy & run of Zeebe diagrams on usage statistics

- client/src/app/EmptyTab.js
- client/src/app/EmptyTab.less
- client/src/app/TabsProvider.js
- client/src/app/__tests__/AppSpec.js
- client/src/app/__tests__/EmptyTabSpec.js
- client/src/app/tabs/cloud-bpmn/BpmnTab.js
- client/src/app/tabs/dmn/DmnTab.js
- client/src/plugins/camunda-plugin/deployment-tool/DeploymentConfigModal.js
- client/src/plugins/camunda-plugin/start-instance-tool/StartInstanceConfigModal.js
- client/src/plugins/camunda-plugin/start-instance-tool/StartInstanceTool.js
- client/src/plugins/zeebe-plugin/deployment-plugin/DeploymentPluginConstants.js
> feat: add Zeebe tab button for empty tab

- client/src/app/tabs/bpmn/BpmnTab.js
> chore: rename diagram label for Camunda Engine tab

- client/package-lock.json
- client/package.json
- client/src/plugins/camunda-plugin/deployment-tool/__tests__/DeploymentConfigModalSpec.js
Fixes test connection timeouts on Linux.
> Bump puppeteer

- client/karma.config.js
- client/src/app/App.js
- client/src/app/EmptyTab.js
- client/src/app/TabsProvider.js
- client/src/app/__tests__/EmptyTabSpec.js
- client/src/app/__tests__/TabsProviderSpec.js
- client/src/app/tabs/form/FormTab.js
- client/src/app/tabs/form/Menu.js
- client/src/app/tabs/form/index.js
- client/src/app/tabs/form/initial.form
- client/src/app/tabs/json/CodeMirror.js
- client/src/app/tabs/json/JSONEditor.js
- client/src/app/tabs/json/JSONEditor.less
- client/src/app/tabs/json/Menu.js
- client/src/app/tabs/json/__tests__/JSONEditorSpec.js
- client/src/app/tabs/json/index.js
- client/src/util/Flags.js
- client/webpack.config.js
- electron-builder.json
- resources/diagram/simple.form
- resources/platform/linux/support/mime-types.xml
- resources/platform/linux/support/xdg_register.sh
__Compatibility Checklist__
---
Try it out via 
```
npx @bpmn-io/sr camunda/camunda-modeler#form-integration
```
---
Some screenshots:
---
Closes https://github.com/camunda/camunda-modeler/issues/2149
> Form integration

- client/src/app/tabs/form/initial.form
+ no buttons for now, as these are added by Camunda Apps
+ default component with type
Closes https://github.com/camunda/camunda-modeler/issues/2164
> fix: correct initial form

- app/lib/file-system.js
- client/src/plugins/camunda-plugin/CamundaPlugin.js
- client/src/plugins/camunda-plugin/deployment-tool/DeploymentConfigModal.js
- client/src/plugins/camunda-plugin/deployment-tool/DeploymentTool.js
- client/src/plugins/camunda-plugin/deployment-tool/__tests__/DeploymentConfigModalSpec.js
- client/src/plugins/camunda-plugin/deployment-tool/__tests__/DeploymentConfigValidatorSpec.js
- client/src/plugins/camunda-plugin/deployment-tool/__tests__/DeploymentToolSpec.js
- client/src/plugins/camunda-plugin/deployment-tool/validation/DeploymentConfigValidator.js
- client/src/plugins/camunda-plugin/shared/CamundaAPI.js
- client/src/plugins/camunda-plugin/shared/__tests__/CamundaAPISpec.js
- client/src/plugins/camunda-plugin/start-instance-tool/StartInstanceTool.js
- client/src/plugins/camunda-plugin/start-instance-tool/__tests__/mocks/index.js
- client/src/shared/ui/form/FileInput.js
- client/src/shared/ui/form/__tests__/FileInputSpec.js
- client/src/shared/ui/form/index.js
- client/src/styles/_forms.less
> Multi-file deployment

- client/src/app/TabsProvider.js
Try to open file with higher prioritized providers first
Closes #2158
----
Note: I investigated whether it would be possible to create a `before` /  `after` for the menu items like [Electron is already supporting it](https://www.electronjs.org/docs/api/menu-item). This way we could define that, as an example, the Cloud BPMN menu entries will be rendered after the BPMN in any case.
That would work fine (and out of the box) for the `getNewFileMenu` methods of the providers. However, for the `getNewFileButton` we would need to implement [a similar logic](https://github.com/electron/electron/blob/master/lib/browser/api/menu-utils.ts#L96) on our own for the `DropdownButton`. I gave it a chance in a time-boxed manner and did not end up with a reasonable solution. 
That's why I decided to move …
> fix(tabs-provider): introduce provider priorities

- client/src/util/formHelpers.js
Related to bpmn-io/bpmn-js-properties-panel#447
> Align extension elements helper function

- client/package-lock.json
- client/package.json
Closes https://github.com/camunda/camunda-modeler/issues/2166
> deps(client): bump to camunda-bpmn-js@0.5.0-0

- client/src/app/App.js
- client/src/app/Log.js
- client/src/app/TabsProvider.js
- client/src/app/__tests__/LogSpec.js
- client/src/app/status-bar/StatusBar.js
- client/src/app/status-bar/StatusBar.less
- client/src/app/status-bar/__tests__/StatusBarSpec.js
- client/src/app/status-bar/index.js
- client/src/app/tabs/MultiSheetTab.js
- client/src/app/tabs/__tests__/MultiSheetTabSpec.js
- client/src/styles/_status-bar.less
- client/src/styles/style.less
> Status bar initial implementation

- client/src/plugins/usage-statistics/event-handlers/__tests__/DeploymentEventHandlerSpec.js
- client/src/plugins/usage-statistics/event-handlers/__tests__/DiagramOpenEventHandlerSpec.js
- client/src/plugins/usage-statistics/event-handlers/__tests__/fixtures/user-tasks-with-participants.bpmn
- client/src/plugins/usage-statistics/event-handlers/__tests__/fixtures/user-tasks-with-subprocess.bpmn
- client/src/plugins/usage-statistics/event-handlers/__tests__/fixtures/user-tasks.bpmn
- client/src/util/metrics/userTasks.js
- docs/telemetry/README.md
> feat(usage-statistics): track camunda forms on platform diagrams

- client/package-lock.json
- client/package.json
Integrates https://github.com/bpmn-io/form-js/pull/43.
Related to https://github.com/bpmn-io/form-js/pull/43.
> chore(client): update @bpmn-io/form-js dependency

- client/resources/icons/LinkArrow.svg
- client/src/app/status-bar/StatusBar.less
- client/src/app/tabs/EngineProfile.js
- client/src/app/tabs/EngineProfile.less
- client/src/app/tabs/MultiSheetTab.js
- client/src/app/tabs/__tests__/EngineProfileSpec.js
- client/src/shared/ui/__tests__/OverlaySpec.js
- client/src/shared/ui/overlay/GlobalClickListener.js
- client/src/shared/ui/overlay/Overlay.js
- client/src/shared/ui/overlay/Overlay.less
- client/src/shared/ui/overlay/index.js
- client/src/styles/_colors.less
- client/src/styles/_overlay.less
- client/src/styles/style.less
> Engine profile overlay

- CHANGELOG.md
> chore(CHANGELOG): update to v4.7.0

- client/package-lock.json
- client/package.json
- client/src/app/tabs/form/FormEditor.js
- client/test/mocks/form-js/index.js
Fixes drag and drop interaction in the form editor and allows drop across full height.
Preview:
Requires https://github.com/bpmn-io/form-js/pull/51 to be integrated.
Closes #2197
> fix(client): form editor emits attach and detach events

- app/package-lock.json
- client/package-lock.json
- package-lock.json
> chore: fix security audit issues

- client/package-lock.json
- client/package.json
Closes https://github.com/camunda/camunda-modeler/issues/2042
> deps(client): bump to dmn-js@10.2.0

- client/src/app/TabsProvider.js
- client/src/app/__tests__/TabsProviderSpec.js
- resources/diagram/zeebe-camunda-mixed.bpmn
- resources/diagram/zeebe.bpmn
Closes https://github.com/camunda/camunda-modeler/issues/2212
> fix(client): correctly filter out Zeebe provider if disabled

- client/src/plugins/update-checks/UpdateChecks.js
- client/src/plugins/update-checks/__tests__/UpdateChecksSpec.js
Displays update check errors inside the Log View and via Notification (if actively triggered).
Closes #2086
---
I decided to do it the same as we handle deployment errors: display the error in the Log View instead of the Notification contents. Errors thrown by the Update Server can differ in the number of details they reveal.
> feat(update-checks): display errors

- client/package-lock.json
- client/package.json
- client/src/app/EmptyTab.js
- client/src/app/TabsProvider.js
- client/src/app/__tests__/EmptyTabSpec.js
- client/src/app/__tests__/TabsProviderSpec.js
- client/src/app/tabs/cloud-bpmn/modeler/BpmnModeler.js
- client/src/util/Flags.js
- docs/flags/README.md
This enables Camunda Cloud tab together with User Task. 
Closes #2210
> feat: enable Camunda Cloud tab per default

- NOTICE
> chore: add form-js to NOTICE

- client/src/plugins/usage-statistics/event-handlers/__tests__/DeploymentEventHandlerSpec.js
- client/src/plugins/usage-statistics/event-handlers/__tests__/DiagramOpenEventHandlerSpec.js
- client/src/plugins/usage-statistics/event-handlers/__tests__/fixtures/service-tasks-with-participants.bpmn
- client/src/plugins/usage-statistics/event-handlers/__tests__/fixtures/service-tasks-with-participants.zeebe.bpmn
- client/src/plugins/usage-statistics/event-handlers/__tests__/fixtures/service-tasks-with-subprocess.bpmn
- client/src/plugins/usage-statistics/event-handlers/__tests__/fixtures/service-tasks-with-subprocess.zeebe.bpmn
- client/src/plugins/usage-statistics/event-handlers/__tests__/fixtures/service-tasks.bpmn
- client/src/plugins/usage-statistics/event-handlers/__tests__/fixtures/service-tasks.zeebe.bpmn
- client/src/util/extensionElementsHelpers.js
- client/src/util/formHelpers.js
- client/src/util/metrics/index.js
- client/src/util/metrics/serviceTasks.js
> Track serviceTask metrics

- docs/telemetry/README.md
> docs(telemetry): document serviceTask tracking

- client/src/plugins/camunda-plugin/deployment-tool/DeploymentTool.js
- client/src/plugins/camunda-plugin/deployment-tool/__tests__/DeploymentToolSpec.js
- client/src/plugins/camunda-plugin/shared/CamundaAPI.js
- client/src/plugins/camunda-plugin/shared/__tests__/CamundaAPISpec.js
- client/src/plugins/camunda-plugin/start-instance-tool/StartInstanceTool.js
- client/src/plugins/camunda-plugin/start-instance-tool/__tests__/StartInstanceToolSpec.js
- client/src/plugins/camunda-plugin/start-instance-tool/__tests__/mocks/index.js
- client/src/plugins/usage-statistics/event-handlers/DeploymentEventHandler.js
- client/src/plugins/usage-statistics/event-handlers/__tests__/DeploymentEventHandlerSpec.js
related to #2219
* Seperate PR for zeebe will follow
* Seperate PR for docs will follow
> 2219 track engine version

- .github/workflows/BUILD_ON_DEMAND.yml
- .travis.yml
- tasks/distro.js
GitHub Actions are faster than Travis ⏲️
> feat: move build-on-demand to GitHub Actions

- app/lib/zeebe-api.js
- app/package-lock.json
- app/package.json
- app/test/spec/zeebe-api-spec.js
- client/src/plugins/zeebe-plugin/deployment-plugin/DeploymentPluginConstants.js
- client/src/plugins/zeebe-plugin/deployment-plugin/DeploymentPluginModal.js
> Migrate to Zeebe 1.0.0 API

- client/src/app/tabs/EngineProfile.js
> feat: include Camunda Cloud in the forms engine profile

- app/lib/index.js
- app/lib/preload.js
- app/lib/zeebe-api.js
- app/test/spec/zeebe-api-spec.js
- client/src/plugins/camunda-plugin/deployment-tool/DeploymentTool.js
- client/src/plugins/camunda-plugin/deployment-tool/__tests__/DeploymentToolSpec.js
- client/src/plugins/camunda-plugin/start-instance-tool/StartInstanceTool.js
- client/src/plugins/camunda-plugin/start-instance-tool/__tests__/StartInstanceToolSpec.js
- client/src/plugins/zeebe-plugin/deployment-plugin/DeploymentPlugin.js
- client/src/plugins/zeebe-plugin/deployment-plugin/__tests__/DeploymentPluginSpec.js
- client/src/remote/ZeebeAPI.js
- client/src/remote/__tests__/ZeebeAPISpec.js
- docs/telemetry/README.md
> 2219 fetch zeebe broker version for et

- client/src/plugins/usage-statistics/event-handlers/DeploymentEventHandler.js
- client/src/plugins/usage-statistics/event-handlers/__tests__/DeploymentEventHandlerSpec.js
- client/src/plugins/usage-statistics/event-handlers/__tests__/fixtures/empty.dmn
- client/src/util/metrics/processVariables.js
- client/src/util/parse.js
> fix(telemetry): don't parse executionPlatform profile for dmn

- client/src/app/EmptyTab.js
- client/src/app/TabsProvider.js
- client/src/app/__tests__/EmptyTabSpec.js
- client/src/app/tabs/EngineProfile.js
- client/src/app/tabs/__tests__/EngineProfileSpec.js
- client/src/app/tabs/__tests__/MultiSheetTabSpec.js
- client/src/app/tabs/bpmn/BpmnTab.js
- client/src/app/tabs/bpmn/diagram.bpmn
- client/src/app/tabs/cloud-bpmn/BpmnTab.js
- client/src/app/tabs/dmn/DmnTab.js
- client/src/plugins/camunda-plugin/deployment-tool/DeploymentConfigModal.js
- client/src/plugins/camunda-plugin/deployment-tool/__tests__/DeploymentConfigValidatorSpec.js
- client/src/plugins/camunda-plugin/deployment-tool/validation/EndpointURLValidator.js
- client/src/plugins/camunda-plugin/shared/CamundaAPI.js
- docs/telemetry/README.md
* The Modeler UI should reflect the Camunda Product strategy.
* The core products are: Camunda Platform and Camunda Cloud.
* Rather than using the technical engine names, we use these product
names now consistently on the UI.
> Prepare 4.8 release

- CHANGELOG.md
Related to https://github.com/camunda/camunda-modeler/issues/2221.
> chore(CHANGELOG): update to v4.8

- client/src/plugins/camunda-plugin/CamundaPlugin.js
- client/src/plugins/camunda-plugin/__tests__/CamundaPluginSpec.js
> Expose getVersion to start instance plugin

- docs/.project/INTEGRATION_TEST.md
> chore(project): extend integration test with validation that flags work

- CHANGELOG.md
Related to https://github.com/camunda/camunda-modeler/issues/2261.
> chore(CHANGELOG): update to v4.8.1

- .github/workflows/BUILD_ON_DEMAND.yml
- .github/workflows/CI.yml
- .github/workflows/NIGHTLY.yml
- .travis.yml
- tasks/distro.js
This migrates CI and nightly jobs to GitHub Actions. Next step will be to migrate the release jobs.
> Migrate to GitHub actions (1/2)

- README.md
Related to https://github.com/camunda/camunda-modeler/issues/2269.
Closes #2274.
> docs: document necessary tools to run development setup

- client/src/app/tabs/PropertiesContainer.js
- client/src/app/tabs/__tests__/PropertiesContainerSpec.js
- client/src/app/tabs/bpmn/BpmnEditor.js
- client/src/app/tabs/bpmn/__tests__/BpmnEditorSpec.js
- client/src/app/tabs/cloud-bpmn/BpmnEditor.js
- client/src/app/tabs/cloud-bpmn/__tests__/BpmnEditorSpec.js
- client/src/app/tabs/dmn/DmnEditor.js
- client/src/app/tabs/dmn/__tests__/DmnEditorSpec.js
BPMN and DMN properties panel will always fall back to default layout.
Closes #2252
> Allways Fall Back to Default Properties Panel Layout

- tasks/link-dependencies.js
Works on my machine.
Related to https://github.com/bpmn-io/build-on-demand/issues/14.
> Add Support For Linking @bpmn-io/form-js When Linking Dependencies

- client/src/app/tabs/MultiSheetTab.js
- client/src/app/tabs/__tests__/MultiSheetTabSpec.js
> fix(forms): show fallback editor for invalid files

- client/src/app/App.js
Closes #2293
* Adds a new welcome tab:
> fix(app): remove + button to avoid ambiguous behavior

- app/lib/index.js
- app/lib/menu/menu-builder.js
- client/src/app/status-bar/StatusBar.less
- client/src/plugins/index.js
- client/src/plugins/version-info/VersionInfo.js
- client/src/plugins/version-info/VersionInfo.less
- client/src/plugins/version-info/VersionInfoOverlay.js
- client/src/plugins/version-info/VersionInfoOverlay.less
- client/src/plugins/version-info/__tests__/VersionInfoOverlaySpec.js
- client/src/plugins/version-info/__tests__/VersionInfoSpec.js
- client/src/plugins/version-info/index.js
- client/src/shared/ui/__tests__/OverlaySpec.js
- client/src/shared/ui/overlay/Overlay.js
- client/src/shared/ui/overlay/Overlay.less
Related to https://github.com/camunda/camunda-modeler/issues/2303
This includes the visual part of the "What's New" overlay. Usage tracking will be included in a second PR.
> What's New (1/2)

- client/package-lock.json
- client/package.json
> deps: update to `dmn-js@10.3.0`

- client/src/plugins/version-info/ReleaseInfo.js
- client/src/plugins/version-info/ReleaseInfo.less
> Improve release info (style <ol> and add doc)

- CHANGELOG.md
- client/package-lock.json
- client/package.json
> deps: update to `bpmn-js@8.7.1`

- client/src/app/App.js
- client/src/app/__tests__/AppSpec.js
- client/src/app/tabs/EngineProfile.less
- client/src/plugins/camunda-plugin/deployment-tool/DeploymentTool.js
- client/src/plugins/camunda-plugin/deployment-tool/__tests__/DeploymentToolSpec.js
- client/src/plugins/camunda-plugin/start-instance-tool/StartInstanceTool.js
- client/src/plugins/version-info/VersionInfoOverlay.less
- client/src/plugins/zeebe-plugin/deployment-plugin/DeploymentPlugin.js
- client/src/plugins/zeebe-plugin/deployment-plugin/__tests__/DeploymentPluginSpec.js
- client/src/plugins/zeebe-plugin/start-instance-plugin/StartInstancePlugin.js
- client/src/plugins/zeebe-plugin/start-instance-plugin/__tests__/StartInstancePluginSpec.js
- client/src/shared/ui/__tests__/OverlayDropdownSpec.js
- client/src/shared/ui/index.js
- client/src/shared/ui/overlay/Overlay.less
- client/src/shared/ui/overlay/OverlayDropdown.js
- client/src/shared/ui/overlay/OverlayDropdown.less
- client/src/shared/ui/overlay/index.js
- client/src/styles/_base.less
- client/src/styles/_overlay.less
This implements basic concept for deploy & run on the status bar and reduces number of buttons on the toolbar.
Closes #2318
> Move deploy & run to the status bar and reduce number of toolbar buttons

- docs/element-templates/README.md
- resources/element-templates/samples.json
related to #2334
requires camunda/element-templates-json-schema#30
requires bpmn-io/bpmn-js-properties-panel#475
> docs(element-templates): cover local specific camunda:in|out

- docs/element-templates/README.md
> docs(element-templates): correctly state current schema version

- .github/workflows/MERGE_MASTER_TO_DEVELOP.yml
This merges master to develop automatically and notifies us via Slack if merge fails.
> ci: automatically merge master to develop

- CHANGELOG.md
What is missing is the actual library version bumps.
> chore(CHANGELOG): update to v4.9.0

- client/package-lock.json
- client/package.json
Closes https://github.com/camunda/camunda-modeler/issues/2365
> deps: bump zeebe-bpmn-moddle

- client/package-lock.json
- client/package.json
- client/src/app/tabs/bpmn/modeler/features/properties-panel-keyboard-bindings/PropertiesPanelKeyoardBindings.js
> deps(client): bump `@bpmn-io/bpmn-properties-panel`

- client/src/app/App.js
> chore: use const instead of var

- client/src/plugins/update-checks/UpdateChecks.js
- client/src/plugins/update-checks/UpdateChecksAPI.js
- client/src/plugins/update-checks/__tests__/UpdateChecksSpec.js
depends on camunda/camunda-modeler-update-server#2263
closes #2263
> 2263 skip staged rollout

- app/lib/menu/menu-builder.js
- app/test/spec/menu/menu-builder-spec.js
> Ignore plugin & edit menu shortcuts triggered from devtools

- CHANGELOG.md
- app/lib/index.js
- app/lib/menu/menu-builder.js
- app/lib/preload.js
- app/lib/util/file-explorer-open.js
- app/test/spec/menu/menu-builder-spec.js
- client/src/app/App.js
- client/src/app/__tests__/AppSpec.js
- client/src/app/__tests__/mocks/index.js
- client/src/remote/Dialog.js
- client/src/remote/__tests__/DialogSpec.js
> 1834 add option to reveal in file explorer

- client/package-lock.json
- client/package.json
> deps(client): bump to `bpmn-io/bpmn-properties-panel@v0.2.0`

- client/package-lock.json
- client/package.json
Includes a fix for https://github.com/bpmn-io/form-js/issues/161.
> deps(client): update to @bpmn-io/form-js@0.4.2

- client/src/plugins/version-info/ReleaseInfo.js
> feat(releaseInfo): add 4.10 release info

- CHANGELOG.md
- client/package-lock.json
- client/package.json
This does some key bumps and prepares the release log. With this, we should be ready to build the RC (unless we have more changes until the codefreeze)
Releated to #2391
> Prepare 4.10 release

- README.md
> chore(README): add forms to the description

- client/src/app/tabs/EngineProfile.js
- client/src/app/tabs/__tests__/EngineProfileSpec.js
- client/src/app/tabs/form/linting/FormLinter.js
- client/src/app/tabs/form/linting/__tests__/FormLinterSpec.js
- client/src/app/tabs/form/linting/__tests__/camunda-cloud-1-2.json
- client/src/app/tabs/form/linting/__tests__/camunda-platform-7-16.json
> Add Camunda Platform 7.16 and Camunda Cloud 1.2 Execution Platforms

- resources/plugins/test-client/client/index.js
Adds the entry file that somehow got lost...
> fix(plugins): make test-client bundle (again)

- client/src/shared/ui/form/ToggleSwitch.js
- client/src/shared/ui/form/__tests__/ToggleSwitchSpec.js
Add `onChange` handler to toggle in order to allow submit form on toggle.
Related to design review from camunda/cloud-connect-modeler-plugin/pull/65
> feat(toggle): add `onChange` handler

- client/src/app/status-bar/StatusBar.less
- client/src/plugins/camunda-plugin/deployment-tool/DeploymentTool.js
- client/src/plugins/zeebe-plugin/deployment-plugin/DeploymentPlugin.js
- client/src/styles/_status-bar.less
Closes #2550 
Cf. [Design](https://fluffy-fiesta-212e1c7c.pages.github.io/prototypes/visual-ide/v15/)
> Update status bar action colors

- app/lib/window-manager/__tests__/window-manager-spec.js
- app/lib/window-manager/window-manager.js
> feat: increase default window size

- client/src/app/App.less
- client/src/app/Log.less
- client/src/app/primitives/Tabbed.less
- client/src/app/tabs/PropertiesContainer.less
> Redesign tab container

- client/package-lock.json
- client/package.json
This will integrate all latest Zeebe 1.3 changes
closes #2524
closes #2535
closes #2579
> Integrate latest zeebe

- client/src/app/tabs/EngineProfile.js
- client/src/plugins/version-info/ReleaseInfo.js
- client/src/plugins/version-info/ReleaseInfo.less
- client/src/plugins/version-info/VersionInfoOverlay.js
- client/src/plugins/version-info/VersionInfoOverlay.less
- client/src/shared/ui/Section.less
- client/src/shared/ui/overlay/Overlay.js
- client/src/shared/ui/overlay/Overlay.less
- client/src/shared/ui/overlay/OverlayDropdown.less
- client/src/styles/_forms.less
- client/src/styles/_overlay.less
Related to #2488
- Change border and box-shadow
- Change overlay title style
- Adjust report feedback margin around line divider
Artifact: https://camunda-modeler-on-demand.s3.eu-central-1.amazonaws.com/update-overlay-styles/camunda-modeler-update-overlay-styles-mac.dmg
⚠️ waiting to be integrated with #2572
> Adjust overlay styles

- client/package-lock.json
- client/package.json
> deps(client): bump to camunda-bpmn-js@0.12.2

- client/package-lock.json
- client/package.json
> Update dependencies 4.12.0

- client/src/plugins/version-info/ReleaseInfo.js
> Update release info for v4.12

- client/src/remote/Plugins.js
- client/src/shared/ui/overlay/Overlay.js
- client/src/styles/_forms.less
This makes our new sections be available in plugins. It also added missing number input field styles.
Related to https://github.com/camunda/camunda-modeler-plugin-helpers/pull/15
> Expose sections to plugins + add number field styles

- client/src/app/tabs/form/FormEditor.js
- client/src/app/tabs/form/__tests__/FormEditorSpec.js
> fix(FormEditor): #handleChanged on <attach>

- client/src/app/TabsProvider.js
- client/src/app/__tests__/TabsProviderSpec.cloud.form
- client/src/app/__tests__/TabsProviderSpec.form
- client/src/app/__tests__/TabsProviderSpec.js
> fix(forms): tab type for Platform forms

- client/src/app/TabsProvider.js
- client/src/app/__tests__/TabsProviderSpec.js
- client/src/app/__tests__/mocks/index.js
> fix: errors will now show properly when dragging in the wrong file type with 'disable-platform' on

- client/src/app/notifications/Notification.js
- client/src/app/notifications/Notification.less
- client/src/app/notifications/__tests__/NotificationSpec.js
- client/src/plugins/camunda-plugin/deployment-tool/DeploymentTool.js
- client/src/plugins/camunda-plugin/start-instance-tool/StartInstanceTool.js
- client/src/plugins/camunda-plugin/start-instance-tool/__tests__/StartInstanceToolSpec.js
- client/src/plugins/update-checks/UpdateChecks.js
- client/src/plugins/update-checks/__tests__/UpdateChecksSpec.js
- client/src/plugins/zeebe-plugin/deployment-plugin/DeploymentPlugin.js
- client/src/plugins/zeebe-plugin/deployment-plugin/__tests__/DeploymentPluginSpec.js
Closes #2643
https://user-images.githubusercontent.com/25825387/148395624-f8cc599f-a4e2-4ea7-ae49-143e45980fb7.mov
> Open log view from notifications

- client/src/app/tabs/form/FormEditor.js
- client/src/app/tabs/form/__tests__/FormEditorSpec.js
- client/src/app/tabs/form/getFormEditMenu.js
@barmac or @pinussilvestrus please verify the fix on macOS. 👍🏻 
Closes #2411
Related to https://github.com/camunda/camunda-modeler/issues/2541
> Make Select All Work in Form Editor

- client/src/app/TabsProvider.js
- client/src/app/__tests__/TabsProviderSpec.js
- client/src/app/tabs/bpmn/diagram.bpmn
- client/src/app/tabs/cloud-bpmn/diagram.bpmn
- client/src/app/tabs/dmn/diagram.dmn
- client/src/app/tabs/form/FormEditor.js
- client/src/app/tabs/form/initial.form
* add exporter to exported form
* add exporter to initial BPMN diagram, DMN diagram and form
Turns out exporting the initial diagram or form without any changes wouldn't add the exporter. Works now, too.
---
Closes #2540
> Add Exporter to Initial Diagram/Form and Exported Form

- client/src/plugins/version-info/VersionInfo.less
> fix(versionInfo): add border to marker

- client/src/plugins/camunda-plugin/deployment-tool/DeploymentTool.js
- client/src/plugins/camunda-plugin/deployment-tool/__tests__/DeploymentToolSpec.js
> feat(deploy): allow deploy for platform forms

- README.md
* c.f. https://github.com/camunda/camunda-modeler/issues/2691#issuecomment-1016566322
> chore(README): use <master> as sample tag in README

- client/src/plugins/update-checks/NewVersionInfoView.less
- client/src/plugins/update-checks/constants.js
* use sentence case
* reduce padding of html snippets
* related to #2422
Next step:
Automatically add version infos (potentially in the updateCheckServer itself)
**New:**
**Old:**
> style(updateChecks): improve version info dialog styling

- client/src/app/tabs/panel/tabs/LintingTab.js
- client/src/app/tabs/panel/tabs/LintingTab.less
closes #2687 
this will be followed up in a new issue for a more UX friendly solution in the future
> feat: linting errors can now be selected

- CHANGELOG.md
- client/package-lock.json
- client/package.json
> deps: update to dmn-js@11.1.2

- client/src/plugins/version-info/ReleaseInfo.js
> Update release info to v5.0.0-alpha.0

- client/src/app/tabs/bpmn/BpmnEditor.js
- client/src/app/tabs/bpmn/__tests__/BpmnEditorSpec.js
- client/src/app/tabs/cloud-bpmn/BpmnEditor.js
- client/src/app/tabs/cloud-bpmn/__tests__/BpmnEditorSpec.js
- client/src/app/tabs/cmmn/CmmnEditor.js
- client/test/mocks/bpmn-js/Modeler.js
> fix(bpmn): unregister `commandStack.changed` listener

- client/src/plugins/usage-statistics/event-handlers/__tests__/DeploymentEventHandlerSpec.js
- client/src/plugins/usage-statistics/event-handlers/__tests__/DiagramOpenEventHandlerSpec.js
- client/src/plugins/usage-statistics/event-handlers/__tests__/fixtures/subprocess-content.bpmn
- client/src/plugins/usage-statistics/event-handlers/__tests__/fixtures/subprocess-empty.bpmn
- client/src/plugins/usage-statistics/event-handlers/__tests__/fixtures/subprocess-nested.bpmn
- client/src/plugins/usage-statistics/event-handlers/__tests__/fixtures/subprocess-pool.bpmn
- client/src/util/metrics/index.js
- client/src/util/metrics/subprocessPlanes.js
- docs/telemetry/README.md
> chore(usage-statistics): add tracking for subprocess planes

- client/package-lock.json
- client/package.json
> Bump to form-js@0.7.0

- client/src/app/tabs/bpmn/BpmnEditor.js
- client/src/app/tabs/cloud-bpmn/BpmnEditor.js
Closes [#2757](https://github.com/camunda/camunda-modeler/issues/2757)
> feat(plugins): added new menu state flags

- .github/workflows/BUILD_ON_DEMAND.yml
- .github/workflows/NIGHTLY.yml
- .github/workflows/RELEASE.yml
Related to https://github.com/camunda/camunda-modeler/issues/2779
> fix(ci): pin windows-2019

- client/src/plugins/camunda-plugin/start-instance-tool/StartInstanceTool.js
- client/src/plugins/camunda-plugin/start-instance-tool/__tests__/StartInstanceToolSpec.js
> fix(start-instance): remove unnecessary `closeOverlay` for overlayDropdown

- client/src/plugins/usage-statistics/event-handlers/DiagramOpenEventHandler.js
- client/src/plugins/usage-statistics/event-handlers/__tests__/DiagramOpenEventHandlerSpec.js
Closes #2786
Built on top #2785
> Track cloud element templates

- client/src/app/tabs/bpmn-shared/util/__tests__/configureSpec.js
- client/src/app/tabs/bpmn-shared/util/configure.js
- client/src/app/tabs/bpmn/BpmnEditor.js
- client/src/app/tabs/bpmn/__tests__/BpmnEditorSpec.js
- client/src/app/tabs/cloud-bpmn/BpmnEditor.js
- client/src/app/tabs/cloud-bpmn/__tests__/BpmnEditorSpec.js
> feat(bpmnjs): handle platform specific plugins

- client/src/plugins/camunda-plugin/deployment-tool/DeploymentConfigOverlay.js
- client/src/plugins/zeebe-plugin/deployment-plugin/DeploymentPluginConstants.js
Related to https://github.com/bpmn-io/internal-docs/issues/481
Artifacts:
https://camunda-modeler-on-demand.s3.eu-central-1.amazonaws.com/rename-C7-C8-deployment/camunda-modeler-rename-C7-C8-deployment-linux-x64.tar.gz
https://camunda-modeler-on-demand.s3.eu-central-1.amazonaws.com/rename-C7-C8-deployment/camunda-modeler-rename-C7-C8-deployment-mac.dmg
https://camunda-modeler-on-demand.s3.eu-central-1.amazonaws.com/rename-C7-C8-deployment/camunda-modeler-rename-C7-C8-deployment-mac.zip
https://camunda-modeler-on-demand.s3.eu-central-1.amazonaws.com/rename-C7-C8-deployment/camunda-modeler-rename-C7-C8-deployment-win-ia32.zip
https://camunda-modeler-on-demand.s3.eu-central-1.amazonaws.com/rename-C7-C8-deployment/camunda-modeler-rename-C7-C8-deployment-win-x64.zip
Screenshot:
> Rename to C7/C8 in deployment overlay

- client/src/app/__tests__/TabsProviderSpec.dmn13.xml
- client/src/app/__tests__/TabsProviderSpec.js
- client/src/app/util/parseDiagramType.js
> fix: open DMN 1.3 files with XML extension

- client/src/app/EmptyTab.js
- client/src/app/EmptyTab.less
- client/src/app/__tests__/EmptyTabSpec.js
- client/src/shared/ui/NewBadge.js
- client/src/shared/ui/NewBadge.less
- client/src/styles/_colors.less
Closes: #2826 
See artifacts via build 
https://camunda-modeler-on-demand.s3.eu-central-1.amazonaws.com/welcome-tab-upgrades/camunda-modeler-welcome-tab-upgrades-linux-x64.tar.gz
https://camunda-modeler-on-demand.s3.eu-central-1.amazonaws.com/welcome-tab-upgrades/camunda-modeler-welcome-tab-upgrades-mac.dmg
https://camunda-modeler-on-demand.s3.eu-central-1.amazonaws.com/welcome-tab-upgrades/camunda-modeler-welcome-tab-upgrades-mac.zip
https://camunda-modeler-on-demand.s3.eu-central-1.amazonaws.com/welcome-tab-upgrades/camunda-modeler-welcome-tab-upgrades-win-ia32.zip
https://camunda-modeler-on-demand.s3.eu-central-1.amazonaws.com/welcome-tab-upgrades/camunda-modeler-welcome-tab-upgrades-win-x64.zip
> feat: welcome tab overhaul 

- client/src/app/App.js
- client/src/app/EmptyTab.js
- client/src/app/__tests__/AppSpec.js
- client/src/app/__tests__/mocks/index.js
- client/src/shared/ui/NewBadge.js
- client/src/shared/ui/NewBadge.less
- client/src/shared/ui/overlay/OverlayDropdown.js
> feat: create new dropdown badge

- client/src/app/tabs/EngineProfile.js
- client/src/app/tabs/__tests__/EngineProfileSpec.js
- client/src/util/Engines.js
> feat: engine profile version renaming

- client/src/app/EmptyTab.js
* We do this early, so that we can update docs with new screenshots
already.
> chore(emptyTab): adjust blogpost title for C8 intro

- client/src/plugins/zeebe-plugin/deployment-plugin/DeploymentPlugin.js
- client/src/plugins/zeebe-plugin/deployment-plugin/DeploymentPluginOverlay.js
- client/src/plugins/zeebe-plugin/deployment-plugin/__tests__/DeploymentPluginSpec.js
> chore(cloud deployment): set `SaaS` as default

- client/src/plugins/usage-statistics/event-handlers/DeploymentEventHandler.js
- client/src/plugins/usage-statistics/event-handlers/DiagramOpenEventHandler.js
- client/src/plugins/usage-statistics/event-handlers/__tests__/DeploymentEventHandlerSpec.js
- client/src/plugins/usage-statistics/event-handlers/__tests__/DiagramOpenEventHandlerSpec.js
- client/src/plugins/usage-statistics/event-handlers/__tests__/fixtures/engine-cloud.dmn
- client/src/plugins/usage-statistics/event-handlers/__tests__/fixtures/engine-platform.dmn
- client/src/util/parse.js
Closes #2853
---
- https://camunda-modeler-on-demand.s3.eu-central-1.amazonaws.com/DMN-telemetry/camunda-modeler-DMN-telemetry-linux-x64.tar.gz
- https://camunda-modeler-on-demand.s3.eu-central-1.amazonaws.com/DMN-telemetry/camunda-modeler-DMN-telemetry-mac.dmg
- https://camunda-modeler-on-demand.s3.eu-central-1.amazonaws.com/DMN-telemetry/camunda-modeler-DMN-telemetry-mac.zip
- https://camunda-modeler-on-demand.s3.eu-central-1.amazonaws.com/DMN-telemetry/camunda-modeler-DMN-telemetry-win-ia32.zip
- https://camunda-modeler-on-demand.s3.eu-central-1.amazonaws.com/DMN-telemetry/camunda-modeler-DMN-telemetry-win-x64.zip
> Telemetry for cloud dmn diagrams

- client/src/plugins/zeebe-plugin/deployment-plugin/DeploymentPlugin.js
- client/src/plugins/zeebe-plugin/deployment-plugin/DeploymentPluginOverlay.js
- client/src/plugins/zeebe-plugin/deployment-plugin/__tests__/DeploymentPluginOverlaySpec.js
- client/src/plugins/zeebe-plugin/deployment-plugin/__tests__/DeploymentPluginSpec.js
Closes #2860
See example:
1. Try wrong credentials (can't deploy) -> close overlay -> credentials saved
2. Try right credentials with invalid diagram -> deploy fails but credentials are saved
https://user-images.githubusercontent.com/25825387/161419793-eb5e9966-ec36-4032-a180-da72d5081017.mov
> Improve UX of deploy's remember credentials

- client/src/app/App.js
- client/src/plugins/camunda-plugin/deployment-tool/DeploymentTool.js
- client/src/plugins/camunda-plugin/start-instance-tool/StartInstanceTool.js
- client/src/plugins/camunda-plugin/start-instance-tool/__tests__/StartInstanceToolSpec.js
- client/src/plugins/update-checks/UpdateChecks.js
- client/src/plugins/update-checks/__tests__/UpdateChecksSpec.js
- client/src/plugins/zeebe-plugin/deployment-plugin/DeploymentPlugin.js
- client/src/plugins/zeebe-plugin/deployment-plugin/__tests__/DeploymentPluginSpec.js
> fix: adjusted logging for toast notifications

- client/src/app/tabs/dmn/OverviewContainer.less
> fix: DMN overview icons ignore pointer events

- client/src/plugins/report-feedback/ClipboardCopySystemInfo.js
- client/src/plugins/report-feedback/__tests__/ClipboardCopySystemInfoSpec.js
> fix: copy correct execution platform

- .github/CONTRIBUTING.md
- .github/ISSUE_TEMPLATE/config.yml
- README.md
- client/src/app/tabs/MultiSheetTab.js
- client/src/plugins/report-feedback/ReportFeedbackOverlay.js
> chore: link to new forum homepage

- resources/element-templates/cloud-samples.json
- resources/element-templates/samples.json
Related to https://github.com/bpmn-io/internal-docs/issues/499
> docs: update element template samples

- client/src/app/EmptyTab.js
> chore(emptyTab): link to C8 intro blogPost

- client/src/plugins/version-info/ReleaseInfo.js
* This is WIP as long as we don't have the final Modeler 5 feature set fixed.
* Please already review to ensure we have the major themes covered. Also feel free to add individual feedback already.
> chore(ReleaseInfo): update to 5.0.0

- app/lib/zeebe-api.js
- app/test/spec/zeebe-api-spec.js
- client/src/plugins/zeebe-plugin/deployment-plugin/DeploymentPluginConstants.js
- client/src/plugins/zeebe-plugin/deployment-plugin/DeploymentPluginOverlay.js
Closes #2862
For further explanation on the message changes, look here https://github.com/camunda/camunda-modeler/issues/2862#issuecomment-1086941833
Artfacts:
https://camunda-modeler-on-demand.s3.eu-central-1.amazonaws.com/2862-extract-error-message/camunda-modeler-2862-extract-error-message-linux-x64.tar.gz
https://camunda-modeler-on-demand.s3.eu-central-1.amazonaws.com/2862-extract-error-message/camunda-modeler-2862-extract-error-message-mac.dmg
https://camunda-modeler-on-demand.s3.eu-central-1.amazonaws.com/2862-extract-error-message/camunda-modeler-2862-extract-error-message-mac.zip
https://camunda-modeler-on-demand.s3.eu-central-1.amazonaws.com/2862-extract-error-message/camunda-modeler-2862-extract-error-message-win-ia32.zip …
> Improve connection error messages in cloud deploy

- client/src/app/EmptyTab.js
- client/src/app/tabs/EngineProfile.js
- client/src/app/tabs/__tests__/EngineProfileSpec.js
- client/src/plugins/privacy-preferences/constants.js
- client/src/plugins/report-feedback/ReportFeedbackOverlay.js
- client/src/plugins/version-info/VersionInfoOverlay.js
- client/src/plugins/zeebe-plugin/start-instance-plugin/StartInstanceConfigOverlay.js
> chore: add query params to camunda.com URLs

- client/src/app/App.js
- client/src/app/__tests__/AppSpec.js
- client/src/app/tabs/MultiSheetTab.js
> fix(App): use separate linting state

- client/package-lock.json
- client/package.json
- client/src/app/tabs/panel/tabs/LintingTab.js
- client/src/app/tabs/panel/tabs/__tests__/LintingTabSpec.js
* fix error message formatting (cf. https://github.com/camunda/bpmnlint-plugin-camunda-compat/pull/27)
* make sorting deterministic
---
Requires https://github.com/camunda/bpmnlint-plugin-camunda-compat/pull/27
> fix: make sorting deterministic

- client/src/plugins/zeebe-plugin/deployment-plugin/DeploymentPlugin.js
- client/src/plugins/zeebe-plugin/deployment-plugin/__tests__/DeploymentPluginSpec.js
- client/src/shared/ui/form/TextInput.js
> fix(deploy): reverse order of input error and description

- client/src/app/App.js
- client/src/app/__tests__/AppSpec.js
> fix(App): always write file when save is triggered

- .github/workflows/COMMENT_DEVELOP_FIX.yml
> ci: check target branch only when PR is opened

- README.md
> fix: add form-js notice to license

- client/src/remote/Dialog.js
- client/src/remote/__tests__/DialogSpec.js
Closes #2300
This requires local testing.
Artefacts
https://camunda-modeler-on-demand.s3.eu-central-1.amazonaws.com/cfd-cons/camunda-modeler-cfd-cons-linux-x64.tar.gz
https://camunda-modeler-on-demand.s3.eu-central-1.amazonaws.com/cfd-cons/camunda-modeler-cfd-cons-mac.dmg
https://camunda-modeler-on-demand.s3.eu-central-1.amazonaws.com/cfd-cons/camunda-modeler-cfd-cons-mac.zip
https://camunda-modeler-on-demand.s3.eu-central-1.amazonaws.com/cfd-cons/camunda-modeler-cfd-cons-win-ia32.zip
https://camunda-modeler-on-demand.s3.eu-central-1.amazonaws.com/cfd-cons/camunda-modeler-cfd-cons-win-x64.zip
> fix: reorder close file dialog to match convention

- .github/workflows/ADD_TO_PROJECT.yaml
Add `connectors` labeled issues to the connector project.
> ci: add ADD_TO_PROJECT action

- tasks/send-license-book-summary.js
In this PR, we no longer get the current version from git, but rather use `app/package.json#version`. It's a workaround but we don't need to figure out what is happening in the GHA clone of the repo in order to fix the issue.
Closes #2896
---
Tested via https://github.com/camunda/camunda-modeler/runs/5970232438?check_suite_focus=true
> ci: display correct version in license book summary

- client/src/plugins/user-journey-statistics/event-handlers/DeploymentEventHandler.js
- client/src/plugins/user-journey-statistics/event-handlers/__tests__/DeploymentEventHandlerSpec.js
- client/src/plugins/user-journey-statistics/event-handlers/index.js
> Mixpanel: track diagram deployments

- client/src/plugins/user-journey-statistics/event-handlers/OverlayEventHandler.js
- client/src/plugins/user-journey-statistics/event-handlers/__tests__/OverlayEventHandlerSpec.js
- client/src/plugins/user-journey-statistics/util.js
> feat(mixpanel): track overlays usage

- package-lock.json
- package.json
I did `npm run all`, played around with it and did some of the integration tests. There seems to be no issues.
I also build artifacts, to make sure it would work:
https://camunda-modeler-on-demand.s3.eu-central-1.amazonaws.com/update-electron-to-latest/camunda-modeler-update-electron-to-latest-linux-x64.tar.gz
https://camunda-modeler-on-demand.s3.eu-central-1.amazonaws.com/update-electron-to-latest/camunda-modeler-update-electron-to-latest-win-ia32.zip
https://camunda-modeler-on-demand.s3.eu-central-1.amazonaws.com/update-electron-to-latest/camunda-modeler-update-electron-to-latest-win-x64.zip
https://camunda-modeler-on-demand.s3.eu-central-1.amazonaws.com/update-electron-to-latest/camunda-modeler-update-electron-to-latest-mac.dmg …
> Update electron to latest (19.0.5)

- resources/element-templates/cloud-samples.json
Related to https://github.com/bpmn-io/bpmn-js-properties-panel/issues/690
* bump `bpmn-js-properties-panel`
* add conditional template properties example
> Include conditional template properties

- docs/.project/INTEGRATION_TEST.md
`Camunda Cloud 1.0` + `Camunda Cloud 1.2` are outdated.
> chore(INTEGRATION_TEST): update execution platforms

- client/src/plugins/version-info/ReleaseInfo.js
> chore(release): Update release info for 5.1

- client/src/app/App-patch.css
- client/src/app/App.js
> fix(styles): enforce styles for 5.1 release

- .github/workflows/BUILD_ON_DEMAND.yml
- .github/workflows/CI.yml
- .github/workflows/NIGHTLY.yml
- .github/workflows/RELEASE.yml
Related to https://github.com/actions/virtual-environments/issues/5583
> ci: use macos 11

- client/src/app/tabs/panel/Panel.less
- client/src/app/tabs/panel/tabs/LintingTab.js
- client/src/app/tabs/panel/tabs/LintingTab.less
Fixes according to https://github.com/camunda/camunda-modeler-design/issues/104.
---
Required https://github.com/camunda/camunda-modeler/pull/3014
> Fix Error Panel Styles

- client/src/plugins/version-info/ReleaseInfo.js
@marstamm Feel free to change the wording.
> chore: adjust release info to v5.2

- client/src/app/TabsProvider.js
> fix(tabs-provider): add missing DMN help menu

- CHANGELOG.md
- client/package-lock.json
- client/package.json
closes https://github.com/camunda/camunda-modeler/issues/3068
> deps: bump to dmn-js@12.2.1

- client/src/app/tabs/panel/tabs/LintingTab.less
> fix: make error panel ellipsis work

- client/src/plugins/camunda-plugin/__tests__/CamundaPluginSpec.js
- client/src/plugins/camunda-plugin/start-instance-tool/StartInstanceTool.js
- client/src/plugins/camunda-plugin/start-instance-tool/__tests__/StartInstanceToolSpec.js
- client/src/plugins/zeebe-plugin/start-instance-plugin/StartInstancePlugin.js
- client/src/plugins/zeebe-plugin/start-instance-plugin/__tests__/StartInstancePluginSpec.js
Closes #3052
Note: These files were a bit confusing so I did some clean-up along with the solution
> fix(start instance): close overlay through icon click

- .github/workflows/RELEASE_ISSUE.yml
related to https://github.com/bpmn-io/fake-join/pull/44
> chore: move release issue creation to gh-action

- CHANGELOG.md
- client/package-lock.json
- client/package.json
- client/src/app/tabs/bpmn/BpmnEditor.js
- client/src/app/tabs/cloud-bpmn/BpmnEditor.js
- package-lock.json
Related to https://github.com/camunda/camunda-modeler/issues/3083.
> Update `@camunda/linting` to add `inclusive-gateway` Rule

- client/src/app/tabs/__tests__/EngineProfileSpec.js
- client/src/util/Engines.js
> feat(client): add latest execution platform versions

- client/package.json
- client/src/app/tabs/form/FormEditor.less
- package-lock.json
> deps: update to `form-js@0.9.2`

- client/src/plugins/version-info/ReleaseInfo.js
> chore(releaseInfo): update to v5.4.0

- client/src/app/tabs/dmn/modeler/features/decision-table-keyboard/DecisionTableKeyboard.js
- client/src/app/tabs/dmn/modeler/features/decision-table-keyboard/__tests__/DecisionTableKeyboardSpec.js
> fix(client): do not call injector#invoke on class

- client/package.json
- package-lock.json
closes https://github.com/camunda/camunda-modeler/issues/3215
> deps: update to form-js@0.9.6

- CHANGELOG.md
> chore(CHANGELOG): update to v5.4.0

- app/lib/menu/menu-builder.js
Links to https://docs.camunda.io/docs/components/modeler/feel/what-is-feel/
Closes #3201
> feat(menu): add FEEL reference link

- package-lock.json
- package.json
Reverts camunda/camunda-modeler#3155
> Revert "deps(builder): bump electron from 19.0.13 to 20.2.0"

- client/src/app/tabs/form/FormEditor.less
Related to https://github.com/bpmn-io/form-js/issues/330
> style(form): use proper font variables

- client/src/app/tabs/xml/XMLEditor.js
- client/src/app/tabs/xml/__tests__/XMLEditorSpec.js
> fix: save flag on handle change in xml editor

- client/src/plugins/update-checks/UpdateChecksAPI.js
- client/src/plugins/update-checks/__tests__/UpdateChecksAPISpec.js
- client/src/plugins/update-checks/__tests__/UpdateChecksSpec.js
400 Bad Request handler for #2999
> fix: handle bad request for update check

- client/package.json
- package-lock.json
> deps: update to @bpmn-io/properties-panel@0.24.0

- client/src/app/tabs/EngineProfile.js
- client/src/app/tabs/__tests__/EngineProfileSpec.js
> feat: tag non-latest versions as `alpha`

- CHANGELOG.md
Related to https://github.com/camunda/camunda-modeler/issues/3307
> Prepare 5.5.1 release

- docs/.project/RELEASE_TEMPLATE.md
> docs: add release presentation page link

- CHANGELOG.md
> chore: update changelog to v5.6.0

- client/src/plugins/version-info/ReleaseInfo.js
> feat: update release info to v5.6.0

- client/src/plugins/version-info/ReleaseInfo.js
> chore: update release info

- CHANGELOG.md
- client/package.json
- package-lock.json
Related to https://github.com/camunda/camunda-modeler/issues/3361
> deps: update @camunda/form-linting to v0.2.1

- client/package.json
- client/src/util/metrics/processVariables.js
- package-lock.json
Integrates `@bpmn-io/extract-process-variables@0.7.0` and ensures we await the newly asynchronous functions
> deps: bump to @bpmn-io/extract-process-variables@0.7.0

- .github/workflows/BUILD_ON_DEMAND.yml
- .github/workflows/CI.yml
- .github/workflows/NIGHTLY.yml
- .github/workflows/RELEASE.yml
> ci: cache using built-in pipeline feature

- client/src/app/KeyboardBindings.js
- client/src/app/__tests__/KeyboardBindingsSpec.js
> fix(client): check for modifier in replace shortcut

- CHANGELOG.md
- client/package.json
- package-lock.json
> deps: update to `@camunda/linting@0.13.0`

- app/package-lock.json
- app/package.json
- package-lock.json
> deps: bump to zeebe-node@8.1.5

- CHANGELOG.md
- app/lib/zeebe-api/zeebe-api.js
- app/test/spec/zeebe-api/zeebe-api-spec.js
Related to https://camunda.slack.com/archives/CKGH9LR40/p1675861000401159
> fix: deploy to C8 when name ends with file type

- .github/workflows/PUBLISH_RELEASE.yml
> ci: serialize download links for release publishing

- client/src/plugins/zeebe-plugin/deployment-plugin/DeploymentPlugin.js
- client/src/plugins/zeebe-plugin/deployment-plugin/__tests__/DeploymentPluginSpec.js
- client/src/plugins/zeebe-plugin/start-instance-plugin/StartInstancePlugin.js
- client/src/plugins/zeebe-plugin/start-instance-plugin/__tests__/StartInstancePluginSpec.js
> fix: correct C8 SaaS deploy/start cluster URL

- app/lib/menu/menu-builder.js
- client/src/app/App.js
- client/src/app/__tests__/AppSpec.js
Closes https://github.com/camunda/camunda-modeler/issues/3458
> feat: expose `activeTab` to menu

- client/package.json
- package-lock.json
Closes https://github.com/camunda/camunda-modeler/issues/3442
Closes https://github.com/camunda/camunda-modeler/issues/3440
> deps(client): update to bpmn-js@11.4.1

- package-lock.json
> deps: bump to variable-resolver@0.1.1

- .github/workflows/PUBLISH_RELEASE.yml
fixes `No such file or directory` error, (cf. https://github.com/camunda/camunda-modeler/actions/runs/4385953189 )
> fix(PUBLISH_RELEASE): escape download URLs

- CHANGELOG.md
- app/package.json
- package-lock.json
> deps: update to `zeebe-node@8.1.6`

- client/src/util/Engines.js
- client/src/util/__tests__/EnginesSpec.js
closes https://github.com/bpmn-io/internal-docs/issues/745
> chore: update latest versions

- client/src/plugins/version-info/ReleaseInfo.js
> fix(ReleaseInfo): fix uppercase typo

- CHANGELOG.md
- client/package.json
- package-lock.json
> Integrate form linting patch

- resources/platform/base/resources/element-templates/README.md
* rephrase
* clarify local vs global element templates
* change documentation link
Follow-up to https://github.com/camunda/camunda-modeler/pull/3559.
> chore: rephrase `resources/element-templates` README

- client/src/util/Engines.js
> feat: add alpha platform version

- package-lock.json
- @bpmn-io/feel-editor@0.7.1
- @bpmn-io/variable-resolver@1.0.1
- @camunda/example-data-properties-provider@1.1.1
closes #3581, #3582
The dependencies will also be bumped in the repos with direct dependencies on them via https://github.com/camunda/camunda-bpmn-js/pull/274 and https://github.com/bpmn-io/properties-panel/pull/239
> deps: update variable resolver deps

- package-lock.json
> deps: update to moddle@6.2.3

- client/src/app/tabs/bpmn/BpmnEditor.js
- client/src/app/tabs/bpmn/__tests__/BpmnEditorSpec.js
- client/src/app/tabs/cloud-bpmn/BpmnEditor.js
- client/src/app/tabs/cloud-bpmn/__tests__/BpmnEditorSpec.js
- package-lock.json
> deps: update to `@bpmn-io/properties-panel@1.8.2`

- client/src/plugins/zeebe-plugin/deployment-plugin/DeploymentPlugin.js
- client/src/plugins/zeebe-plugin/deployment-plugin/__tests__/DeploymentPluginSpec.js
- client/src/plugins/zeebe-plugin/shared/__tests__/utilSpec.js
- client/src/plugins/zeebe-plugin/shared/util.js
- client/src/plugins/zeebe-plugin/start-instance-plugin/StartInstancePlugin.js
- client/src/plugins/zeebe-plugin/start-instance-plugin/__tests__/StartInstancePluginSpec.js
> fix: display Operate link without trailing slash

- client/package.json
- client/src/app/tabs/bpmn/modeler/BpmnModeler.js
- client/src/app/tabs/cloud-bpmn/modeler/BpmnModeler.js
- package-lock.json
Related to https://github.com/camunda/camunda-modeler/pull/3598#discussion_r1189958945
> chore(client): explicitly import tracking modules

- CHANGELOG.md
- app/lib/zeebe-api/zeebe-api.js
- app/test/spec/zeebe-api/zeebe-api-spec.js
- client/src/plugins/zeebe-plugin/deployment-plugin/__tests__/DeploymentPluginValidatorSpec.js
> feat: infer default port when connecting to Zeebe instances

- client/src/app/App.js
- client/src/app/__tests__/AppParentSpec.js
- client/src/app/__tests__/AppSpec.js
> fix(client): keep all files open when quitting the app

- client/src/plugins/camunda-plugin/start-instance-tool/StartInstanceConfigOverlay.js
- client/src/plugins/camunda-plugin/start-instance-tool/StartInstanceTool.js
- client/src/plugins/camunda-plugin/start-instance-tool/__tests__/StartInstanceToolSpec.js
This reworks https://github.com/camunda/camunda-modeler/pull/3631 + adds test coverage.
----
Closes https://github.com/camunda/camunda-modeler/issues/3623
> Business key null

- CHANGELOG.md
I think this is worth mentioning. 😜
> chore(CHANGELOG): add missing change

- client/src/plugins/version-info/VersionInfoOverlay.js
> fix(VersionInfo): update release notes link

- .github/workflows/BUILD_ON_DEMAND.yml
- .github/workflows/NIGHTLY.yml
- .github/workflows/RELEASE.yml
- CHANGELOG.md
- package-lock.json
- package.json
- tasks/after-sign/notarize.js
> deps: migrate to `@electron/notarize`

- .github/workflows/CODE_SCANNING.yml
Let's try out native GitHub code scanning provider.
> ci: setup code scanning with GH CodeQL

- client/src/app/resizable-container/PropertiesPanelContainer.js
Closes #3672
Explanation [in issue ](https://github.com/camunda/camunda-modeler/issues/3672#issuecomment-1594427521)
> fix(client): add `properties` class to container

- CHANGELOG.md
- client/package.json
- package-lock.json
> deps: update to `@camunda/linting@2.1.0`

- client/src/plugins/user-journey-statistics/event-handlers/DeploymentEventHandler.js
- client/src/plugins/user-journey-statistics/event-handlers/TabEventHandler.js
- client/src/plugins/user-journey-statistics/event-handlers/__tests__/DeploymentEventHandlerSpec.js
- client/src/plugins/user-journey-statistics/event-handlers/__tests__/TabEventHandlerSpec.js
- client/src/plugins/user-journey-statistics/util.js
Closes #3539
Working on Mixpanel:
> feat(mixpanel): track template ids present in diagrams

- docs/.project/RELEASE_TEMPLATE.md
* update release manager handle
* update blog post
> chore(RELEASE_TEMPLATE): incorporate latest changes

- client/src/plugins/version-info/ReleaseInfo.js
> chore(version-info): update based on feedback

- client/src/app/tabs/bpmn/__tests__/DiagramSpec.js
- client/src/app/tabs/bpmn/diagram.bpmn
closes #3701
History TTL is defined in days, so 180 days = 6 (30 day) Months
> feat(bpmn): set default ttl to 6 months

- CHANGELOG.md
- client/package.json
- package-lock.json
Closes #3613
Closes #3712
Closes #3577
> deps: update to `@camunda/linting@3.3.0`

- CHANGELOG.md
- client/package.json
- package-lock.json
> deps: update to `@camunda/linting@3.4.0`

- client/src/plugins/version-info/ReleaseInfo.js
> chore(version-info): update to v5.14.0

- client/src/app/tabs/MultiSheetTab.js
- client/src/app/tabs/bpmn/BpmnEditor.js
- client/src/app/tabs/bpmn/__tests__/BpmnEditorSpec.js
- client/src/app/tabs/cloud-bpmn/BpmnEditor.js
- client/src/app/tabs/cloud-bpmn/__tests__/BpmnEditorSpec.js
> feat(bpmn): reload element templates on file save

- client/src/plugins/version-info/VersionInfoOverlay.js
Closes #3765 (see discussion in [previous PR](https://github.com/camunda/camunda-modeler/pull/3766))
> fix(VersionInfo): adjust release notes blog link

- client/src/app/App.js
- client/src/app/__tests__/AppSpec.js
closed https://github.com/camunda/camunda-modeler/issues/3763
> feat(app): lint on save

- client/src/app/panel/tabs/linting/LintingTab.js
I've tried to test this with text selection but failed with both ´enzyme´ and `react-dom/test-utils`. 😢 
Closes #2687
> fix: do not select element if text selected

- client/package.json
- package-lock.json
Closes https://github.com/camunda/camunda-modeler/issues/3762
Closes https://github.com/camunda/camunda-modeler/issues/3609
> deps: update to `@camunda/linting@3.5.0`

- .github/workflows/NIGHTLY.yml
- app/util/get-version.js
- client/webpack.config.js
- dev.js
- tasks/distro.js
- tasks/test-distro.js
closes https://github.com/camunda/camunda-modeler/issues/3791
> fix(sentry): align sentry release with build version

- package-lock.json
- package.json
> chore: drop `which`

- client/package.json
- package-lock.json
closes https://github.com/camunda/camunda-modeler/issues/3758
> deps: update to @camunda/linting@3.5.1

- client/src/plugins/version-info/ReleaseInfo.js
> chore: update release info to v5.15

- client/src/app/tabs/bpmn/BpmnEditor.less
- client/src/app/tabs/cloud-bpmn/BpmnEditor.less
We'll unhide it once it's fixed. 🤞🏻
> fix: hide FEEL popup

- client/src/app/panel/tabs/linting/LintingTab.less
Follow-up to https://github.com/camunda/camunda-modeler/pull/3818
> fix(linting-tab): fix link color

- app/lib/log/__tests__/log-spec.js
- app/lib/log/log.js
- app/lib/log/transports/client.js
- app/lib/log/transports/console.js
- app/lib/log/transports/file.js
- app/lib/zeebe-api/zeebe-api.js
- app/test/spec/zeebe-api/zeebe-api-spec.js
- client/src/plugins/zeebe-plugin/deployment-plugin/__tests__/DeploymentPluginSpec.js
- client/src/plugins/zeebe-plugin/shared/__tests__/utilSpec.js
- client/src/plugins/zeebe-plugin/shared/util.js
- client/src/plugins/zeebe-plugin/start-instance-plugin/StartInstancePlugin.js
- client/src/plugins/zeebe-plugin/start-instance-plugin/__tests__/StartInstancePluginSpec.js
To improve the tracability and error handling in the app I suggest the following changes:
* DEBUG log ALL zeebe interactions
* Not hide details (i.e. redact secrets `****`, but keep the keys)
* Normalize logging
> Debug log zeebe connections

- .github/ISSUE_TEMPLATE/BUG_REPORT.yml
- client/src/app/EmptyTab.js
- client/src/app/TabsProvider.js
- client/src/app/__tests__/EmptyTabSpec.js
- client/src/app/__tests__/mocks/index.js
- client/src/app/tabs/EngineProfile.js
- client/src/app/tabs/__tests__/EngineProfileSpec.js
- client/src/app/tabs/bpmn/__tests__/BpmnEditorSpec.js
- client/src/app/tabs/cloud-dmn/DmnTab.js
- client/src/app/tabs/dmn/__tests__/DmnEditorSpec.js
- client/src/app/tabs/form/__tests__/FormEditorSpec.js
- client/src/plugins/camunda-plugin/deployment-tool/DeploymentConfigOverlay.js
- client/src/plugins/camunda-plugin/deployment-tool/__tests__/DeploymentConfigValidatorSpec.js
- client/src/plugins/camunda-plugin/deployment-tool/validation/EndpointURLValidator.js
- client/src/plugins/camunda-plugin/shared/CamundaAPI.js
- client/src/plugins/report-feedback/ClipboardCopySystemInfo.js
- client/src/plugins/report-feedback/__tests__/ClipboardCopySystemInfoSpec.js
- client/src/plugins/zeebe-plugin/deployment-plugin/DeploymentPluginConstants.js
- client/src/util/Engines.js
- docs/.project/INTEGRATION_TEST.md
> chore: drop `platform` term

- client/src/util/Engines.js
- client/src/util/__tests__/EnginesSpec.js
> chore(Engines): mark 8.3 and 7.20 as stable

- docs/.project/INTEGRATION_TEST.md
> chore(docs): remove Cawemo plugin from integration tests

- client/package.json
- package-lock.json
> deps: update @camunda/linting to v3.9.0

- docs/.project/RELEASE_TEMPLATE.md
Changed, cf. https://github.com/camunda/camunda-docs.
> chore: rename docs repository in RELEASE_TEMPLATE

- client/package.json
- client/src/app/tabs/bpmn/BpmnEditor.less
- client/src/app/tabs/bpmn/modeler/features/properties-panel-keyboard-bindings/FeelPopupKeyboardBindings.js
- client/src/app/tabs/bpmn/modeler/features/properties-panel-keyboard-bindings/index.js
- client/src/app/tabs/cloud-bpmn/BpmnEditor.js
- client/src/app/tabs/cloud-bpmn/BpmnEditor.less
- package-lock.json
closes https://github.com/camunda/camunda-modeler/issues/3877
This does not address https://github.com/camunda/camunda-modeler/issues/3902 and reuses the (sometimes broken) undo/redo handling already present for forms.
> feat(bpmn): integrate popup editor 

- client/package.json
- client/src/plugins/element-templates-modal/modeler/EditorActions.js
- client/src/plugins/element-templates-modal/modeler/__tests__/bpmn-io-modelers/EditorActionsSpec.js
- client/src/plugins/element-templates-modal/modeler/__tests__/bpmn-io-modelers/templates.json
- package-lock.json
> Do not allow to select deprecated templates

- client/src/util/Engines.js
related to https://github.com/camunda/camunda-modeler/issues/3921
> feat(engines): add new alpha versions

- .github/workflows/ADD_TO_PROJECT.yaml
> ci: use vault for add-to-project action

- .github/workflows/BUILD_ON_DEMAND.yml
- .github/workflows/CI.yml
- .github/workflows/NIGHTLY.yml
- .github/workflows/RELEASE.yml
Related to failed run https://github.com/camunda/camunda-modeler/actions/runs/6723359618
> ci: build on windows-2022 runner

- client/src/plugins/version-info/ReleaseInfo.js
> chore(RelaseInfo): update to v5.17.0

- client/src/plugins/version-info/ReleaseInfo.js
Replace the minor Non-Interrupting Events toggle with the FEEL editor improvements, which have a bigger user impact.
Thanks to @nikku for pointing this out.
> chore(ReleaseInfo): add FEEL editor improvements

- client/src/app/tabs/cloud-dmn/DmnEditor.js
- client/src/app/tabs/dmn/DmnEditor.js
---
Related to https://github.com/bpmn-io/dmn-js/issues/801
> chore: adjust label

- client/src/plugins/zeebe-plugin/deployment-plugin/DeploymentPluginConstants.js
Discovered via https://camunda.slack.com/archives/CKGH9LR40/p1701705286288949?thread_ts=1701703361.067919&cid=CKGH9LR40
Thanks @MaxTru 
Closes #4005
> fix: update error message to Camunda 8 SaaS URL

- client/src/plugins/version-info/ReleaseInfo.js
> chore(release-info): update to v5.18.0

- client/package.json
- package-lock.json
> deps: update to `camunda-dmn-js@1.7.0`

- CHANGELOG.md
- client/package.json
- package-lock.json
deps: update `@camunda/linting`
Closes #4020
> feat: allow collapsed subprocess in 8.4

- CHANGELOG.md
- client/src/plugins/version-info/ReleaseInfo.js
> Camunda Modeler v5.19.0 Release Info

- client/src/util/Engines.js
- client/src/util/__tests__/EnginesSpec.js
Related to https://github.com/camunda/camunda-modeler/issues/4027
> chore: update latest stable Camunda 8 version to 8.4

- app/lib/index.js
- app/lib/menu/menu-builder.js
- app/lib/preload.js
- client/src/app/App.js
- client/src/app/__tests__/AppSpec.js
- client/src/app/__tests__/mocks/index.js
- client/src/remote/Dialog.js
- client/src/remote/__tests__/DialogSpec.js
Closes #3240 #3886
* If no unsaved changes -> reloads
* If unsaved changes -> show dialog (save and reload, continue without reload, cancel)
> feat: dialog to save changes before reload

- .github/workflows/CODE_SCANNING.yml
- .github/workflows/COMMENT_DEVELOP_FIX.yml
- .github/workflows/MERGE_MASTER_TO_DEVELOP.yml
- CHANGELOG.md
- README.md
- client/src/plugins/version-info/VersionInfoOverlay.js
- tasks/after-pack/add-platform-files.js
- tasks/link-dependencies.js
> chore: switch to `main`

- client/package.json
- client/src/app/tabs/cloud-bpmn/modeler/BpmnModeler.js
- package-lock.json
> deps: integrate feel popup tracking

- client/src/plugins/report-feedback/ReportFeedbackOverlay.js
- client/src/plugins/report-feedback/ReportFeedbackSystemInfoSection.js
Closes https://github.com/camunda/camunda-modeler/issues/4085
----
> Improve report feedback widget

- client/src/app/App.js
- client/src/app/__tests__/AppSpec.js
> fix(App): do not reopen unsaved Tabs

- package-lock.json
> deps: update to lezer-feel@1.2.6

- docs/.project/RELEASE_TEMPLATE.md
Related to https://github.com/camunda/camunda-docs/issues/3339
> docs: add supported environments update to release issue

- CHANGELOG.md
- client/package.json
- client/src/app/tabs/bpmn/__tests__/DiagramSpec.js
- client/src/app/tabs/bpmn/diagram.bpmn
- package-lock.json
Related to https://github.com/camunda/camunda-modeler/issues/4062
> Do not provide default HTTL configuration for Camunda 7 diagrams

- client/src/app/TabsProvider.js
- client/src/app/__tests__/TabsProviderSpec.js
- client/src/app/tabs/bpmn/__tests__/DiagramSpec.js
- client/src/app/tabs/bpmn/diagram.bpmn
- client/src/util/Flags.js
Related to https://github.com/camunda/camunda-modeler/issues/3869
Related to https://github.com/camunda/camunda-modeler/issues/4062
> feat(platform): rename flag to `default-httl`

- .github/CONTRIBUTING.md
- .github/ISSUE_TEMPLATE/config.yml
- app/lib/menu/menu-builder.js
- client/src/app/tabs/MultiSheetTab.js
Closes https://github.com/camunda/camunda-modeler/issues/4161
> chore: update forum link

- CHANGELOG.md
> chore(CHANGELOG): correct lint rule name

- CHANGELOG.md
> chore(CHANGELOG): remove duplicated entry

- client/src/app/tabs/bpmn/BpmnEditor.js
- client/src/app/tabs/bpmn/__tests__/BpmnEditorSpec.js
- client/src/app/tabs/cloud-bpmn/BpmnEditor.js
- client/src/app/tabs/cloud-bpmn/__tests__/BpmnEditorSpec.js
Closes #3483
[SUPPORT-21053](https://jira.camunda.com/browse/SUPPORT-21053)
> fix: update menu when element templates modal is open

- CHANGELOG.md
- client/package.json
- package-lock.json
deps: update to `@camunda/linting@3.18.0`
Closes #3945
> feat: support compensation events in C8

- client/src/util/Engines.js
- client/src/util/__tests__/EnginesSpec.js
Closes https://github.com/camunda/camunda-modeler/issues/4208
> feat: mark Camunda 8.5 as stable

- client/package.json
- client/src/plugins/camunda-plugin/deployment-tool/DeploymentTool.js
- dev.js
- package-lock.json
Two issues:
* styles broken, fixed via https://github.com/camunda/camunda-modeler/pull/4215/commits/59077c9c3f17ac4cc838e2ea368a391541061b3e
* even after reverting formik bump I saw a forced app reload on C7 diagram (`resources/diagram/simple.bpmn`) deploy dialog open, fixed via https://github.com/camunda/camunda-modeler/pull/4215/commits/721ca1ec2a35de6aaed4710345fb812eb58cc05a
---
---
Closes https://github.com/camunda/camunda-modeler/issues/4213
> deps(client): pin formik to v2.0.4

- CHANGELOG.md
- client/package.json
- package-lock.json
Closes #4216
Closes #4217
Closes #4218
> deps: update to `@bpmn-io/form-js@1.8.2`

- client/src/util/Engines.js
- client/src/util/__tests__/EnginesSpec.js
Nearly forgot about that one :see_no_evil:
> feat: mark 7.21 as the latest stable Camunda 7 version

- CHANGELOG.md
- client/package.json
- package-lock.json
Related to https://github.com/bpmn-io/bpmn-js-element-templates/issues/78
> deps: update to bpmn-js-element-templates@1.15.0

- client/package.json
- package-lock.json
related to https://github.com/bpmn-io/internal-docs/issues/913
This ensures we do not send sensitive data to mixpanel
> deps: update to bpmn-js-tracking@0.5.0

- .github/workflows/MERGE_MAIN_TO_DEVELOP.yml
> ci: use conventional commit message

- client/package.json
- package-lock.json
fix: prevent editor crash when opening form
Closes https://github.com/camunda/camunda-modeler/issues/4240
> deps: update to @bpmn-io/form-js@1.8.5

- client/src/app/tabs/MultiSheetTab.js
> fix: Use more friendly error message

- client/src/plugins/version-info/ReleaseInfo.js
> chore(release-info): update to v5.23.0

- client/src/util/Engines.js
Zeebe 8.6.0-alpha1 already released: https://github.com/camunda/zeebe/releases/tag/8.6.0-alpha1
> feat(engines): add Zeebe 8.6 (alpha)

- docs/.project/INTEGRATION_TEST.md
Ensure we cover (nowadays) core feature of our app.
> docs(INTEGRATION_TEST): cover version chooser and problems panel

- client/package.json
- package-lock.json
> deps: update @camunda/linting to v3.19.0

- CHANGELOG.md
- package-lock.json
- package.json
Closes https://github.com/camunda/camunda-modeler/issues/4299
> deps: update to `electron@30.0.6`

- CHANGELOG.md
- client/package.json
- package-lock.json
> deps: update to `@camunda/linting@3.20.0`

- CHANGELOG.md
- client/package.json
- package-lock.json
This integrated https://github.com/camunda/linting/issues/102
> deps: bump to @camunda/linting@3.21.0

- CHANGELOG.md
- client/package.json
- package-lock.json
- package.json
Update to latest set of dependencies.
> Dependency updates (form-js, electron)

- docs/.project/PATCH_RELEASE_TEMPLATE.md
- docs/.project/RELEASE_TEMPLATE.md
Related to https://github.com/bpmn-io/internal-docs/pull/990
Closes https://github.com/bpmn-io/internal-docs/issues/910
> Ensure we send closed support related issues post release

- docs/.project/INTEGRATION_TEST.md
Related to https://github.com/bpmn-io/internal-docs/issues/909
> docs: make accessibility tests part of the integration test

- .github/PULL_REQUEST_TEMPLATE.md
Related to https://github.com/bpmn-io/.github/pull/7
> chore(.github): adjust PULL_REQUEST_TEMPLATE

- client/src/plugins/zeebe-plugin/start-instance-plugin/StartInstancePlugin.js
> fix: deactivate active button after user cancelled

- client/src/plugins/privacy-preferences/PrivacyPreferencesView.js
- client/src/plugins/privacy-preferences/PrivacyPreferencesView.less
- client/src/plugins/privacy-preferences/__tests__/PrivacyPreferencesViewSpec.js
- client/src/plugins/privacy-preferences/constants.js
- client/src/styles/_base.less
- client/src/styles/_colors.less
Add global link styles to ensure they have a unified look and meet accessibility standards. Test with `npm start`,
closes #4369
closes #4245
> chore(PrivacyPolicy): add link styles

- .github/PULL_REQUEST_TEMPLATE.md
- .github/workflows/COMMENT_DEVELOP_FIX.yml
- .github/workflows/NIGHTLY.yml
- .github/workflows/PUBLISH_RELEASE.yml
- client/package.json
- client/src/app/panel/tabs/linting/LintingTab.js
- client/src/app/panel/tabs/linting/LintingTab.less
- client/src/app/tabs/EngineProfile.js
- client/src/index.js
- client/src/plugins/camunda-plugin/deployment-tool/DeploymentConfigOverlay.less
- client/src/plugins/privacy-preferences/PrivacyPreferencesView.js
- client/src/plugins/privacy-preferences/PrivacyPreferencesView.less
- client/src/plugins/privacy-preferences/__tests__/PrivacyPreferencesViewSpec.js
- client/src/plugins/privacy-preferences/constants.js
- client/src/plugins/zeebe-plugin/deployment-plugin/DeploymentPluginOverlay.less
- client/src/plugins/zeebe-plugin/start-instance-plugin/StartInstancePlugin.js
- client/src/shared/ui/form/FileInput.js
- client/src/shared/ui/form/ToggleSwitch.js
- client/src/styles/_base.less
- client/src/styles/_colors.less
- client/src/styles/_forms.less
- client/src/util/a11y.js
- docs/.project/INTEGRATION_TEST.md
- docs/.project/PATCH_RELEASE_TEMPLATE.md
- docs/.project/RELEASE_TEMPLATE.md
- package-lock.json
- package.json
The PR adds accessible labels for inputs where they were missing.
This required some substantial changes in the toggle switch, but it still works:
https://github.com/camunda/camunda-modeler/assets/28307541/38674415-10c6-4064-9bda-8e8b88e02db6
Closes #4367
> fix: add accessible names

- client/src/plugins/version-info/ReleaseInfo.js
Updates release info with latest changes:
related to https://github.com/camunda/camunda-modeler/issues/4363
> chore(ReleaseInfo): update to v5.25.0

- CHANGELOG.md
This PR fixes a link in changelog which was probably a copy & paste error.
> chore: fix link in changelog

- CHANGELOG.md
- package-lock.json
Integrate latest `bpmnlint-plugin-camunda-compat` release to fix loop detection for big diagrams:
closes https://github.com/camunda/camunda-modeler/issues/4401
Try out with Diagram linked in support case: [SUPPORT-22488](https://jira.camunda.com/browse/SUPPORT-22488)
> deps: update to bpmnlint-plugin-camunda-compat@2.21.1

- client/src/app/tabs/EngineProfile.js
I struggled to understand the original text ("unsupported version of _what_?"), so this is my attempt to simplify it:
Related to https://github.com/camunda/camunda-modeler/issues/2682
>  chore(EngineProfile): slightly re-word

- client/src/plugins/version-info/ReleaseInfo.js
> chore: update release info for v5.26.0

- CHANGELOG.md
- client/package.json
- package-lock.json
This PR bumps the variable outline to include a correction in the Tooltips:
related to https://github.com/bpmn-io/variable-outline/pull/2
> deps(client): bump to @bpmn-io/variable-outline@1.0.2

- client/package.json
- package-lock.json
Integrates https://github.com/camunda/form-linting/pull/108.
> deps(client): update @camunda/form-linting to v0.17.0

- CHANGELOG.md
- client/src/plugins/version-info/ReleaseInfo.js
* updates changelog
* updates release info
Depends on https://github.com/camunda/camunda-modeler/pull/4494.
> Prepare v5.27 Release

- client/src/plugins/version-info/ReleaseInfo.js
Adjusts the wording according to previous discussions (cf. https://github.com/camunda/camunda-modeler/pull/4502#discussion_r1749323309).
> chore: adjust release info wording

- client/package.json
- package-lock.json
Updates @camunda/linting to latest to fix https://github.com/camunda/camunda-modeler/issues/4519.
Closes https://github.com/camunda/camunda-modeler/issues/4519
> deps: update @camunda/linting to v3.27.0

- package-lock.json
Works in dmn-js:
Works in bpmn-js:
Closes #4500
> Support Camuna 8.6 FEEL built-ins

- CHANGELOG.md
- client/package.json
- package-lock.json
Update to @bpmn-io/form-js@1.10.1.
> deps: update to form-js@1.10.1

- CHANGELOG.md
This moves new `feel-lint` feature to the General section as it's available in all editors.
> chore: improve changelog

- CHANGELOG.md
This adds fixes provided with form-js@1.10.1.
> chore: add forms section to changelog

- client/package.json
- package-lock.json
Finalizes https://github.com/camunda/camunda-modeler/pull/4563.
> Revert playground

- CHANGELOG.md
- client/package.json
- package-lock.json
Changelog: https://github.com/camunda/improved-canvas/blob/main/CHANGELOG.md#175
(No relevant changes in Desktop Modeler context).
> deps: bump to @camunda/improved-canvas@1.7.5

- client/src/app/panel/tabs/linting/LintingTab.js
- client/src/app/panel/tabs/linting/__tests__/LintingTabSpec.js
Displays ID or name unaltered.
Closes #4597
> fix(linting-tab): display unaltered name or ID

- client/src/util/Engines.js
Adds Camunda 8 and Camunda 7 alpha versions to the version selector:
related to https://github.com/camunda/camunda-modeler/issues/4610
> feat: add new alpha versions

- client/package.json
- package-lock.json
This should address various local and CI failures we're seeing (https://github.com/camunda/camunda-modeler/pull/4639, https://github.com/camunda/camunda-modeler/pull/4638, ...).
> chore: bump puppeteer

- client/src/plugins/version-info/ReleaseInfo.js
Updates the release info for [v5.29.0](https://github.com/camunda/camunda-modeler/issues/4594) :
> chore: add v5.29.0 release info

- CHANGELOG.md
- client/src/app/App.js
- client/src/app/__tests__/AppSpec.js
> fix: camunda 8 extension issue .bpmn

- docs/.project/INTEGRATION_TEST.md
- docs/.project/RELEASE_TEMPLATE.md
"Create a feature branch" sounds too cryptic. We can clarify that a PR is the way to go.
> docs: clarify release info update

- CHANGELOG.md
- client/package.json
- package-lock.json
This version fixes the C7 `form-js` mapping (https://github.com/camunda/form-linting/pull/111) and [bumps some deps](https://github.com/camunda/form-linting/blob/main/CHANGELOG.md#0190)
Closes https://github.com/camunda/camunda-modeler/issues/4733
> deps: bump `@camunda/form-linting`

- docs/.project/RELEASE_TEMPLATE.md
Closes https://github.com/camunda/camunda-modeler/issues/4689
This adds a task of sending a message to support. 
> docs: add support message to release template

- docs/.project/RELEASE_TEMPLATE.md
This updates the release issue with new timing and automation mark for support notification. The notice will take form of https://camunda.slack.com/archives/CHAC0L80M/p1736418307219489
Cf. https://github.com/camunda/camunda-modeler/blob/1d813edbcbec488cd7731ed45e96bf333aca38a1/.github/workflows/RELEASE.yml#L173
> docs: update support notification

- package-lock.json
- package.json
Related to https://github.com/electron/rebuild/issues/1073#issuecomment-2594789958
This is to make app build on Windows again. 
> chore: update build deps

- client/src/app/tabs/cloud-bpmn/__tests__/BpmnEditorSpec.js
- client/test/mocks/bpmn-js/Modeler.js
Ensure cloud BPMN editor provides the up-to-date versions of the app and runtime platform to the element templates module.
More on the engines compatibility feature: https://github.com/bpmn-io/bpmn-js-element-templates/pull/132
Closes #4760
> test: element templates engines integration

- CHANGELOG.md
- app/package.json
- client/package.json
- client/src/app/panel/tabs/linting/LintingTab.js
- client/src/app/panel/tabs/linting/__tests__/LintingTabSpec.js
- package-lock.json
Incorporates the latest version of [@camunda/linting](https://github.com/camunda/linting), rendering documentation URL sourced from `meta?.documentation?.url`, if provided by rules:
No expected user-facing changes. All [provided guidance](https://docs.camunda.io/docs/next/components/modeler/reference/modeling-guidance/) should be linked from within the modeler.
Closes https://github.com/camunda/camunda-modeler/issues/4491
Closes https://github.com/camunda/camunda-modeler/issues/4811
Incorporates https://github.com/camunda/camunda-modeler/pull/4829
> Modern linting

- CHANGELOG.md
- client/package.json
- package-lock.json
Update latest *bpmn modeling dependencies.
Closes https://github.com/camunda/camunda-modeler/issues/4523
Closes https://github.com/camunda/camunda-modeler/issues/4802
> deps(client): update to `camunda-bpmn-js@5.6.0`

- app/lib/zeebe-api/zeebe-api.js
Fixes https://github.com/camunda/camunda-modeler/commit/e20f4bb76c3c0a0bf9fd84090e0aa0f7aac48058#r152769523.
> chore(app): correct type annotation

- CHANGELOG.md
- client/package.json
- package-lock.json
Integrate `@camunda/linting@3.33.0` with `bpmnlint:correctness` ruleset. Follow-up to #4811.
> deps: update to `@camunda/linting@3.33.0`

- client/src/plugins/version-info/ReleaseInfo.js
Updates the v5.33.0 release information.
Related to https://github.com/camunda/camunda-modeler/issues/4825
> Prepare v5.33 release info

- docs/.project/RELEASE_TEMPLATE.md
We want to make sure our tools are integrated into the Web Modeler.
Not sure about the exact wording and order of tasks.
> chore(docs): update release issue template with Web Modeler deps update

- docs/.project/RELEASE_TEMPLATE.md
Related to https://camunda.slack.com/archives/GP70M0J6M/p1741163415194969
We want to avoid situations where a release is published accidentally. This can be removed once https://github.com/camunda/camunda-modeler/issues/4243 is fixed.
> docs: document Windows signing explicitly

- client/src/util/Engines.js
- client/src/util/__tests__/EnginesSpec.js
Closes #4900
- mark Camunda 7.23 and Camunda 8.7 as latest
> feat: mark Camunda 7.23 and Camunda 8.7 as latest

- CHANGELOG.md
- client/package.json
- package-lock.json
reverted fix ``FEAT`: trim trailing whitespaces from all input fields except expressions ([#4818](https://github.com/camunda/camunda-modeler/issues/4818), [#2385](https://github.com/camunda/camunda-modeler/issues/2385), [bpmn-io/properties-panel#309](https://github.com/bpmn-io/properties-panel/issues/309))
removed changelog entry
> Update properties-panel deps

- CHANGELOG.md
- client/package.json
- package-lock.json
This PR fixes the problem detected in the release candidate: https://camunda.slack.com/archives/GP70M0J6M/p1742890716277539?thread_ts=1742548611.173819&cid=GP70M0J6M
> deps: update to `camunda-bpmn-js@5.7.1`

- client/package.json
- package-lock.json
Closes https://github.com/camunda/camunda-modeler/issues/4873
> deps(client): update @camunda/linting

- client/package.json
- package-lock.json
This PR updates the app to `@bpmn-io/variable-outline@1.0.5` which fixes the problem that caused error to be thrown in dev mode.
https://github.com/user-attachments/assets/948c0696-61e0-4541-94ed-c5c7e17d5b91
Closes #4940
> deps: update to `@bpmn-io/variable-outline@1.0.5`

- client/src/plugins/version-info/ReleaseInfo.js
Updated Release Info for v5.34.0
> chore(release-info): update for v5.34.0

- .github/workflows/CHECK_LICENSES.yml
Related to https://github.com/camunda/team-infrastructure/issues/751 and previous PR https://github.com/camunda/camunda-modeler/pull/4937.
This PR extends the FOSSA integration to include tags in addition to the `develop` and `main` branches. Like the previous PR, it only pushes data (dependency graph) to FOSSA and does not introduce any blocking checks.
Internally, if the commit has already been scanned by FOSSA (e.g., in the main branch), it will just refer to the existing scan (using the revision ID). If no scan exists (it might happen), a new scan will be triggered and performed by FOSSA (internally).
`${{ github.ref_name }}` retrieves the tag name, as for the branch. Tests with tags have been performed on a separate test repository.
To ensure you provided everything we need to look …
> chore(fossa): extend integration to tags

- client/package.json
- package-lock.json
This fixes parser issues in the RPA editor
[screencap-2025-04-08-14-25-01.webm](https://github.com/user-attachments/assets/84b9ea16-323a-4603-8f0b-bac57cfc65cb)
To try out:
- Start the Modeler & create a new RPA file
- Add a lot of spaces
- The Editor does not freeze
related to 
- https://github.com/camunda/rpa-frontend/issues/11
- https://camunda.slack.com/archives/C07DA2WBMAL/p1743767755111479
> chore: update to @camunda/rpa-integration@0.3.1

- client/src/util/Engines.js
Related to https://github.com/camunda/camunda-modeler/issues/4984
add camunda 7.24 as alpha
> feat: support camunda 7.24 (alpha)

- resources/platform/linux/support/camunda-modeler.desktop
- resources/platform/linux/support/xdg_register.sh
- resources/platform/linux/support/xdg_unregister.sh
Follow-up on https://github.com/camunda/camunda-modeler/pull/4989:
* make desktop file external resource
* use on board utilities to modify and validate it
Read more on Desktop files and edit tools [here](https://www.cyberciti.biz/howto/how-to-install-and-edit-desktop-files-on-linux-desktop-entries/).
> feat(platform/linux): extract desktop file from register script

- client/src/plugins/version-info/ReleaseInfo.js
- client/src/plugins/version-info/VersionInfoOverlay.js
Update release info and fix link to release blog
> Release-notes

- docs/.project/RELEASE_TEMPLATE.md
document how to increment release canditate version (eg from `1.2.3-rc.0` to `1.2.3-rc.1`)
> document prerelease semver bump

- docs/.project/RELEASE_TEMPLATE.md
- [add self-managed downloads page](https://github.com/camunda/camunda-modeler/pull/5031/commits/38e4a3ca4e8b715f0045808de2f801b3ed5f5209)
- [clarify when to merge PRs](https://github.com/camunda/camunda-modeler/pull/5031/commits/89751833948433de2afcd406e05ca49b8fe5a888)
> Improve release issue

- .github/workflows/BUILD_ON_DEMAND.yml
- .github/workflows/NIGHTLY.yml
- .github/workflows/RELEASE.yml
- package-lock.json
- package.json
- tasks/distro.js
This sets up azure trusted signing so that we can use CI to sign artifacts again.
Closes #4243
> Setup Azure Trusted Signing for Windows

- CHANGELOG.md
- client/package.json
- package-lock.json
This update fixes the problem reported via https://camunda.slack.com/archives/C032H77434N/p1748016281595929 
https://github.com/user-attachments/assets/742ceba1-be9d-4f4f-9101-442140bce221
> deps: update to `@bpmn-io/properties-panel@3.27.3`

- client/src/plugins/version-info/ReleaseInfo.js
This PR updates the release info to v5.36.
Related to #5035
> chore: update release info to v5.36.0

- client/src/plugins/process-applications/ProcessApplicationsDeploymentPlugin.js
- client/src/plugins/process-applications/__tests__/ProcessApplicationsDeploymentPluginSpec.js
This PR unlocks RPA files deployment in the context of a process application.
Closes #5060
https://github.com/user-attachments/assets/1ea72e1b-2f42-4dc7-aeff-bbcd35cea592
> Deploy rpa files in process application

- CHANGELOG.md
- client/package.json
- package-lock.json
Closes #5071
This updates the properties panel to the version with a fix for #5071.
> deps: update to `@bpmn-io/properties-panel@3.27.4`

- client/src/plugins/zeebe-plugin/deployment-plugin/DeploymentConfigForm.js
- client/src/plugins/zeebe-plugin/deployment-plugin/DeploymentPluginOverlay.js
- client/src/plugins/zeebe-plugin/deployment-plugin/__tests__/DeploymentConfigFormSpec.js
- client/src/plugins/zeebe-plugin/start-instance-plugin/StartInstanceConfigForm.js
- client/src/plugins/zeebe-plugin/start-instance-plugin/StartInstancePluginOverlay.js
- client/src/plugins/zeebe-plugin/start-instance-plugin/__tests__/StartInstanceConfigFormSpec.js
> fix(deployment): show validation error after touched

- README.md
Ensure our documentation captures:
* This is a desktop application
* Use it + your favorite IDE to implement Camunda
Related to https://github.com/bpmn-io/internal-docs/issues/1202
> docs: reword introduction

- client/src/app/__tests__/helpers/renderEditor.js
- client/src/app/tabs/bpmn/__tests__/BpmnEditorSpec.js
- client/src/app/tabs/cloud-bpmn/__tests__/BpmnEditorSpec.js
Migrate tests for both BPMN editors.
Extract a helper function to render all editors in tests in the same way.
Related to https://github.com/camunda/camunda-modeler/issues/3856
> test: migrate BpmnEditor to RTL

- client/src/app/EmptyTab.js
- client/src/app/__tests__/AppSpec.js
- client/src/app/__tests__/EmptyTabSpec.js
Migrate App and EmptyTab tests to React Testing Library.
Related to #3856
> test: migrate `AppSpec` and `EmptyTabSpec` to `@testing-library/react`

- client/package.json
- client/src/app/TabsProvider.js
- client/src/app/tabs/rpa/RPAEditor.js
- client/src/app/tabs/rpa/RPAEditor.less
- client/src/app/tabs/rpa/__tests__/RPAEditorSpec.js
- package-lock.json
Related Product-Hub epic: https://github.com/camunda/product-hub/issues/2710
This PR introduces:
- The ability to add additional files to the RPA file. The main use-case is template matching.
- Linting (Multi-file is only supported from 8.8) + working engine version selection
[screencap-2025-07-14-11-09-20.webm](https://github.com/user-attachments/assets/0835bde1-9574-484c-86ac-989c011f98c2)
You can find a build-on-demand artifacts here:
- https://camunda-modeler-on-demand.s3.eu-central-1.amazonaws.com/rpa-multi-file-2/camunda-modeler-rpa-multi-file-2-linux-x64.tar.gz
- https://camunda-modeler-on-demand.s3.eu-central-1.amazonaws.com/rpa-multi-file-2/camunda-modeler-rpa-multi-file-2-mac-x64.dmg
- https://camunda-modeler-on-demand.s3.eu-central-1.amazonaws.com/rpa-multi-file-2/camunda-modele …
> feat: add RPA multi-file and linting

- client/src/plugins/version-info/ReleaseInfo.js
Related to https://github.com/camunda/camunda-modeler/issues/5151
> chore(ReleaseInfo): update for v5.38.0

- app/lib/zeebe-api/zeebe-api.js
- client/src/plugins/zeebe-plugin/deployment-plugin/DeploymentConfigValidator.js
- client/src/plugins/zeebe-plugin/deployment-plugin/__tests__/DeploymentConfigValidatorSpec.js
- client/src/remote/ZeebeAPI.js
Related to https://github.com/camunda/camunda-modeler/issues/5103
support grpc and grpcs urls for camunda 8 deployments (SaaS, SelfManaged, c8run)
> feat: support grpc(s) deployment URLs

- client/src/app/panel/Panel.js
- client/src/app/panel/__tests__/PanelSpec.js
Related to: #3856 
- Replaced enzyme with `@testing-library/react`
- General cleanup 
> test(panelSpec): removed enzyme and replaced with @testing-library/react

- app/lib/file-context/processors/__tests__/util-spec.js
- app/lib/file-context/processors/util.js
This builds on top of https://github.com/camunda/camunda-modeler/pull/5205 and adds tests to verify our `findProcessAppplicationFile` utility works as expected.
Closes #5205 
Closes #5204
> Ensure process application is found also for relative file references

- client/src/app/panel/tabs/task-testing/TaskTestingTab.js
Links to https://docs.camunda.com/docs/components/modeler/desktop-modeler/task-testing/ ([still in progress](https://github.com/camunda/camunda-docs/pull/6736)).
Closes #5297
> fix(TaskTestingTab): add docs link
